import type { Module } from '../types';

export const foundations: Module = {
  id: 'foundations',
  title: 'Foundations & Inference',
  blurb:
    'Where annotations are required, where they are noise, and how TypeScript widens what you write. Everything here is plain Node — no framework, no JSX.',
  status: 'ready',
  exercises: [
    {
      id: 'annotate-a-function',
      title: 'Annotate what TypeScript cannot guess',
      brief: [
        '`strict` mode refuses to infer parameter types from nothing. A bare parameter is an',
        'implicit `any`, and an implicit `any` is an error.',
        '',
        'Annotate the three parameters so this compiles. Leave the *return* type alone —',
        'TypeScript already knows it, and writing it out by hand would be noise you have to',
        'maintain.',
      ].join('\n'),
      starterCode: [
        'export function buildConnectionString(host, port, useTls) {',
        "  const scheme = useTls ? 'https' : 'http';",
        "  return scheme + '://' + host + ':' + port;",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { buildConnectionString } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<typeof buildConnectionString, (host: string, port: number, useTls: boolean) => string>',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export function buildConnectionString(host: string, port: number, useTls: boolean) {',
        "  const scheme = useTls ? 'https' : 'http';",
        "  return scheme + '://' + host + ':' + port;",
        '}',
      ].join('\n'),
      hints: [
        'The error is "Parameter implicitly has an \'any\' type" — TypeScript is telling you exactly which ones it cannot infer.',
        'A port is a number, and `useTls` reads like a yes/no flag.',
        'Write `host: string, port: number, useTls: boolean`. Do not add a return type — inference has it covered.',
      ],
    },
    {
      id: 'widening',
      title: 'let widens, const does not',
      brief: [
        'TypeScript infers a *wider* type than you might expect from `let`, because a `let`',
        'can be reassigned. `let x = 3000` is `number`; `const x = 3000` is the literal type',
        '`3000`.',
        '',
        'This matters more than it looks: literal types are what make unions, discriminated',
        'unions and exhaustiveness checks work at all.',
        '',
        'Make both values keep their literal types.',
      ].join('\n'),
      starterCode: ['export let DEFAULT_PORT = 3000;', "export let LOG_PREFIX = '[app]';"].join('\n'),
      hiddenChecks: [
        "import type { DEFAULT_PORT, LOG_PREFIX } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof DEFAULT_PORT, 3000>>,',
        "  Expect<Equal<typeof LOG_PREFIX, '[app]'>>,",
        '];',
      ].join('\n'),
      solution: ['export const DEFAULT_PORT = 3000;', "export const LOG_PREFIX = '[app]';"].join('\n'),
      hints: [
        'You do not need to add any annotation here. Change a keyword.',
        'A binding that can never be reassigned can safely be inferred as its exact value.',
        'Swap both `let` for `const`.',
      ],
    },
    {
      id: 'any-vs-unknown',
      title: 'Stop `any` at the boundary',
      brief: [
        '`JSON.parse` returns `any`, which means every property access downstream is',
        'unchecked. `any` is contagious: it silently disables the compiler everywhere it',
        'flows.',
        '',
        '`unknown` is the safe counterpart. It holds anything, but forces a check before you',
        'use it — which is exactly what you want at the edge of your program, where the data',
        'came from a file or a network call and you have no guarantees.',
        '',
        'Make `parseJson` hand back `unknown` instead of leaking `any` into your codebase.',
      ].join('\n'),
      starterCode: [
        'export function parseJson(text: string) {',
        '  return JSON.parse(text);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { parseJson } from './exercise';",
        'type _cases = [Expect<Equal<ReturnType<typeof parseJson>, unknown>>];',
      ].join('\n'),
      solution: [
        'export function parseJson(text: string): unknown {',
        '  return JSON.parse(text);',
        '}',
      ].join('\n'),
      hints: [
        'Inference is giving you `any` here because that is what `JSON.parse` is declared to return.',
        'This is one of the few places an explicit return type earns its keep: you are overriding inference on purpose.',
        'Add `: unknown` as the return type.',
      ],
    },
    {
      id: 'literal-unions',
      title: 'A union of literals beats `string`',
      brief: [
        '`level: string` accepts `"dbeug"`, `"DEBUG"`, `""` and every other typo. A union of',
        'string literals accepts exactly four values and autocompletes them for you.',
        '',
        'Narrow `LogLevel` to just the four levels this logger supports.',
      ].join('\n'),
      starterCode: [
        'export type LogLevel = string;',
        '',
        'export function shouldLog(level: LogLevel, threshold: LogLevel): boolean {',
        '  return level === threshold;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { LogLevel } from './exercise';",
        "type _cases = [Expect<Equal<LogLevel, 'debug' | 'info' | 'warn' | 'error'>>];",
      ].join('\n'),
      solution: [
        "export type LogLevel = 'debug' | 'info' | 'warn' | 'error';",
        '',
        'export function shouldLog(level: LogLevel, threshold: LogLevel): boolean {',
        '  return level === threshold;',
        '}',
      ].join('\n'),
      hints: [
        'A string literal like `\'debug\'` is a valid type on its own.',
        'Combine several with the `|` union operator.',
        "Write `type LogLevel = 'debug' | 'info' | 'warn' | 'error';`",
      ],
    },
    {
      id: 'as-const',
      title: 'Derive the type from the value',
      brief: [
        'You already wrote the list of HTTP methods once. Writing the union out again by hand',
        'means two things to keep in sync forever.',
        '',
        '`as const` freezes an array into a readonly tuple of literals, and `T[number]` reads',
        'out its element type. Together they let the *value* be the single source of truth.',
        '',
        'Make `HttpMethod` derive itself from `HTTP_METHODS`, without repeating the strings.',
      ].join('\n'),
      starterCode: [
        "export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE'];",
        '',
        'export type HttpMethod = string;',
      ].join('\n'),
      hiddenChecks: [
        "import type { HttpMethod } from './exercise';",
        "type _cases = [Expect<Equal<HttpMethod, 'GET' | 'POST' | 'PUT' | 'DELETE'>>];",
      ].join('\n'),
      solution: [
        "export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE'] as const;",
        '',
        'export type HttpMethod = (typeof HTTP_METHODS)[number];',
      ].join('\n'),
      hints: [
        'Without `as const`, that array is inferred as `string[]` — the literals are already lost before you can read them back.',
        '`typeof HTTP_METHODS` gets you the type of the value. Indexing a tuple type with `[number]` gets you the union of its elements.',
        'Append `as const` to the array, then write `export type HttpMethod = (typeof HTTP_METHODS)[number];`',
      ],
    },
    {
      id: 'function-types',
      title: 'Type a callback properly',
      brief: [
        '`Function` is the `any` of callable values: it accepts any arguments and returns',
        '`any`. It tells you nothing and checks nothing.',
        '',
        'Describe the actual shape instead — this is the classic Express-style middleware',
        'signature.',
      ].join('\n'),
      starterCode: [
        'export interface RequestLike {',
        '  url: string;',
        '  method: string;',
        '}',
        '',
        'export type Middleware = Function;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Middleware, RequestLike } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Middleware, (req: RequestLike, next: () => void) => void>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface RequestLike {',
        '  url: string;',
        '  method: string;',
        '}',
        '',
        'export type Middleware = (req: RequestLike, next: () => void) => void;',
      ].join('\n'),
      hints: [
        'A function type is written like an arrow function with types instead of a body.',
        'It takes the request first and a `next` callback second, and returns nothing.',
        'Write `type Middleware = (req: RequestLike, next: () => void) => void;`',
      ],
    },
    {
      id: 'async-returns',
      title: 'An async function always returns a Promise',
      brief: [
        'Marking a function `async` wraps its return value in a `Promise`, whether you like',
        'it or not. Annotating it with a bare `string` is therefore always wrong, and',
        'TypeScript says so.',
        '',
        'Fix the annotation.',
      ].join('\n'),
      starterCode: [
        "import { readFile } from 'node:fs/promises';",
        '',
        'export async function loadEnvFile(path: string): string {',
        "  return readFile(path, 'utf8');",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { loadEnvFile } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof loadEnvFile, (path: string) => Promise<string>>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { readFile } from 'node:fs/promises';",
        '',
        'export async function loadEnvFile(path: string): Promise<string> {',
        "  return readFile(path, 'utf8');",
        '}',
      ].join('\n'),
      hints: [
        'Read the error: "The return type of an async function must be the global Promise<T> type."',
        'The `T` is what you `return` from inside the function body.',
        'Change `: string` to `: Promise<string>`.',
      ],
    },
    {
      id: 'tuples-and-readonly',
      title: 'Tuples and readonly arrays',
      brief: [
        '`number[]` says "some numbers, any amount". Sometimes you mean something stricter:',
        'exactly two numbers, or a list nobody is allowed to push to.',
        '',
        'A tuple `[number, number]` pins down the length and the position of each element. A',
        '`readonly number[]` keeps the length open but removes the mutating methods.',
        '',
        'Give each alias the right shape.',
      ].join('\n'),
      starterCode: ['export type Coordinate = number[];', '', 'export type FrozenPorts = number[];'].join('\n'),
      hiddenChecks: [
        "import type { Coordinate, FrozenPorts } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Coordinate, [number, number]>>,',
        '  Expect<Equal<FrozenPorts, readonly number[]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Coordinate = [number, number];',
        '',
        'export type FrozenPorts = readonly number[];',
      ].join('\n'),
      hints: [
        'A tuple type is written with square brackets around its element types, not after them.',
        'The `readonly` modifier goes in front of an array type.',
        'Write `[number, number]` and `readonly number[]`.',
      ],
    },
  ],
};
