import type { Module } from '../types';

export const foundations: Module = {
  id: 'foundations',
  title: 'Foundations & Inference',
  blurb:
    'Where annotations are required, where they are noise, and how TypeScript widens what you write. Everything here is plain Node — no framework, no JSX.',
  status: 'ready',
  exercises: [
    {
      id: 'annotate-a-function',
      title: 'Annotate what TypeScript cannot guess',
      concept: [
        'TypeScript does far more inference than most people coming from JavaScript expect. You',
        'do not annotate everything — you annotate the things the compiler genuinely cannot',
        'work out, and let it derive the rest.',
        '',
        'It is very good at return types. Give it the parameters and it reads the body:',
        '',
        '```ts',
        'function double(n: number) {',
        '  return n * 2;',
        '}',
        '',
        '// TypeScript already knows: (n: number) => number',
        '// Writing `: number` on the end would be true, but it would also be one',
        '// more thing to update the day the body changes.',
        '```',
        '',
        'What it cannot do is invent a *parameter* type. Nothing in the function body tells it',
        'what a caller will pass — the body is downstream of that decision. So an unannotated',
        'parameter has no type at all, which TypeScript calls an *implicit any*:',
        '',
        '```ts-bad',
        'function double(n) {',
        '  return n * 2;',
        '}',
        '// Parameter "n" implicitly has an "any" type.',
        '```',
        '',
        'The `noImplicitAny` flag — on by default under `strict` — turns that into an error',
        'rather than a silent hole. It is the single highest-value flag in the compiler, because',
        'an implicit `any` disables type checking for everything downstream of it without ever',
        'saying so.',
        '',
        'So the rule of thumb for functions: **annotate the inputs, let it infer the output.**',
      ].join('\n'),
      brief: [
        'Annotate the three parameters so this compiles.',
        '',
        'Leave the return type alone — TypeScript already knows it.',
      ].join('\n'),
      debrief: [
        'You annotated the parameters and left the return type inferred. That is the right',
        'default, but it is a default, not a law — there are two cases where writing the return',
        'type out earns its keep.',
        '',
        'The first is a **public API boundary**. Inference means the body defines the signature,',
        'so a careless change to the body silently changes what callers see. An explicit return',
        'type pins the contract, and the error lands in the function you edited rather than in',
        'the five places that call it.',
        '',
        'The second is when you want the compiler to check the body *against* your intent:',
        '',
        '```ts-bad',
        'function findPort(config: { port?: number }): number {',
        '  return config.port;',
        '}',
        '// Type "number | undefined" is not assignable to type "number".',
        '```',
        '',
        'Without the annotation that function would happily infer `number | undefined` and push',
        'the problem to its callers. With it, the mistake surfaces here.',
        '',
        'What you should *not* do is annotate everything reflexively. Every redundant annotation',
        'is a second copy of a fact the compiler already knows, and copies drift.',
      ].join('\n'),
      starterCode: [
        'export function buildConnectionString(host, port, useTls) {',
        "  const scheme = useTls ? 'https' : 'http';",
        "  return scheme + '://' + host + ':' + port;",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { buildConnectionString } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<typeof buildConnectionString, (host: string, port: number, useTls: boolean) => string>',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export function buildConnectionString(host: string, port: number, useTls: boolean) {',
        "  const scheme = useTls ? 'https' : 'http';",
        "  return scheme + '://' + host + ':' + port;",
        '}',
      ].join('\n'),
      hints: [
        'The error is "Parameter implicitly has an \'any\' type" — TypeScript is telling you exactly which ones it cannot infer.',
        'A port is a number, and `useTls` reads like a yes/no flag.',
        'Write `host: string, port: number, useTls: boolean`. Do not add a return type — inference has it covered.',
      ],
    },
    {
      id: 'widening',
      title: 'let widens, const does not',
      concept: [
        'When TypeScript infers a type from a value, it has to make a judgement call: do you',
        'mean *this exact value*, or *values like this one*?',
        '',
        'For a `let`, it assumes the second. The binding can be reassigned, so a type of exactly',
        '`3000` would be useless — you could never store anything else in it. This is called',
        '*widening*: the literal type `3000` widens to `number`.',
        '',
        'For a `const`, reassignment is impossible, so it keeps the literal:',
        '',
        '```ts',
        'let mutablePort = 3000;',
        '//  mutablePort: number',
        '',
        'const fixedPort = 3000;',
        '//    fixedPort: 3000',
        '```',
        '',
        'That second type — `3000` — is a *literal type*: a type inhabited by exactly one value.',
        'It looks like a curiosity and it is actually load-bearing. Literal types are what make',
        'unions like `\'GET\' | \'POST\'` meaningful, what makes discriminated unions narrow, and',
        'what makes exhaustiveness checking possible. Almost everything interesting in the next',
        'few modules is built on them.',
        '',
        'The distinction bites in practice when you pass a value somewhere strict:',
        '',
        '```ts-bad',
        'let method = \'GET\';',
        'const send = (m: \'GET\' | \'POST\') => m;',
        'send(method);',
        '// Argument of type "string" is not assignable to',
        '// parameter of type "GET" | "POST".',
        '```',
        '',
        'The value is fine. The *type* was widened away before it got there.',
      ].join('\n'),
      brief: ['Make both values keep their literal types.', '', 'You should not need to add any annotation.'].join('\n'),
      debrief: [
        'One `const` is not always enough, and this is where people get caught.',
        '',
        '`const` only stops the *binding* from being reassigned. It says nothing about the',
        'contents of an object, so properties inside a `const` object still widen:',
        '',
        '```ts',
        'const config = { retries: 3 };',
        '//    config: { retries: number }   <- widened, not 3',
        '',
        'config.retries = 5; // perfectly legal',
        '```',
        '',
        'Which makes sense: the property *is* mutable, so a literal type would be a lie.',
        '',
        'When you want the literal types to survive into an object or array, you need `as const`',
        '— which marks the whole structure readonly and therefore safe to keep narrow. That is',
        'exercise 5, and this is the reason it exists.',
        '',
        'There is one more place widening shows up unexpectedly: a `const` initialised from a',
        'function call gets whatever that function returns, literal or not. `const x =',
        'getPort()` is `number` if `getPort` returns `number`. Widening is about how a type is',
        '*inferred from a literal expression*, not about `const` having magic powers.',
      ].join('\n'),
      starterCode: ['export let DEFAULT_PORT = 3000;', "export let LOG_PREFIX = '[app]';"].join('\n'),
      hiddenChecks: [
        "import type { DEFAULT_PORT, LOG_PREFIX } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof DEFAULT_PORT, 3000>>,',
        "  Expect<Equal<typeof LOG_PREFIX, '[app]'>>,",
        '];',
      ].join('\n'),
      solution: ['export const DEFAULT_PORT = 3000;', "export const LOG_PREFIX = '[app]';"].join('\n'),
      hints: [
        'You do not need to add any annotation here. Change a keyword.',
        'A binding that can never be reassigned can safely be inferred as its exact value.',
        'Swap both `let` for `const`.',
      ],
    },
    {
      id: 'any-vs-unknown',
      title: 'Stop `any` at the boundary',
      concept: [
        '`any` is not a type so much as an instruction to stop type checking. Every operation on',
        'an `any` is permitted, and the result is another `any`:',
        '',
        '```ts',
        'const raw: any = 42;',
        'raw.toUpperCase().flatMap((x: never) => x).whatever;',
        '// Not one error. All of it compiles. All of it crashes.',
        '```',
        '',
        'The dangerous part is that `any` is *contagious*. It flows outward through return',
        'values and property access, quietly switching the compiler off in code far away from',
        'wherever it entered — which is why one `any` at a boundary can hollow out a whole',
        'module.',
        '',
        '`unknown` is the safe counterpart. It also accepts any value, but it permits nothing',
        'until you prove what it is:',
        '',
        '```ts-bad',
        'const raw: unknown = 42;',
        'raw.toUpperCase();',
        '// "raw" is of type "unknown".',
        '```',
        '',
        'That error is the feature. To use an `unknown` you have to narrow it first — with',
        '`typeof`, `instanceof`, or a check of your own — and the compiler then knows what it is',
        'for real rather than taking your word for it.',
        '',
        'This matters most at the edges of your program: JSON from a request body, a file you',
        'just read, a message off a queue. You genuinely do not know what is in there. `unknown`',
        'says so, and forces exactly one validation step before the data gets in.',
        '',
        '`JSON.parse` is declared as returning `any`, which is a historical wart — it predates',
        '`unknown` existing. Overriding that is one of the few places an explicit return type is',
        'obviously right.',
      ].join('\n'),
      brief: ['Make `parseJson` hand back `unknown` instead of leaking `any` into your codebase.'].join('\n'),
      debrief: [
        'Notice what you have done to the callers: they now *have* to check before they use the',
        'result. That is the whole trade. You accepted one inconvenience at the boundary in',
        'exchange for real types everywhere downstream.',
        '',
        'In practice the check is usually a validation library — this is precisely the job zod',
        'does, and module 7 covers deriving your static types from the validator so the two can',
        'never disagree. Hand-rolled, it looks like this:',
        '',
        '```ts',
        'function parseJson(text: string): unknown {',
        '  return JSON.parse(text);',
        '}',
        '',
        'function isUser(value: unknown): value is { id: string } {',
        "  return typeof value === 'object' && value !== null && 'id' in value;",
        '}',
        '',
        'const parsed = parseJson(\'{"id":"u1"}\');',
        'if (isUser(parsed)) {',
        '  parsed.id; // string, and genuinely checked',
        '}',
        '```',
        '',
        'That `value is { id: string }` return type is a *type predicate*, and it is the next',
        'module.',
        '',
        'One more distinction worth filing away: `unknown` is the type every value is assignable',
        '*to*, and `never` is the type assignable *from* nothing at all. They are the two ends of',
        'the type system, and `never` turns out to be surprisingly useful — it is how you get the',
        'compiler to prove you handled every case.',
      ].join('\n'),
      starterCode: ['export function parseJson(text: string) {', '  return JSON.parse(text);', '}'].join('\n'),
      hiddenChecks: [
        "import type { parseJson } from './exercise';",
        'type _cases = [Expect<Equal<ReturnType<typeof parseJson>, unknown>>];',
      ].join('\n'),
      solution: [
        'export function parseJson(text: string): unknown {',
        '  return JSON.parse(text);',
        '}',
      ].join('\n'),
      hints: [
        'Inference is giving you `any` here because that is what `JSON.parse` is declared to return.',
        'This is one of the few places an explicit return type earns its keep: you are overriding inference on purpose.',
        'Add `: unknown` as the return type.',
      ],
    },
    {
      id: 'literal-unions',
      title: 'A union of literals beats `string`',
      concept: [
        'A parameter typed `string` accepts every string in the universe. If your logger handles',
        'four levels, `string` is not describing it — it is describing the absence of a',
        'description.',
        '',
        'A union of literal types says what you actually mean:',
        '',
        '```ts',
        "type LogLevel = 'debug' | 'info' | 'warn' | 'error';",
        '',
        'function log(level: LogLevel, message: string) {',
        '  return `[${level}] ${message}`;',
        '}',
        '',
        "log('warn', 'disk almost full'); // fine",
        '```',
        '',
        'And typos stop compiling:',
        '',
        '```ts-bad',
        "type LogLevel = 'debug' | 'info' | 'warn' | 'error';",
        'declare function log(level: LogLevel, message: string): void;',
        '',
        "log('WARN', 'disk almost full');",
        '// Argument of type "WARN" is not assignable to parameter of type LogLevel.',
        '```',
        '',
        'Two things you get for free, and they are the real reason to do this. Your editor will',
        'autocomplete the four values, so you never have to go and look them up. And when you',
        'later add `\'fatal\'` to the union, every `switch` that does not handle it can be made to',
        'light up — that is the exhaustiveness check in module 2.',
        '',
        'This is also why the previous exercise mattered: a union of literals is only useful if',
        'literal types survive long enough to reach it.',
      ].join('\n'),
      brief: ['Narrow `LogLevel` to just the four levels this logger supports.'].join('\n'),
      debrief: [
        'If you have written other typed languages you may be reaching for an `enum` here.',
        'TypeScript has them, and for this job the string union is usually the better tool.',
        '',
        'A union is *erased* — it exists only at compile time, and the runtime value is a plain',
        'string. That means it interoperates with JSON, database columns and HTTP payloads with',
        'no conversion at all. A `LogLevel` you read from a config file just is a `LogLevel`.',
        '',
        'An `enum`, by contrast, emits a real object into your bundle, and its members are',
        'nominally typed — `LogLevel.Warn` is not interchangeable with the string `\'warn\'` even',
        'though that is what it holds. That nominal behaviour is occasionally what you want, and',
        'usually just friction.',
        '',
        'The middle ground, once you have a list you also need at runtime, is the `as const`',
        'pattern from the next exercise:',
        '',
        '```ts',
        "const LEVELS = ['debug', 'info', 'warn', 'error'] as const;",
        'type LogLevel = (typeof LEVELS)[number];',
        '',
        '// LEVELS is iterable at runtime; LogLevel is the union at compile time;',
        '// and there is exactly one place to add a fifth level.',
        '```',
        '',
        'Worth knowing: `const enum` exists too, and is best avoided — it does not work under',
        'isolated-module transpilers like esbuild and swc, which most modern toolchains use.',
      ].join('\n'),
      starterCode: [
        'export type LogLevel = string;',
        '',
        'export function shouldLog(level: LogLevel, threshold: LogLevel): boolean {',
        '  return level === threshold;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { LogLevel } from './exercise';",
        "type _cases = [Expect<Equal<LogLevel, 'debug' | 'info' | 'warn' | 'error'>>];",
      ].join('\n'),
      solution: [
        "export type LogLevel = 'debug' | 'info' | 'warn' | 'error';",
        '',
        'export function shouldLog(level: LogLevel, threshold: LogLevel): boolean {',
        '  return level === threshold;',
        '}',
      ].join('\n'),
      hints: [
        'A string literal like `\'debug\'` is a valid type on its own.',
        'Combine several with the `|` union operator.',
        "Write `type LogLevel = 'debug' | 'info' | 'warn' | 'error';`",
      ],
    },
    {
      id: 'as-const',
      title: 'Derive the type from the value',
      concept: [
        'You have the list of HTTP methods written down once, as a value. Writing the union out',
        'again as a type gives you two copies of the same fact, and copies drift.',
        '',
        'Three features combine to remove the duplication.',
        '',
        '**`as const`** stops widening for a whole structure. Without it an array of strings is',
        '`string[]` and the literals are gone before you can do anything with them:',
        '',
        '```ts',
        "const loose = ['GET', 'POST'];",
        '//    loose: string[]',
        '',
        "const frozen = ['GET', 'POST'] as const;",
        '//    frozen: readonly ["GET", "POST"]',
        '```',
        '',
        '**`typeof`** crosses from the value world into the type world. `frozen` is a value;',
        '`typeof frozen` is its type, usable anywhere a type is expected.',
        '',
        '**Indexed access** reads a type out of another type, using the same bracket syntax as',
        'property access. Indexing an array or tuple type with `number` gives the union of its',
        'elements:',
        '',
        '```ts',
        "const frozen = ['GET', 'POST'] as const;",
        'type Method = (typeof frozen)[number];',
        '//   Method: "GET" | "POST"',
        '```',
        '',
        'The parentheses are required. `typeof frozen[number]` parses as `typeof (frozen[number])`,',
        'which is not what you want.',
        '',
        'Put together, the value is now the single source of truth: add a method to the array and',
        'the union updates itself.',
      ].join('\n'),
      brief: [
        'Make `HttpMethod` derive itself from `HTTP_METHODS`, without repeating the strings.',
      ].join('\n'),
      debrief: [
        'This pattern — a `const` array plus a derived union — is one you will use constantly.',
        'It gives you a list you can iterate at runtime *and* a type that can never disagree',
        'with it.',
        '',
        'Two follow-ups worth knowing.',
        '',
        '`as const` makes the array `readonly`, which occasionally propagates further than you',
        'expect. A `readonly string[]` is not assignable to a `string[]` parameter, because that',
        'parameter might push to it. If you hit that, the fix is usually to widen the *parameter*',
        'to `readonly string[]` rather than to drop `as const`:',
        '',
        '```ts',
        "const METHODS = ['GET', 'POST'] as const;",
        '',
        '// Accepts both readonly and mutable arrays. Prefer this in signatures.',
        'function describe(items: readonly string[]) {',
        "  return items.join(', ');",
        '}',
        '',
        'describe(METHODS);',
        '```',
        '',
        'And `keyof` is the object-shaped counterpart of `[number]`. Where `(typeof arr)[number]`',
        'gives you the union of an array’s elements, `keyof typeof obj` gives you the union of an',
        'object’s keys — the same trick, one level over. Module 3 leans on it heavily.',
      ].join('\n'),
      starterCode: [
        "export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE'];",
        '',
        'export type HttpMethod = string;',
      ].join('\n'),
      hiddenChecks: [
        "import type { HttpMethod } from './exercise';",
        "type _cases = [Expect<Equal<HttpMethod, 'GET' | 'POST' | 'PUT' | 'DELETE'>>];",
      ].join('\n'),
      solution: [
        "export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE'] as const;",
        '',
        'export type HttpMethod = (typeof HTTP_METHODS)[number];',
      ].join('\n'),
      hints: [
        'Without `as const`, that array is inferred as `string[]` — the literals are already lost before you can read them back.',
        '`typeof HTTP_METHODS` gets you the type of the value. Indexing a tuple type with `[number]` gets you the union of its elements.',
        'Append `as const` to the array, then write `export type HttpMethod = (typeof HTTP_METHODS)[number];`',
      ],
    },
    {
      id: 'function-types',
      title: 'Type a callback properly',
      concept: [
        'Functions are values, so they have types like any other value — and the syntax for',
        'writing one down looks like an arrow function with the body replaced by a return type:',
        '',
        '```ts',
        'type Formatter = (value: number, digits: number) => string;',
        '',
        'const money: Formatter = (value, digits) => value.toFixed(digits);',
        '//                        ^^^^^  ^^^^^^',
        '// No annotations needed: the parameter types flow in from Formatter.',
        '// This is contextual typing, and it is why typing the alias pays off.',
        '```',
        '',
        'The parameter names in the type are documentation only — `(v: number) => string` and',
        '`(value: number) => string` are the same type. Only positions and types matter.',
        '',
        'What you want to avoid is `Function`. It is the `any` of callable values: it accepts any',
        'arguments, returns `any`, and checks nothing. Note that this example compiles cleanly —',
        'that is the problem with it:',
        '',
        '```ts',
        'const run: Function = (a: number) => a + 1;',
        '',
        '// Every line below type-checks. Not one of them survives runtime.',
        "run('nonsense', 1, 2, 3);",
        'run().anything.at.all;',
        '```',
        '',
        'Describing the real shape costs one line and buys you argument checking, return-type',
        'checking, and autocomplete inside every callback you pass.',
      ].join('\n'),
      brief: [
        'Replace `Function` with the actual middleware shape: it takes the request and a `next`',
        'callback, and returns nothing.',
      ].join('\n'),
      debrief: [
        'There is a genuinely surprising rule hiding in that `=> void` you just wrote.',
        '',
        'A function type returning `void` will accept a function that returns *something*. The',
        'return value is simply ignored:',
        '',
        '```ts',
        'type Middleware = (next: () => void) => void;',
        '',
        '// Returns a number, but assigning it to Middleware is allowed.',
        'const counted: Middleware = (next) => {',
        '  next();',
        '  return 42;',
        '};',
        '```',
        '',
        'This looks like a hole and is actually deliberate. It is what lets you write',
        '`items.forEach(item => set.add(item))` — `add` returns the set, `forEach` wants `void`,',
        'and without this rule you would have to wrap every such callback in braces.',
        '',
        'The trap is that it also silently allows `array.forEach(async (x) => { ... })`, where',
        'the returned promise is dropped on the floor and your errors vanish. If you find',
        'yourself passing an `async` callback to something expecting `void`, that is almost',
        'always a bug — reach for a `for...of` loop with `await`, or `Promise.all(items.map(...))`.',
        '',
        'One more thing to file away: writing a property as `method(): void` rather than',
        '`method: () => void` changes how strictly TypeScript checks its parameters. The arrow',
        'form is checked more soundly, so prefer it in type aliases unless you are describing a',
        'real class method.',
      ].join('\n'),
      starterCode: [
        'export interface RequestLike {',
        '  url: string;',
        '  method: string;',
        '}',
        '',
        'export type Middleware = Function;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Middleware, RequestLike } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Middleware, (req: RequestLike, next: () => void) => void>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface RequestLike {',
        '  url: string;',
        '  method: string;',
        '}',
        '',
        'export type Middleware = (req: RequestLike, next: () => void) => void;',
      ].join('\n'),
      hints: [
        'A function type is written like an arrow function with types instead of a body.',
        'It takes the request first and a `next` callback second, and returns nothing.',
        'Write `type Middleware = (req: RequestLike, next: () => void) => void;`',
      ],
    },
    {
      id: 'async-returns',
      title: 'An async function always returns a Promise',
      concept: [
        'The `async` keyword does one thing to a function’s type: it wraps the return value in a',
        '`Promise`. Always, unconditionally, even if the body returns a plain value and never',
        'awaits anything.',
        '',
        '```ts',
        'async function loadCount(): Promise<number> {',
        '  return 42; // a number goes in...',
        '}',
        '',
        'const pending = loadCount();',
        '//    pending: Promise<number>   ...a promise comes out',
        '```',
        '',
        'So annotating an `async` function with a bare `string` is not merely wrong, it is',
        'impossible — the compiler has a dedicated error for it:',
        '',
        '```ts-bad',
        'async function loadName(): string {',
        "  return 'ryan';",
        '}',
        '// The return type of an async function must be the global Promise<T> type.',
        '```',
        '',
        'The `T` you write is what the caller gets after awaiting: whatever the body returns.',
        '',
        'Usefully, `async` does not double-wrap. Returning a `Promise<string>` from an',
        '`async` function still gives you `Promise<string>`, not `Promise<Promise<string>>` —',
        'the language flattens it, which is why `return readFile(...)` inside an async function',
        'is fine and needs no `await`.',
      ].join('\n'),
      brief: ['Fix the return type annotation.', '', 'The body is already correct.'].join('\n'),
      debrief: [
        'Since promise types nest so easily, TypeScript ships a utility for unwrapping them:',
        '`Awaited<T>` gives you the type you would get from awaiting a value, however many',
        'layers deep it is.',
        '',
        '```ts',
        'declare function loadUser(): Promise<{ id: string }>;',
        '',
        'type Pending = ReturnType<typeof loadUser>; // Promise<{ id: string }>',
        'type Loaded = Awaited<Pending>;             // { id: string }',
        '```',
        '',
        'You will reach for that constantly once you start deriving types from existing async',
        'functions rather than declaring them twice. Module 4 covers it properly.',
        '',
        'The other half of this — the part types cannot save you from on their own — is the',
        '**floating promise**. Calling an async function without awaiting it is perfectly legal',
        'TypeScript, and the rejection becomes an unhandled one at runtime:',
        '',
        '```ts',
        'declare function save(): Promise<void>;',
        '',
        'function handler() {',
        '  save(); // no await, no .catch — if this rejects, nothing catches it',
        '}',
        '```',
        '',
        'The compiler will not flag that by default. `@typescript-eslint`’s',
        '`no-floating-promises` rule will, and it is worth turning on in any Node service — it',
        'catches a genuinely common class of production bug that the type system alone does not.',
      ].join('\n'),
      starterCode: [
        "import { readFile } from 'node:fs/promises';",
        '',
        'export async function loadEnvFile(path: string): string {',
        "  return readFile(path, 'utf8');",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { loadEnvFile } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof loadEnvFile, (path: string) => Promise<string>>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { readFile } from 'node:fs/promises';",
        '',
        'export async function loadEnvFile(path: string): Promise<string> {',
        "  return readFile(path, 'utf8');",
        '}',
      ].join('\n'),
      hints: [
        'Read the error: "The return type of an async function must be the global Promise<T> type."',
        'The `T` is what you `return` from inside the function body.',
        'Change `: string` to `: Promise<string>`.',
      ],
    },
    {
      id: 'tuples-and-readonly',
      title: 'Tuples and readonly arrays',
      concept: [
        '`number[]` means "some numbers, any amount, in any arrangement". Often that is exactly',
        'right. Sometimes it throws away the thing you cared about.',
        '',
        'A **tuple** fixes the length and gives each position its own type:',
        '',
        '```ts',
        'type Coordinate = [number, number];',
        'type Labelled = [id: string, count: number]; // names are documentation only',
        '',
        'const point: Coordinate = [10, 20];',
        'const [x, y] = point; // both number, and TypeScript knows there are exactly two',
        '```',
        '',
        '```ts-bad',
        'type Coordinate = [number, number];',
        'const bad: Coordinate = [10, 20, 30];',
        '// Source has 3 element(s) but target allows only 2.',
        '```',
        '',
        'A **readonly array** keeps the length open but removes every mutating method:',
        '',
        '```ts-bad',
        'const ports: readonly number[] = [80, 443];',
        'ports.push(8080);',
        '// Property "push" does not exist on type "readonly number[]".',
        '```',
        '',
        '`readonly number[]` and `ReadonlyArray<number>` are the same type written two ways. The',
        'shorthand is more common; the long form is occasionally clearer in a nested position.',
        '',
        'You have already met a readonly tuple, incidentally — that is exactly what `as const`',
        'produced two exercises ago.',
      ].join('\n'),
      brief: ['Give each alias the right shape: a pair of numbers, and a list nobody can push to.'].join('\n'),
      debrief: [
        'The most important thing to know about `readonly` is that **it does not exist at**',
        '**runtime**. It is a compile-time constraint and nothing more:',
        '',
        '```ts',
        'const ports: readonly number[] = [80, 443];',
        '',
        '// The compiler stops you writing ports.push(8080) directly...',
        '// ...but the underlying array is an ordinary mutable one:',
        'const escaped = ports as number[];',
        'escaped.push(8080); // no error, and `ports` now has three elements',
        '```',
        '',
        'If you need a value that genuinely cannot be mutated, you want `Object.freeze` — a',
        'runtime mechanism. `readonly` protects you from your own code, not from the world.',
        '',
        'It is also *shallow*. A `readonly User[]` stops you replacing elements; it does nothing',
        'about mutating the objects inside them. Deep readonly needs a recursive type, which you',
        'will write yourself in module 5.',
        '',
        'The habit worth forming: **take `readonly` in your parameters**. It costs nothing,',
        'accepts strictly more callers than `T[]` does (both mutable and readonly arrays), and',
        'documents that you will not mutate what you were handed.',
        '',
        'That is the end of module 1. Everything from here builds on literal types and inference',
        '— next up is describing values that could be one of several shapes, and convincing the',
        'compiler which one you are holding.',
      ].join('\n'),
      starterCode: ['export type Coordinate = number[];', '', 'export type FrozenPorts = number[];'].join('\n'),
      hiddenChecks: [
        "import type { Coordinate, FrozenPorts } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Coordinate, [number, number]>>,',
        '  Expect<Equal<FrozenPorts, readonly number[]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Coordinate = [number, number];',
        '',
        'export type FrozenPorts = readonly number[];',
      ].join('\n'),
      hints: [
        'A tuple type is written with square brackets around its element types, not after them.',
        'The `readonly` modifier goes in front of an array type.',
        'Write `[number, number]` and `readonly number[]`.',
      ],
    },
  ],
};
