import type { Module } from '../types';

export const narrowing: Module = {
  id: 'narrowing',
  title: 'Objects, Unions & Narrowing',
  blurb:
    'Model a value that could be several things, then convince the compiler which one it is. This is where TypeScript stops being annotation and starts being useful.',
  status: 'ready',
  exercises: [
    {
      id: 'optional-and-readonly',
      title: 'Optional and readonly properties',
      brief: [
        'Two modifiers carry a lot of meaning. `readonly` says a field is set once at',
        'construction and never reassigned. `?` says the field may be absent entirely.',
        '',
        'A user has an `id` nobody should reassign, an `email` that is always present, and a',
        '`nickname` that often is not. Say so.',
      ].join('\n'),
      starterCode: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  nickname: string;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<User, { readonly id: string; email: string; nickname?: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface User {',
        '  readonly id: string;',
        '  email: string;',
        '  nickname?: string;',
        '}',
      ].join('\n'),
      hints: [
        'Both modifiers are single words or symbols added to the property, not to its type.',
        '`readonly` goes before the property name; `?` goes after it.',
        'Write `readonly id: string;` and `nickname?: string;`.',
      ],
    },
    {
      id: 'typeof-narrowing',
      title: 'Narrow a union before you use it',
      brief: [
        'A `string | number` has only the methods *both* members have, which is why',
        '`.toUpperCase()` is rejected — it would blow up on a number at runtime.',
        '',
        'A plain `typeof` check is enough for TypeScript to split the union and let you use',
        'each branch for what it is. Keep the signature exactly as it is; change the body.',
      ].join('\n'),
      starterCode: [
        'export function formatId(id: string | number): string {',
        '  return id.toUpperCase();',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { formatId } from './exercise';",
        'type _cases = [Expect<Equal<typeof formatId, (id: string | number) => string>>];',
      ].join('\n'),
      solution: [
        'export function formatId(id: string | number): string {',
        "  if (typeof id === 'string') {",
        '    return id.toUpperCase();',
        '  }',
        '  return id.toFixed(0);',
        '}',
      ].join('\n'),
      hints: [
        'Inside `if (typeof id === \'string\')`, TypeScript knows `id` is a string and nothing else.',
        'You need a second branch for the number case that still returns a string.',
        "Guard with `if (typeof id === 'string') return id.toUpperCase();` then return something like `id.toFixed(0)`.",
      ],
    },
    {
      id: 'discriminated-union',
      title: 'Give your union a discriminant',
      brief: [
        'This is the single most useful pattern in backend TypeScript, and the reason literal',
        'types matter.',
        '',
        'A bare union of `{ data }` and `{ error }` is nearly useless: TypeScript cannot tell',
        'the members apart, so it refuses to let you touch either field. Add a shared property',
        'whose type is a *different literal* in each member, and the union becomes a tagged',
        'one the compiler can take apart.',
        '',
        'Tag the two members with a `status` field, then use it to narrow inside `unwrap`.',
      ].join('\n'),
      starterCode: [
        'export type ApiResult = { data: string } | { error: string };',
        '',
        'export function unwrap(result: ApiResult): string {',
        '  return result.data;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ApiResult, unwrap } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ApiResult,',
        "      { status: 'ok'; data: string } | { status: 'error'; error: string }",
        '    >',
        '  >,',
        '  Expect<Equal<typeof unwrap, (result: ApiResult) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type ApiResult =',
        "  | { status: 'ok'; data: string }",
        "  | { status: 'error'; error: string };",
        '',
        'export function unwrap(result: ApiResult): string {',
        "  if (result.status === 'ok') {",
        '    return result.data;',
        '  }',
        '  return result.error;',
        '}',
      ].join('\n'),
      hints: [
        "The discriminant must be a literal type, not `string` — `status: 'ok'`, not `status: string`.",
        'Once both members carry `status`, you can read `result.status` even before narrowing, because it exists on every member.',
        "Add `status: 'ok'` to the data member and `status: 'error'` to the error member, then branch on `result.status === 'ok'`.",
      ],
    },
    {
      id: 'type-predicate',
      title: 'Teach the compiler your own check',
      brief: [
        'A *type predicate* return type, `value is Something`, turns an ordinary runtime check',
        'into a narrowing one: callers who pass the check get the narrowed type in the branch',
        'below.',
        '',
        'Worth knowing: since TypeScript 5.5 the compiler infers these on its own for simple',
        'one-liners, so `(v: unknown) => typeof v === \'string\'` already narrows without help.',
        'Inference gives up quickly, though — here it can get as far as `object`, which is not',
        'useful enough to index into.',
        '',
        'Say what you actually mean, so a caller can read properties off the result.',
      ].join('\n'),
      starterCode: [
        'export function isRecord(value: unknown) {',
        "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { isRecord } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof isRecord, (value: unknown) => value is Record<string, unknown>>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function isRecord(value: unknown): value is Record<string, unknown> {',
        "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
        '}',
      ].join('\n'),
      hints: [
        'The change is entirely in the return type annotation; the body is already correct.',
        'The syntax is `parameterName is Type` — it uses the actual name of the parameter.',
        'Write `: value is Record<string, unknown>` as the return type.',
      ],
    },
    {
      id: 'exhaustiveness',
      title: 'Make the compiler catch the case you forgot',
      brief: [
        'Assigning to a `never` variable is the trick that turns "I added a new job type and',
        'forgot to handle it" from a production incident into a compile error.',
        '',
        'In the `default` branch, TypeScript has narrowed `job` down to whatever you have not',
        'handled. If you handled everything, that is `never` and the assignment is fine. If',
        'you missed one, the assignment fails and names the case you forgot.',
        '',
        'Read the error, then handle the missing case.',
      ].join('\n'),
      starterCode: [
        'export type Job =',
        "  | { kind: 'email'; to: string }",
        "  | { kind: 'sms'; number: string }",
        "  | { kind: 'push'; deviceId: string };",
        '',
        'export function describeJob(job: Job): string {',
        '  switch (job.kind) {',
        "    case 'email':",
        "      return 'email to ' + job.to;",
        "    case 'sms':",
        "      return 'sms to ' + job.number;",
        '    default: {',
        '      const impossible: never = job;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { describeJob } from './exercise';",
        "import type { Job } from './exercise';",
        'type _cases = [Expect<Equal<typeof describeJob, (job: Job) => string>>];',
      ].join('\n'),
      solution: [
        'export type Job =',
        "  | { kind: 'email'; to: string }",
        "  | { kind: 'sms'; number: string }",
        "  | { kind: 'push'; deviceId: string };",
        '',
        'export function describeJob(job: Job): string {',
        '  switch (job.kind) {',
        "    case 'email':",
        "      return 'email to ' + job.to;",
        "    case 'sms':",
        "      return 'sms to ' + job.number;",
        "    case 'push':",
        "      return 'push to ' + job.deviceId;",
        '    default: {',
        '      const impossible: never = job;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
      ].join('\n'),
      hints: [
        'The error message names the type that is not assignable to `never`. That is your missing case.',
        'Do not delete the `never` line — it is the thing doing the work.',
        "Add `case 'push': return 'push to ' + job.deviceId;` before the default.",
      ],
    },
    {
      id: 'in-narrowing',
      title: 'Narrow by the shape of the object',
      brief: [
        'Not every union has a tidy discriminant — sometimes you are handed two shapes that',
        'differ only by which properties exist.',
        '',
        'The `in` operator narrows on exactly that. Use it to handle both source kinds.',
      ].join('\n'),
      starterCode: [
        'export interface FileSource {',
        '  path: string;',
        '}',
        '',
        'export interface UrlSource {',
        '  url: string;',
        '}',
        '',
        'export type Source = FileSource | UrlSource;',
        '',
        'export function locate(source: Source): string {',
        '  return source.path;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { Source, locate } from './exercise';",
        'type _cases = [Expect<Equal<typeof locate, (source: Source) => string>>];',
      ].join('\n'),
      solution: [
        'export interface FileSource {',
        '  path: string;',
        '}',
        '',
        'export interface UrlSource {',
        '  url: string;',
        '}',
        '',
        'export type Source = FileSource | UrlSource;',
        '',
        'export function locate(source: Source): string {',
        "  if ('path' in source) {",
        '    return source.path;',
        '  }',
        '  return source.url;',
        '}',
      ].join('\n'),
      hints: [
        'The property name goes on the left as a string literal: `\'path\' in source`.',
        'After that check, the else branch is a `UrlSource` and nothing else.',
        "Guard with `if ('path' in source) return source.path;` then return `source.url`.",
      ],
    },
    {
      id: 'nullable-narrowing',
      title: 'undefined is part of the type',
      brief: [
        'Under `strict`, `string | undefined` genuinely might not be there, and TypeScript',
        'will not let you pretend otherwise.',
        '',
        'The fix is not `!` — that just silences the compiler and moves the crash to runtime.',
        'Handle the missing case for real, and keep the signature as it is.',
      ].join('\n'),
      starterCode: [
        'export function nameLength(name: string | undefined): number {',
        '  return name.length;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { nameLength } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof nameLength, (name: string | undefined) => number>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function nameLength(name: string | undefined): number {',
        '  if (name === undefined) {',
        '    return 0;',
        '  }',
        '  return name.length;',
        '}',
      ].join('\n'),
      hints: [
        'An early return for the undefined case narrows everything below it.',
        'A truthiness check (`if (!name)`) also works here, though it lumps the empty string in with undefined.',
        'Return `0` when `name === undefined`, then `name.length` below.',
      ],
    },
  ],
};
