import type { Module } from '../types';

export const narrowing: Module = {
  id: 'narrowing',
  title: 'Objects, Unions & Narrowing',
  blurb:
    'Model a value that could be several things, then convince the compiler which one it is. This is where TypeScript stops being annotation and starts being useful.',
  status: 'ready',
  exercises: [
    {
      id: 'optional-and-readonly',
      title: 'Optional and readonly properties',
      concept: [
        'Two modifiers on a property carry a lot of meaning, and both are one character or one word.',
        '',
        '`readonly` says the field is set at construction and never reassigned. `?` says the field may be absent entirely.',
        '',
        '```ts',
        'interface User {',
        '  readonly id: string;',
        '  email: string;',
        '  nickname?: string;',
        '}',
        '',
        'declare const user: User;',
        'user.email = \'new@example.com\';',
        '```',
        '',
        '```ts-bad',
        'interface User {',
        '  readonly id: string;',
        '}',
        '',
        'declare const user: User;',
        'user.id = \'u2\';',
        '// Cannot assign to "id" because it is a read-only property.',
        '```',
        '',
        'The `?` does two things at once, which is worth separating in your head. It makes the key *optional* — an object without it still satisfies the type — and it adds `undefined` to the property\'s type:',
        '',
        '```ts',
        'interface User {',
        '  nickname?: string;',
        '}',
        '',
        'declare const user: User;',
        'const n: string | undefined = user.nickname;',
        '```',
        '',
        'That second effect is why the compiler makes you check before using an optional property, and why `noUncheckedIndexedAccess` feels familiar once you have met it.',
      ].join('\n'),
      brief: ['Give `User` an `id` nobody can reassign and a `nickname` that is often absent.'].join('\n'),
      debrief: [
        'It is worth knowing that `nickname?: string` and `nickname: string | undefined` are *not* the same type, even though both let the value be `undefined`.',
        '',
        'The difference is whether the key has to be there at all:',
        '',
        '```ts',
        'interface Optional {',
        '  nickname?: string;',
        '}',
        '',
        'const ok: Optional = {};',
        '```',
        '',
        '```ts-bad',
        'interface Explicit {',
        '  nickname: string | undefined;',
        '}',
        '',
        'const bad: Explicit = {};',
        '// Property "nickname" is missing in type "{}" but required in type "Explicit".',
        '```',
        '',
        '`Explicit` demands the key be present, even if what it holds is `undefined`. That is occasionally what you want — a patch object where "set this to nothing" and "do not touch this" are different instructions — and most of the time it is just annoying.',
        '',
        'There is also a strict flag, `exactOptionalPropertyTypes`, that stops `?` from silently accepting an explicit `undefined`. It is not part of `strict` and is off here. Turning it on in a real codebase is a good idea and a noisy afternoon.',
        '',
        'One more choice you just made without noticing: `interface` rather than `type`. For plain object shapes they are near-identical. The practical differences are that interfaces *merge* when declared twice — the mechanism behind module 6\'s augmentation exercises — and that only a `type` can describe a union. Reach for `interface` on object shapes, `type` on everything else, and do not agonise over it.',
      ].join('\n'),
      starterCode: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  nickname: string;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<User, { readonly id: string; email: string; nickname?: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface User {',
        '  readonly id: string;',
        '  email: string;',
        '  nickname?: string;',
        '}',
      ].join('\n'),
      hints: [
        'Both modifiers are single words or symbols added to the property, not to its type.',
        '`readonly` goes before the property name; `?` goes after it.',
        'Write `readonly id: string;` and `nickname?: string;`.',
      ],
    },
    {
      id: 'typeof-narrowing',
      title: 'Narrow a union before you use it',
      concept: [
        'A union type only offers what *every* member has in common. `string | number` has no `.toUpperCase()`, because half the values it describes are numbers:',
        '',
        '```ts-bad',
        'function format(id: string | number) {',
        '  return id.toUpperCase();',
        '}',
        '// Property "toUpperCase" does not exist on type "string | number".',
        '```',
        '',
        'The compiler is not being awkward. It is refusing to let you write a line that crashes on half its inputs.',
        '',
        '*Narrowing* is how you get out. TypeScript follows the control flow of your code, and inside a branch that can only be reached by strings, the type is `string`:',
        '',
        '```ts',
        'function format(id: string | number): string {',
        '  if (typeof id === \'string\') {',
        '    return id.toUpperCase();',
        '  }',
        '  return id.toFixed(0);',
        '}',
        '```',
        '',
        'Nothing was annotated there. The `typeof` check is ordinary JavaScript you would have written anyway; TypeScript simply reads it.',
        '',
        'This flow analysis is more thorough than people expect. It follows `if`/`else`, early returns, ternaries, `&&` and `||` chains, and `switch`. Write the runtime check naturally and the types usually follow.',
      ].join('\n'),
      brief: ['Keep the signature exactly as it is and fix the body.'].join('\n'),
      debrief: [
        'Two things about `typeof` that catch people out.',
        '',
        'The first is inherited from JavaScript: `typeof null` is `\'object\'`. So an `object` check does not exclude `null`, and TypeScript knows it:',
        '',
        '```ts-bad',
        'function keyCount(value: object | null): number {',
        '  if (typeof value === \'object\') {',
        '    return Object.keys(value).length;',
        '  }',
        '  return 0;',
        '}',
        '// "value" is possibly "null".',
        '```',
        '',
        'For objects, check `value !== null` instead. `typeof` is for primitives; `instanceof` is for classes; `in` is for shapes, which is exercise 6.',
        '',
        'The second is that truthiness narrowing is coarser than it looks. This compiles perfectly and is a bug:',
        '',
        '```ts',
        'function label(count: number | undefined): string {',
        '  if (!count) return \'none\';',
        '  return String(count);',
        '}',
        '',
        'label(0); // "none"',
        '```',
        '',
        '`!count` is true for `undefined`, and also for `0`. The same trap catches the empty string. When you mean "is it missing", say so — `count === undefined` — and save truthiness for when you genuinely want to lump the falsy values together.',
      ].join('\n'),
      starterCode: [
        'export function formatId(id: string | number): string {',
        '  return id.toUpperCase();',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { formatId } from './exercise';",
        'type _cases = [Expect<Equal<typeof formatId, (id: string | number) => string>>];',
      ].join('\n'),
      solution: [
        'export function formatId(id: string | number): string {',
        "  if (typeof id === 'string') {",
        '    return id.toUpperCase();',
        '  }',
        '  return id.toFixed(0);',
        '}',
      ].join('\n'),
      hints: [
        'Inside `if (typeof id === \'string\')`, TypeScript knows `id` is a string and nothing else.',
        'You need a second branch for the number case that still returns a string.',
        "Guard with `if (typeof id === 'string') return id.toUpperCase();` then return something like `id.toFixed(0)`.",
      ],
    },
    {
      id: 'discriminated-union',
      title: 'Give your union a discriminant',
      concept: [
        'This is the single most useful pattern in backend TypeScript, and it is why literal types mattered in module 1.',
        '',
        'A bare union of two object types is nearly useless. TypeScript cannot tell which member you are holding, so it refuses to let you touch a property that only exists on one of them:',
        '',
        '```ts-bad',
        'type Result = { data: string } | { error: string };',
        '',
        'declare const r: Result;',
        'r.data;',
        '// Property "data" does not exist on type "Result".',
        '```',
        '',
        'Add a property that exists on *every* member, whose type is a *different literal* in each, and the union becomes a tagged one the compiler can take apart:',
        '',
        '```ts',
        'type Result =',
        '  | { status: \'ok\'; data: string }',
        '  | { status: \'error\'; error: string };',
        '',
        'function unwrap(r: Result): string {',
        '  if (r.status === \'ok\') {',
        '    return r.data;',
        '  }',
        '  return r.error;',
        '}',
        '```',
        '',
        'Two things make that work. `status` is on both members, so you can read it before narrowing anything. And its type is a *specific literal* in each member, so comparing it against `\'ok\'` eliminates the other member entirely.',
        '',
        'That is the whole trick. It is not a special language feature so much as literal types and narrowing pointed at each other.',
      ].join('\n'),
      brief: ['Tag the two members with a `status` field, then use it to narrow inside `unwrap`.'].join('\n'),
      debrief: [
        'The discriminant has to be a *literal* type. Widen it to `string` and the whole thing quietly stops working:',
        '',
        '```ts-bad',
        'type Bad =',
        '  | { status: string; data: string }',
        '  | { status: string; error: string };',
        '',
        'declare const b: Bad;',
        'if (b.status === \'ok\') {',
        '  b.data;',
        '}',
        '// Property "data" does not exist on type "Bad".',
        '```',
        '',
        'Comparing against `\'ok\'` eliminates nothing, because `string` is compatible with both members. This is a genuinely common bug, and the error message points at `data` rather than at the real culprit, which is `status`.',
        '',
        'Once you start seeing this shape you will find it everywhere:',
        '',
        '```ts',
        'type RequestState<T> =',
        '  | { phase: \'idle\' }',
        '  | { phase: \'loading\' }',
        '  | { phase: \'done\'; value: T }',
        '  | { phase: \'failed\'; error: Error };',
        '```',
        '',
        'Four states, and it is now impossible to read `value` without proving the request finished — no more `data` and `isLoading` and `error` as three independent fields with eight combinations, five of which are nonsense.',
        '',
        'The same shape models reducer actions, message queues, parser results and state machines. Module 7 builds the `Result` type on it, and the next exercise makes the compiler tell you when you forget a case.',
      ].join('\n'),
      starterCode: [
        'export type ApiResult = { data: string } | { error: string };',
        '',
        'export function unwrap(result: ApiResult): string {',
        '  return result.data;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ApiResult, unwrap } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ApiResult,',
        "      { status: 'ok'; data: string } | { status: 'error'; error: string }",
        '    >',
        '  >,',
        '  Expect<Equal<typeof unwrap, (result: ApiResult) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type ApiResult =',
        "  | { status: 'ok'; data: string }",
        "  | { status: 'error'; error: string };",
        '',
        'export function unwrap(result: ApiResult): string {',
        "  if (result.status === 'ok') {",
        '    return result.data;',
        '  }',
        '  return result.error;',
        '}',
      ].join('\n'),
      hints: [
        "The discriminant must be a literal type, not `string` — `status: 'ok'`, not `status: string`.",
        'Once both members carry `status`, you can read `result.status` even before narrowing, because it exists on every member.',
        "Add `status: 'ok'` to the data member and `status: 'error'` to the error member, then branch on `result.status === 'ok'`.",
      ],
    },
    {
      id: 'type-predicate',
      title: 'Teach the compiler your own check',
      concept: [
        'A function returning `boolean` tells the compiler nothing. You checked something, the check passed, and the value is still `unknown` on the other side.',
        '',
        'Since TypeScript 5.5 the compiler infers a predicate for simple one-liners, so this already narrows without help:',
        '',
        '```ts',
        'function isString(v: unknown) {',
        '  return typeof v === \'string\';',
        '}',
        '',
        'declare const x: unknown;',
        'if (isString(x)) {',
        '  x.toUpperCase();',
        '}',
        '```',
        '',
        'Inference gives up quickly, though. Here it can only get as far as `object`, which is not useful enough to read a property from:',
        '',
        '```ts-bad',
        'function isRecord(v: unknown) {',
        '  return typeof v === \'object\' && v !== null && !Array.isArray(v);',
        '}',
        '',
        'declare const x: unknown;',
        'if (isRecord(x)) {',
        '  x.someKey;',
        '}',
        '```',
        '',
        'A *type predicate* return type — `v is Something` — says what you actually mean. The syntax uses the real name of the parameter:',
        '',
        '```ts',
        'function isRecord(v: unknown): v is Record<string, unknown> {',
        '  return typeof v === \'object\' && v !== null && !Array.isArray(v);',
        '}',
        '',
        'declare const x: unknown;',
        'if (isRecord(x)) {',
        '  x.someKey;',
        '}',
        '```',
      ].join('\n'),
      brief: ['Say what the check actually proves, so a caller can read properties off the result.'].join('\n'),
      debrief: [
        'A predicate is an assertion, not a proof. TypeScript takes your word for it and never checks the body against the claim:',
        '',
        '```ts',
        'function isUser(v: unknown): v is { id: string } {',
        '  return true;',
        '}',
        '```',
        '',
        'That compiles. It is a lie, and every caller downstream now believes it. A wrong predicate is worse than no predicate, because it launders an `unknown` into a confident wrong type with no cast in sight for a reviewer to notice.',
        '',
        'So write them narrowly, keep the body obviously correct, and prefer generating them over hand-writing them — which is exactly what a validation library does for you. `zod`\'s `safeParse` is a type predicate with the body derived from a schema, and that is module 7.',
        '',
        'There is a second form worth recognising when you meet it:',
        '',
        '```ts',
        'function assertIsString(v: unknown): asserts v is string {',
        '  if (typeof v !== \'string\') throw new Error(\'not a string\');',
        '}',
        '',
        'declare const x: unknown;',
        'assertIsString(x);',
        'x.toUpperCase();',
        '```',
        '',
        'An *assertion function* narrows everything after the call rather than inside a branch. Note there is no `if` around it — that is the point. The same caveat applies twice over: the compiler trusts the signature completely.',
      ].join('\n'),
      starterCode: [
        'export function isRecord(value: unknown) {',
        "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { isRecord } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof isRecord, (value: unknown) => value is Record<string, unknown>>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function isRecord(value: unknown): value is Record<string, unknown> {',
        "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
        '}',
      ].join('\n'),
      hints: [
        'The change is entirely in the return type annotation; the body is already correct.',
        'The syntax is `parameterName is Type` — it uses the actual name of the parameter.',
        'Write `: value is Record<string, unknown>` as the return type.',
      ],
    },
    {
      id: 'exhaustiveness',
      title: 'Make the compiler catch the case you forgot',
      concept: [
        '`never` is the type with no values. Nothing at all is assignable to it — and that uselessness turns out to be a tool.',
        '',
        'Put a `never` variable in the `default` branch of a `switch` over a discriminated union. If you handled every case, TypeScript has narrowed the value down to nothing, the assignment is fine, and the branch is unreachable:',
        '',
        '```ts',
        'type Shape =',
        '  | { kind: \'circle\'; r: number }',
        '  | { kind: \'square\'; size: number };',
        '',
        'function area(s: Shape): number {',
        '  switch (s.kind) {',
        '    case \'circle\':',
        '      return Math.PI * s.r ** 2;',
        '    case \'square\':',
        '      return s.size ** 2;',
        '    default: {',
        '      const impossible: never = s;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
        '```',
        '',
        'Now add a third member and forget to handle it. What reaches `default` is no longer `never`, and the assignment fails:',
        '',
        '```ts-bad',
        'type Shape =',
        '  | { kind: \'circle\'; r: number }',
        '  | { kind: \'square\'; size: number }',
        '  | { kind: \'triangle\'; base: number; height: number };',
        '',
        'function area(s: Shape): number {',
        '  switch (s.kind) {',
        '    case \'circle\':',
        '      return Math.PI * s.r ** 2;',
        '    case \'square\':',
        '      return s.size ** 2;',
        '    default: {',
        '      const impossible: never = s;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
        '// Type "{ kind: "triangle"; ... }" is not assignable to type "never".',
        '```',
        '',
        'The error names the case you forgot. That is the whole point: adding a variant becomes a compile error at every site that has to care, instead of a runtime surprise in whichever one you missed.',
      ].join('\n'),
      brief: ['Read the error, then handle the missing case. Do not delete the `never` line — it is the thing doing the work.'].join('\n'),
      debrief: [
        'In a real codebase you would extract that into a helper rather than repeat the two lines:',
        '',
        '```ts',
        'function assertNever(value: never): never {',
        '  throw new Error(`Unhandled case: ${JSON.stringify(value)}`);',
        '}',
        '',
        'type Job = { kind: \'email\' } | { kind: \'sms\' };',
        '',
        'function describe(job: Job): string {',
        '  switch (job.kind) {',
        '    case \'email\':',
        '      return \'email\';',
        '    case \'sms\':',
        '      return \'sms\';',
        '    default:',
        '      return assertNever(job);',
        '  }',
        '}',
        '```',
        '',
        'Same compile-time check, plus a runtime error that is actually useful when malformed data arrives from somewhere the types do not govern.',
        '',
        'Worth understanding *why* `never` behaves this way. It is the empty set: the type that describes no values. Narrowing removes members from a union, and when you remove them all, what is left is `never`. So "this branch is unreachable" and "this value has type `never`" are the same statement.',
        '',
        'It shows up in a few other places once you know the shape of it. A function that always throws returns `never`, not `void`. Filtering a union down to nothing gives `never` — which is exactly the mechanism behind `Exclude`, in module 5. And `never` vanishes from unions entirely, since `string | never` is just `string`.',
      ].join('\n'),
      starterCode: [
        'export type Job =',
        "  | { kind: 'email'; to: string }",
        "  | { kind: 'sms'; number: string }",
        "  | { kind: 'push'; deviceId: string };",
        '',
        'export function describeJob(job: Job): string {',
        '  switch (job.kind) {',
        "    case 'email':",
        "      return 'email to ' + job.to;",
        "    case 'sms':",
        "      return 'sms to ' + job.number;",
        '    default: {',
        '      const impossible: never = job;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { describeJob } from './exercise';",
        "import type { Job } from './exercise';",
        'type _cases = [Expect<Equal<typeof describeJob, (job: Job) => string>>];',
      ].join('\n'),
      solution: [
        'export type Job =',
        "  | { kind: 'email'; to: string }",
        "  | { kind: 'sms'; number: string }",
        "  | { kind: 'push'; deviceId: string };",
        '',
        'export function describeJob(job: Job): string {',
        '  switch (job.kind) {',
        "    case 'email':",
        "      return 'email to ' + job.to;",
        "    case 'sms':",
        "      return 'sms to ' + job.number;",
        "    case 'push':",
        "      return 'push to ' + job.deviceId;",
        '    default: {',
        '      const impossible: never = job;',
        '      return impossible;',
        '    }',
        '  }',
        '}',
      ].join('\n'),
      hints: [
        'The error message names the type that is not assignable to `never`. That is your missing case.',
        'Do not delete the `never` line — it is the thing doing the work.',
        "Add `case 'push': return 'push to ' + job.deviceId;` before the default.",
      ],
    },
    {
      id: 'in-narrowing',
      title: 'Narrow by the shape of the object',
      concept: [
        'Not every union has a tidy discriminant. Sometimes you are handed two shapes from somewhere you do not control, and they differ only by which properties exist.',
        '',
        'The `in` operator narrows on exactly that — it is ordinary JavaScript, and TypeScript reads it as a type check:',
        '',
        '```ts',
        'interface FileSource {',
        '  path: string;',
        '}',
        '',
        'interface UrlSource {',
        '  url: string;',
        '}',
        '',
        'function locate(s: FileSource | UrlSource): string {',
        '  if (\'path\' in s) {',
        '    return s.path;',
        '  }',
        '  return s.url;',
        '}',
        '```',
        '',
        'The property name goes on the left as a string literal. In the true branch the value is a `FileSource`; in the false branch it is a `UrlSource` and nothing else.',
        '',
        'That gives you three narrowing tools, each for a different job:',
        '',
        '- `typeof` — primitives',
        '- `instanceof` — classes and anything with a prototype',
        '- `in` — plain object shapes',
      ].join('\n'),
      brief: ['Handle both source kinds without changing the signature.'].join('\n'),
      debrief: [
        '`in` asks whether the key *exists*, not whether it holds anything useful. Those come apart when a property is optional:',
        '',
        '```ts',
        'interface Config {',
        '  retries?: number;',
        '}',
        '',
        'const config: Config = { retries: undefined };',
        'const hasKey = \'retries\' in config;',
        '// true — the key is there, holding undefined',
        '```',
        '',
        'If what you actually mean is "was a retry count provided", check the value: `config.retries !== undefined`. Reach for `in` when the shapes differ, not when the values might be missing.',
        '',
        'The bigger point is when to use it at all. `in` is a fallback. When you own both types, a discriminant is better in every way — it reads more clearly, it survives a property being renamed, and it enables the exhaustiveness check from the last exercise, which `in` cannot do. Two shapes distinguished by `\'path\' in s` will happily compile after you add a third, and nothing will tell you.',
        '',
        'So: discriminant when you control the type, `in` when you are describing someone else\'s.',
      ].join('\n'),
      starterCode: [
        'export interface FileSource {',
        '  path: string;',
        '}',
        '',
        'export interface UrlSource {',
        '  url: string;',
        '}',
        '',
        'export type Source = FileSource | UrlSource;',
        '',
        'export function locate(source: Source): string {',
        '  return source.path;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { Source, locate } from './exercise';",
        'type _cases = [Expect<Equal<typeof locate, (source: Source) => string>>];',
      ].join('\n'),
      solution: [
        'export interface FileSource {',
        '  path: string;',
        '}',
        '',
        'export interface UrlSource {',
        '  url: string;',
        '}',
        '',
        'export type Source = FileSource | UrlSource;',
        '',
        'export function locate(source: Source): string {',
        "  if ('path' in source) {",
        '    return source.path;',
        '  }',
        '  return source.url;',
        '}',
      ].join('\n'),
      hints: [
        'The property name goes on the left as a string literal: `\'path\' in source`.',
        'After that check, the else branch is a `UrlSource` and nothing else.',
        "Guard with `if ('path' in source) return source.path;` then return `source.url`.",
      ],
    },
    {
      id: 'nullable-narrowing',
      title: 'undefined is part of the type',
      concept: [
        'Under `strict`, `null` and `undefined` are ordinary members of a type rather than values that lurk inside every type. `string | undefined` genuinely might not be there, and the compiler will not pretend otherwise:',
        '',
        '```ts-bad',
        'function len(name: string | undefined): number {',
        '  return name.length;',
        '}',
        '// "name" is possibly "undefined".',
        '```',
        '',
        'This flag — `strictNullChecks` — is the reason TypeScript is worth using at all. It converts an entire category of runtime crash into a compile error.',
        '',
        'Handle the missing case and the rest of the function is narrowed for free:',
        '',
        '```ts',
        'function len(name: string | undefined): number {',
        '  if (name === undefined) {',
        '    return 0;',
        '  }',
        '  return name.length;',
        '}',
        '```',
        '',
        'Two pieces of syntax make the compact version pleasant. Optional chaining `?.` short-circuits to `undefined` instead of throwing, and `??` supplies a fallback when the left side is `null` or `undefined`:',
        '',
        '```ts',
        'function len(name: string | undefined): number {',
        '  return name?.length ?? 0;',
        '}',
        '```',
        '',
        'Both are real JavaScript, not TypeScript inventions — the types simply follow them correctly.',
      ].join('\n'),
      brief: [
        'Handle the missing case for real, keeping the signature as it is.',
        '',
        'The fix is not `!`.',
      ].join('\n'),
      debrief: [
        'The tempting shortcut here is the non-null assertion:',
        '',
        '```ts',
        'function len(name: string | undefined): number {',
        '  return name!.length;',
        '}',
        '```',
        '',
        'That compiles. It does nothing at runtime. It is a bare instruction to the compiler to stop objecting, and if `name` really is undefined you get the exact crash `strictNullChecks` existed to prevent — now with a note in the source saying someone considered this and waved it through.',
        '',
        'There are legitimate uses, mostly where you know something the compiler structurally cannot. They are rarer than the number of `!` in most codebases suggests. If you find yourself writing one, try an early return first.',
        '',
        'The other thing to internalise is `??` versus `||`, because the difference is a real bug:',
        '',
        '```ts',
        'const configuredPort = 0;',
        '',
        'const a = configuredPort || 3000;',
        '// 3000 — the 0 was falsy, so it got thrown away',
        '',
        'const b = configuredPort ?? 3000;',
        '// 0 — the value was present, so it was kept',
        '```',
        '',
        '`||` falls back on any falsy value, which includes `0` and `\'\'` — both perfectly valid configuration. `??` falls back only on `null` and `undefined`. For defaults, `??` is almost always the one you want, and `0` and the empty string are exactly the values that make the difference show up in production rather than in review.',
      ].join('\n'),
      starterCode: [
        'export function nameLength(name: string | undefined): number {',
        '  return name.length;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { nameLength } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof nameLength, (name: string | undefined) => number>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function nameLength(name: string | undefined): number {',
        '  if (name === undefined) {',
        '    return 0;',
        '  }',
        '  return name.length;',
        '}',
      ].join('\n'),
      hints: [
        'An early return for the undefined case narrows everything below it.',
        'A truthiness check (`if (!name)`) also works here, though it lumps the empty string in with undefined.',
        'Return `0` when `name === undefined`, then `name.length` below.',
      ],
    },
  ],
};
