import type { Module } from '../types';

export const generics: Module = {
  id: 'generics',
  title: 'Generics & Constraints',
  blurb:
    'Write one function that keeps its caller’s types instead of flattening them to `unknown`. The wall most JavaScript devs hit, taken slowly.',
  status: 'ready',
  exercises: [
    {
      id: 'first-generic',
      title: 'A type parameter is just an argument',
      brief: [
        'This function works on anything, and destroys the type on the way through: hand it a',
        '`string` and you get back `unknown[]`.',
        '',
        'A type parameter fixes that. `<T>` declares a placeholder that gets filled in *at the',
        'call site* — call it with a string and `T` becomes `string`, so the return is',
        '`string[]`. It is an argument like any other; it just holds a type instead of a value.',
      ].join('\n'),
      starterCode: [
        'export function wrapInArray(value: unknown): unknown[] {',
        '  return [value];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { wrapInArray } from './exercise';",
        'type _cases = [Expect<Equal<typeof wrapInArray, <T>(value: T) => T[]>>];',
      ].join('\n'),
      solution: [
        'export function wrapInArray<T>(value: T): T[] {',
        '  return [value];',
        '}',
      ].join('\n'),
      hints: [
        'The type parameter list goes after the function name, in angle brackets, before the value parameters.',
        'Then use that same name where `unknown` currently appears.',
        'Write `export function wrapInArray<T>(value: T): T[]`.',
      ],
    },
    {
      id: 'constraints',
      title: 'Constrain the parameter to what you actually use',
      brief: [
        'An unconstrained `T` could be anything at all, so TypeScript refuses `item.length` —',
        'and it is right to, because someone could call this with numbers.',
        '',
        '`T extends { length: number }` says: I do not care what you pass, as long as it has a',
        '`length`. That is enough for the body to compile, and callers still get their exact',
        'type back rather than a widened one.',
        '',
        'This is the whole point of constraints: the *minimum* the function needs, not the',
        'most convenient concrete type.',
      ].join('\n'),
      starterCode: [
        'export function totalLength<T>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { totalLength } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<typeof totalLength, <T extends { length: number }>(items: T[]) => number>',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export function totalLength<T extends { length: number }>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
      ].join('\n'),
      hints: [
        '`extends` inside a type parameter list does not mean inheritance — it means "assignable to".',
        'Describe the shape inline, as an object type with the one property you need.',
        'Write `<T extends { length: number }>`.',
      ],
    },
    {
      id: 'keyof',
      title: 'keyof and indexed access',
      brief: [
        'A getter that takes `key: string` and returns `unknown` is barely better than plain',
        'JavaScript: it accepts keys that do not exist and tells you nothing about what comes',
        'back.',
        '',
        'Two features fix this together. `keyof T` is the union of `T`’s property names, so a',
        'second type parameter constrained by it only accepts real keys. And `T[K]` — an',
        '*indexed access type* — is the type of that specific property.',
        '',
        'Get both, and `getProp(user, \'email\')` returns `string` while `getProp(user, \'nope\')`',
        'is a compile error.',
      ].join('\n'),
      starterCode: [
        'export function getProp(obj: object, key: string): unknown {',
        '  return (obj as Record<string, unknown>)[key];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { getProp } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof getProp, <T, K extends keyof T>(obj: T, key: K) => T[K]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {',
        '  return obj[key];',
        '}',
      ].join('\n'),
      hints: [
        'You need two type parameters: one for the object, one for the key.',
        'The second is constrained by the first: `K extends keyof T`.',
        'Write `<T, K extends keyof T>(obj: T, key: K): T[K]`, and the cast in the body becomes unnecessary.',
      ],
    },
    {
      id: 'pluck',
      title: 'Carry the types through a transform',
      brief: [
        'Same two tools as the last exercise, now over a list. `pluck(users, \'email\')` should',
        'come back as `string[]`, with no cast and no `unknown` anywhere.',
        '',
        'If you can write this one without looking at the previous solution, generics have',
        'started to click.',
      ].join('\n'),
      starterCode: [
        'export function pluck(items: unknown[], key: string): unknown[] {',
        '  return items.map((item) => (item as Record<string, unknown>)[key]);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { pluck } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof pluck, <T, K extends keyof T>(items: T[], key: K) => T[K][]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {',
        '  return items.map((item) => item[key]);',
        '}',
      ].join('\n'),
      hints: [
        'The element type is `T`, so the parameter is `T[]` — not `T` itself.',
        'The return is an array of the property type: `T[K][]`.',
        'Write `<T, K extends keyof T>(items: T[], key: K): T[K][]`.',
      ],
    },
    {
      id: 'default-type-params',
      title: 'A type parameter can have a default',
      brief: [
        '`Result<T>` hardcodes `Error` as the failure type. Most of the time that is what you',
        'want — but not always, and today the only way to change it is to write a second type.',
        '',
        'Type parameters take defaults exactly like value parameters do: `<T, E = Error>`. Then',
        '`Result<User>` keeps working unchanged, and `Result<User, ValidationIssue>` becomes',
        'possible.',
        '',
        'This `Result` type is worth remembering, by the way — it is how you model a fallible',
        'operation without exceptions, and it narrows beautifully because `ok` is a discriminant.',
      ].join('\n'),
      starterCode: [
        'export type Result<T> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: Error };',
      ].join('\n'),
      hiddenChecks: [
        "import type { Result } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<Result<number>, { ok: true; value: number } | { ok: false; error: Error }>',
        '  >,',
        '  Expect<',
        '    Equal<',
        '      Result<string, string>,',
        '      { ok: true; value: string } | { ok: false; error: string }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
      ].join('\n'),
      hints: [
        'Add a second type parameter, and give it a default with `=`.',
        'Then use that parameter instead of the hardcoded `Error`.',
        'Write `export type Result<T, E = Error>` and change `error: Error` to `error: E`.',
      ],
    },
  ],
};
