import type { Module } from '../types';

export const generics: Module = {
  id: 'generics',
  title: 'Generics & Constraints',
  blurb:
    'Write one function that keeps its caller’s types instead of flattening them to `unknown`. The wall most JavaScript devs hit, taken slowly.',
  status: 'ready',
  exercises: [
    {
      id: 'first-generic',
      title: 'A type parameter is just an argument',
      concept: [
        'A generic is a function that takes a *type* as an argument.',
        '',
        'Without one, a function that works on anything has to flatten what it is given. Hand this a string and the string is gone:',
        '',
        '```ts-bad',
        'function wrapLoose(value: unknown): unknown[] {',
        '  return [value];',
        '}',
        '',
        'const wrapped = wrapLoose(\'hello\');',
        'wrapped[0].toUpperCase();',
        '```',
        '',
        '`<T>` declares a placeholder that gets filled in *at the call site*. Call it with a string and `T` becomes `string`, so the return is `string[]`:',
        '',
        '```ts',
        'function wrapInArray<T>(value: T): T[] {',
        '  return [value];',
        '}',
        '',
        'const a = wrapInArray(\'hello\');',
        'const b = wrapInArray(42);',
        '',
        'a[0]?.toUpperCase();',
        'b[0]?.toFixed(2);',
        '```',
        '',
        'Notice there is no `wrapInArray<string>(\'hello\')` anywhere. TypeScript works `T` out from the argument you passed, which is why generics are far less intrusive to *use* than to read.',
        '',
        'The mental model that helps most: a generic function is a function from types to types, running at compile time, alongside the ordinary function from values to values. `T` is its parameter.',
      ].join('\n'),
      brief: ['Keep the caller\'s type instead of flattening it to `unknown`.'].join('\n'),
      debrief: [
        'It is worth being clear about how this differs from `any`, because both make the error go away.',
        '',
        '`any` switches the compiler off. A generic keeps every check and adds a *relationship*: this function\'s output type is tied to its input type. Nothing is loosened — you have said something more precise than you could before, not less.',
        '',
        'That points at a rule of thumb for when a generic is not pulling its weight: **a type parameter should appear at least twice.** Once to capture something, and at least once to use it. If it appears only once, it is not relating anything:',
        '',
        '```ts',
        'function logIt<T>(value: T): void {',
        '  console.log(value);',
        '}',
        '```',
        '',
        '`T` is bound and then never used again, so this is `(value: unknown) => void` with extra ceremony. Worse, it reads as though it does something clever, so the next person leaves it alone.',
        '',
        'The same test catches the more common version of this mistake, where a type parameter is used purely as a disguised cast:',
        '',
        '```ts',
        'function parseAs<T>(json: string): T {',
        '  return JSON.parse(json) as T;',
        '}',
        '',
        'const user = parseAs<{ id: string }>(\'{}\');',
        '```',
        '',
        '`T` appears once, in the return position, and nothing checks it — the caller names a type and the function asserts it. That compiles, and `user.id` is `string` for a value that is an empty object. It is `as` wearing a generic\'s clothes.',
      ].join('\n'),
      starterCode: [
        'export function wrapInArray(value: unknown): unknown[] {',
        '  return [value];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { wrapInArray } from './exercise';",
        'type _cases = [Expect<Equal<typeof wrapInArray, <T>(value: T) => T[]>>];',
      ].join('\n'),
      solution: [
        'export function wrapInArray<T>(value: T): T[] {',
        '  return [value];',
        '}',
      ].join('\n'),
      hints: [
        'The type parameter list goes after the function name, in angle brackets, before the value parameters.',
        'Then use that same name where `unknown` currently appears.',
        'Write `export function wrapInArray<T>(value: T): T[]`.',
      ],
    },
    {
      id: 'constraints',
      title: 'Constrain the parameter to what you actually use',
      concept: [
        'An unconstrained `T` could be anything at all, so TypeScript will not let you assume anything about it:',
        '',
        '```ts-bad',
        'function totalLength<T>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
        '```',
        '',
        'It is right to object. Somebody could call that with numbers.',
        '',
        'A constraint says what the function actually needs — no more:',
        '',
        '```ts',
        'function totalLength<T extends { length: number }>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
        '',
        'totalLength([\'a\', \'bb\']);',
        'totalLength([[1], [2, 3]]);',
        '```',
        '',
        'Strings have a `length`, and so do arrays, so both calls work without either being mentioned in the signature.',
        '',
        'One piece of vocabulary that trips people up: `extends` here does **not** mean inheritance. It means "is assignable to". `T extends { length: number }` reads as "whatever T is, it must at least have a numeric length". Structural typing does the rest — nothing has to declare that it implements anything.',
        '',
        'The discipline worth practising is to constrain to the *minimum* the body requires. Every extra requirement is a caller you have turned away for no reason.',
      ].join('\n'),
      brief: ['Constrain `T` to what the body actually uses.'].join('\n'),
      debrief: [
        'A fair question at this point: why not drop the generic entirely and write `items: { length: number }[]`?',
        '',
        'For `totalLength`, you could. It returns a `number` either way, so nothing is lost.',
        '',
        'The difference shows up the moment the function returns something derived from its input:',
        '',
        '```ts',
        'function firstItem<T extends { id: string }>(items: T[]): T | undefined {',
        '  return items[0];',
        '}',
        '',
        'const users = [{ id: \'u1\', email: \'ada@example.com\' }];',
        'const found = firstItem(users);',
        '',
        'found?.email;',
        '```',
        '',
        '`T` was inferred as the full `{ id: string; email: string }`, so `email` survives the round trip. Write the parameter as `{ id: string }[]` instead and the return type is `{ id: string } | undefined` — the compiler has forgotten about `email`, and the caller has to cast it back.',
        '',
        'So the rule is: **constrain when you need to use a property *and* hand the caller\'s own type back.** If the return type does not mention `T`, a plain parameter type is simpler and you should prefer it.',
        '',
        'That is the same "must appear at least twice" test from the last exercise, seen from another angle.',
      ].join('\n'),
      starterCode: [
        'export function totalLength<T>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { totalLength } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<typeof totalLength, <T extends { length: number }>(items: T[]) => number>',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export function totalLength<T extends { length: number }>(items: T[]): number {',
        '  return items.reduce((sum, item) => sum + item.length, 0);',
        '}',
      ].join('\n'),
      hints: [
        '`extends` inside a type parameter list does not mean inheritance — it means "assignable to".',
        'Describe the shape inline, as an object type with the one property you need.',
        'Write `<T extends { length: number }>`.',
      ],
    },
    {
      id: 'keyof',
      title: 'keyof and indexed access',
      concept: [
        'Two operators, then one pattern that combines them.',
        '',
        '`keyof T` is the union of a type\'s property names. `T[\'prop\']` — an *indexed access type* — is the type of that property. Both work on types, not values:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '  loginCount: number;',
        '}',
        '',
        'type UserKey = keyof User;',
        'type EmailType = User[\'email\'];',
        '',
        'const k: UserKey = \'email\';',
        'const e: EmailType = \'ada@example.com\';',
        '```',
        '',
        'Now the pattern. A getter needs *two* type parameters: one for the object, one for the specific key, with the second constrained by the first:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '  loginCount: number;',
        '}',
        '',
        'function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {',
        '  return obj[key];',
        '}',
        '',
        'declare const user: User;',
        'const email = getProp(user, \'email\');',
        'const count = getProp(user, \'loginCount\');',
        '```',
        '',
        '`email` is `string` and `count` is `number` — each call gets the type of the property it actually asked for. And a key that does not exist is a compile error rather than an `undefined` at runtime:',
        '',
        '```ts-bad',
        'interface User {',
        '  id: string;',
        '}',
        '',
        'function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {',
        '  return obj[key];',
        '}',
        '',
        'declare const user: User;',
        'getProp(user, \'emial\');',
        '```',
      ].join('\n'),
      brief: ['Make the getter accept only real keys, and return the type of the property asked for.'].join('\n'),
      debrief: [
        'The second type parameter is the part that is easy to skip, so it is worth seeing what you lose without it.',
        '',
        'This looks equivalent and is much weaker:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  loginCount: number;',
        '}',
        '',
        'function loose<T>(obj: T, key: keyof T): T[keyof T] {',
        '  return obj[key];',
        '}',
        '',
        'declare const user: User;',
        'const value = loose(user, \'id\');',
        '```',
        '',
        '`value` is `string | number`, not `string`. `keyof T` is the union of *all* the keys, so `T[keyof T]` is the union of *all* the property types — the function has correctly told you it returns one of them, without saying which.',
        '',
        'Introducing `K` is what captures the specific key the caller passed. `K` is inferred as the literal type `\'id\'`, so `T[K]` resolves to exactly `string`. That is the entire reason for the second parameter, and the same trick turns up constantly: a type parameter that exists purely to remember which member of a union you were given.',
        '',
        'This is also your first real *type-level program*. `keyof` and `T[K]` are operators that compute types from other types, and everything in modules 4 and 5 is built from that idea — mapped types walk `keyof T`, and conditional types branch on it.',
      ].join('\n'),
      starterCode: [
        'export function getProp(obj: object, key: string): unknown {',
        '  return (obj as Record<string, unknown>)[key];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { getProp } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof getProp, <T, K extends keyof T>(obj: T, key: K) => T[K]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {',
        '  return obj[key];',
        '}',
      ].join('\n'),
      hints: [
        'You need two type parameters: one for the object, one for the key.',
        'The second is constrained by the first: `K extends keyof T`.',
        'Write `<T, K extends keyof T>(obj: T, key: K): T[K]`, and the cast in the body becomes unnecessary.',
      ],
    },
    {
      id: 'pluck',
      title: 'Carry the types through a transform',
      concept: [
        'Same two tools as the last exercise, now applied across a list.',
        '',
        '`pluck(users, \'email\')` should come back as `string[]`, with no cast and no `unknown` anywhere:',
        '',
        '```ts',
        'function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {',
        '  return items.map((item) => item[key]);',
        '}',
        '',
        'const users = [',
        '  { id: \'u1\', email: \'ada@example.com\', loginCount: 3 },',
        '  { id: \'u2\', email: \'grace@example.com\', loginCount: 7 },',
        '];',
        '',
        'const emails = pluck(users, \'email\');',
        'const counts = pluck(users, \'loginCount\');',
        '',
        'emails[0]?.toUpperCase();',
        'counts[0]?.toFixed(0);',
        '```',
        '',
        'Two things to get right. The element type is `T`, so the parameter is `T[]` rather than `T` — the type parameter names what is *in* the array, not the array. And the return is an array of the property type, `T[K][]`.',
        '',
        'If you can write this one without looking back at the previous solution, generics have started to click.',
      ].join('\n'),
      brief: ['Carry the element type and the key type all the way through to the return.'].join('\n'),
      debrief: [
        'Worth noticing where the inference actually came from: `T` was inferred from `items`, and `K` from `key`. Every type parameter needs an argument it can be read off.',
        '',
        'When one has nothing to infer from, TypeScript falls back to the constraint, or to `unknown`:',
        '',
        '```ts',
        'function makeEmpty<T>(): T[] {',
        '  return [];',
        '}',
        '',
        'const explicit = makeEmpty<string>();',
        'const inferred = makeEmpty();',
        '',
        'explicit.push(\'ok\');',
        'inferred.push(\'anything at all\');',
        '```',
        '',
        '`inferred` is `unknown[]`, which is why that second `push` is allowed and why the array is useless afterwards. Nothing in the call gave `T` anything to bind to, so you have to supply it by hand. This is the most common reason a generic "does not work" — not a mistake in the signature, but a type parameter with no inference site.',
        '',
        'In real code you would often skip `pluck` entirely and write `users.map((u) => u.email)`, which is shorter and needs no generics at all — `map` is already generic, and its callback is contextually typed. That is worth saying plainly: the goal is not to write more generics. It is to recognise the shape when a function genuinely has to be reusable, and to be comfortable reading it in the library code you depend on, which is full of exactly this.',
      ].join('\n'),
      starterCode: [
        'export function pluck(items: unknown[], key: string): unknown[] {',
        '  return items.map((item) => (item as Record<string, unknown>)[key]);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { pluck } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof pluck, <T, K extends keyof T>(items: T[], key: K) => T[K][]>>,',
        '];',
      ].join('\n'),
      solution: [
        'export function pluck<T, K extends keyof T>(items: T[], key: K): T[K][] {',
        '  return items.map((item) => item[key]);',
        '}',
      ].join('\n'),
      hints: [
        'The element type is `T`, so the parameter is `T[]` — not `T` itself.',
        'The return is an array of the property type: `T[K][]`.',
        'Write `<T, K extends keyof T>(items: T[], key: K): T[K][]`.',
      ],
    },
    {
      id: 'default-type-params',
      title: 'A type parameter can have a default',
      concept: [
        'Type parameters take defaults, exactly like value parameters do:',
        '',
        '```ts',
        'type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'type NumberResult = Result<number>;',
        'type ParseResult = Result<number, string>;',
        '',
        'const a: NumberResult = { ok: false, error: new Error(\'boom\') };',
        'const b: ParseResult = { ok: false, error: \'not a number\' };',
        '```',
        '',
        '`Result<number>` keeps working unchanged, and `Result<number, string>` becomes possible. Defaults are what let a type grow a new parameter without breaking every existing use of it.',
        '',
        'The rules are the ones you would guess: parameters with defaults come after those without, and a default can refer to an earlier parameter — `<T, E = T>` is legal.',
        '',
        'This `Result` type is worth remembering for its own sake, by the way. It models a fallible operation without exceptions, and because `ok` is a literal in each member it is a discriminated union: you cannot reach `value` without proving the operation succeeded. Module 7 puts it to work.',
      ].join('\n'),
      brief: ['Let the failure type be chosen, without breaking callers who do not care.'].join('\n'),
      debrief: [
        'Defaults and constraints combine, and the order reads oddly the first time:',
        '',
        '```ts',
        'type Store<T extends object = Record<string, unknown>> = {',
        '  get(key: string): T | undefined;',
        '};',
        '',
        'type Loose = Store;',
        'type Strict = Store<{ id: string }>;',
        '```',
        '',
        'The constraint comes first, then the default — `T extends object = Record<string, unknown>`. The default must itself satisfy the constraint, which the compiler checks.',
        '',
        'One thing a default is *not*: it is not a fallback for failed inference in a function. These are different mechanisms and it is easy to conflate them.',
        '',
        '```ts',
        'function make<T = string>(): T[] {',
        '  return [];',
        '}',
        '',
        'const a = make();',
        'const b = make<number>();',
        '```',
        '',
        '`a` is `string[]` because the default applied — there was nothing to infer from. But if a call site *does* provide inference material, that always wins over the default. Defaults fill a gap; they do not override.',
        '',
        'You have now met the whole core of generics: parameters, constraints, `keyof`, indexed access, and defaults. What follows in modules 4 and 5 is those same pieces used to *compute* types rather than merely pass them through.',
      ].join('\n'),
      starterCode: [
        'export type Result<T> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: Error };',
      ].join('\n'),
      hiddenChecks: [
        "import type { Result } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<Result<number>, { ok: true; value: number } | { ok: false; error: Error }>',
        '  >,',
        '  Expect<',
        '    Equal<',
        '      Result<string, string>,',
        '      { ok: true; value: string } | { ok: false; error: string }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
      ].join('\n'),
      hints: [
        'Add a second type parameter, and give it a default with `=`.',
        'Then use that parameter instead of the hardcoded `Error`.',
        'Write `export type Result<T, E = Error>` and change `error: Error` to `error: E`.',
      ],
    },
  ],
};
