import type { Module } from '../types';

export const utilityTypes: Module = {
  id: 'utility-types',
  title: 'Utility & Mapped Types',
  blurb:
    'Stop hand-writing variations of the same type. Derive them — first with the built-ins, then by writing the mapped types those built-ins are made of.',
  status: 'ready',
  exercises: [
    {
      id: 'partial',
      title: 'Partial, for the update case',
      concept: [
        'An update endpoint takes *some* of a config, not all of it. Written by hand, that means a second interface that has to be kept in step with the first forever:',
        '',
        '```ts-bad',
        'interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'const patch: ServerConfig = { port: 8080 };',
        '// Property "host" is missing in type "{ port: number; }".',
        '```',
        '',
        '`Partial<T>` derives it instead:',
        '',
        '```ts',
        'interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'type ConfigPatch = Partial<ServerConfig>;',
        '',
        'const patch: ConfigPatch = { port: 8080 };',
        '```',
        '',
        'Its inverse, `Required<T>`, strips the `?` off everything.',
        '',
        'Neither is magic. Both are about ten characters of mapped type, and you will write `Partial` yourself in the last exercise of this module. What matters for now is the habit: when two types are related by a rule, express the rule rather than writing the second type out.',
      ].join('\n'),
      brief: ['Derive the patch type instead of duplicating the config.'].join('\n'),
      debrief: [
        '`Partial` is shallow. It makes the top level optional and does not touch anything nested:',
        '',
        '```ts',
        'interface Config {',
        '  server: { host: string; port: number };',
        '}',
        '',
        'const patch: Partial<Config> = { server: { host: \'localhost\', port: 80 } };',
        '```',
        '',
        'You can omit `server` entirely, but if you supply it you must supply the whole thing. A `DeepPartial` needs recursion, which is module 5.',
        '',
        'The more important caution is about reaching for `Partial` when you are stuck. It is a genuinely useful type and also a convenient way to make an error go away, and those two uses look identical in a diff:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '}',
        '',
        'function render(user: Partial<User>): string {',
        '  return user.email ?? \'unknown\';',
        '}',
        '```',
        '',
        'Every property is now optional, so nothing is missing, so nothing complains. What you have actually done is move the checks to every call site downstream, forever. If a function needs an email, it should ask for one.',
        '',
        'The honest test is whether *partial* describes the data. A PATCH body genuinely is partial. A user you just loaded from the database is not.',
      ].join('\n'),
      starterCode: [
        'export interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'export type ConfigPatch = ServerConfig;',
      ].join('\n'),
      hiddenChecks: [
        "import type { ConfigPatch } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ConfigPatch, { host?: string; port?: number; tls?: boolean }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'export type ConfigPatch = Partial<ServerConfig>;',
      ].join('\n'),
      hints: [
        'There is a built-in utility type for exactly this.',
        'It takes the type as a type argument, like a function call with angle brackets.',
        'Write `export type ConfigPatch = Partial<ServerConfig>;`',
      ],
    },
    {
      id: 'pick-and-omit',
      title: 'Pick and Omit',
      concept: [
        '`Pick<T, Keys>` builds a type from the properties you name. `Omit<T, Keys>` builds one from everything except the properties you name:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '}',
        '',
        'type PublicUser = Pick<User, \'id\' | \'email\'>;',
        'type WithoutSecret = Omit<User, \'passwordHash\'>;',
        '',
        'const shown: PublicUser = { id: \'u1\', email: \'ada@example.com\' };',
        '```',
        '',
        'Both keys arguments are unions of string *literal* types — the same literal types from module 1, now naming properties.',
        '',
        '`Pick` is checked against the source, so a typo is an error rather than a silently missing property:',
        '',
        '```ts-bad',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '}',
        '',
        'type Broken = Pick<User, \'id\' | \'emial\'>;',
        '```',
        '',
        '`Omit` is deliberately *not* checked that way: `Omit<User, \'nope\'>` compiles and does nothing. That is intentional, so `Omit` can be used on types where the key may or may not be present, but it does mean a typo there fails silently.',
      ].join('\n'),
      brief: [
        'Derive the public shape so a password hash can never reach an API response.',
        '',
        'Both `Pick` and `Omit` will satisfy the check. Choose the one that is still correct in six months.',
      ].join('\n'),
      debrief: [
        'The check accepted either, but they are not equally good here, and the difference is a security property rather than a style preference.',
        '',
        '`Pick` is an **allowlist**. `Omit` is a **denylist**.',
        '',
        'Picture someone adding a field to `User` next quarter:',
        '',
        '```ts',
        'interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '  mfaSecret: string;',
        '}',
        '',
        'type ViaPick = Pick<User, \'id\' | \'email\'>;',
        'type ViaOmit = Omit<User, \'passwordHash\'>;',
        '',
        'const leaked: ViaOmit = {',
        '  id: \'u1\',',
        '  email: \'ada@example.com\',',
        '  mfaSecret: \'totp-seed\',',
        '};',
        '```',
        '',
        '`ViaPick` is unchanged and still safe. `ViaOmit` silently grew a `mfaSecret`, and the type that exists specifically to keep secrets out of API responses now has one in it. No error, no diff in that file, nothing to review.',
        '',
        'This is the general rule and it long predates TypeScript: **allowlist the things you expose, denylist nothing.** When new data appears, an allowlist fails closed and a denylist fails open.',
        '',
        '`Omit` is still the right tool plenty of the time — dropping an `id` before an insert, removing a prop a wrapper component consumes itself. Just not when the consequence of being wrong is a leak.',
      ].join('\n'),
      starterCode: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '}',
        '',
        'export type PublicUser = User;',
      ].join('\n'),
      hiddenChecks: [
        "import type { PublicUser } from './exercise';",
        'type _cases = [Expect<Equal<PublicUser, { id: string; email: string }>>];',
      ].join('\n'),
      solution: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '}',
        '',
        "export type PublicUser = Pick<User, 'id' | 'email'>;",
      ].join('\n'),
      hints: [
        'Both `Pick` and `Omit` can express this. The second type argument is a union of string literal keys.',
        'One of them lists what to keep, the other lists what to drop. For a type whose job is to not leak secrets, think about which one behaves better the day someone adds a `mfaSecret` field.',
        "Write `Pick<User, 'id' | 'email'>`.",
      ],
    },
    {
      id: 'record',
      title: 'Record for lookup tables',
      concept: [
        '`Record<Keys, Value>` builds an object type from a union of keys and a single value type:',
        '',
        '```ts',
        'type HttpMethod = \'GET\' | \'POST\' | \'DELETE\';',
        'type Handler = (body: string) => string;',
        '',
        'type HandlerMap = Record<HttpMethod, Handler>;',
        '',
        'const handlers: HandlerMap = {',
        '  GET: (b) => b,',
        '  POST: (b) => b,',
        '  DELETE: (b) => b,',
        '};',
        '```',
        '',
        'Because the keys come from a union, the compiler knows the table is meant to be *complete*. Miss one and it says so:',
        '',
        '```ts-bad',
        'type HttpMethod = \'GET\' | \'POST\' | \'DELETE\';',
        '',
        'const handlers: Record<HttpMethod, (b: string) => string> = {',
        '  GET: (b) => b,',
        '  POST: (b) => b,',
        '};',
        '// Property "DELETE" is missing.',
        '```',
        '',
        'That is the real value of typing a dispatch table this way. Add a method to the union and every table in the codebase that has not been updated becomes a compile error — the same trick as the exhaustive `switch` in module 2, in object form.',
      ].join('\n'),
      brief: ['Type the handler map so a missing method is a compile error.'].join('\n'),
      debrief: [
        '`Record<string, T>` and `Record<SomeUnion, T>` look similar and behave completely differently.',
        '',
        'A union of literals gives you a fixed set of known keys. `string` gives you an *index signature* — any key at all, and no guarantee that any particular one exists:',
        '',
        '```ts',
        'const byId: Record<string, string> = {};',
        'const value = byId[\'missing\'];',
        '```',
        '',
        'Under `noUncheckedIndexedAccess` (on in this project), `value` is `string | undefined`, because the compiler is honest that the key might not be there. Without that flag it would be plain `string`, and you would have a confident type for a value that is `undefined` at runtime. That flag is not part of `strict`, and it is one of the most valuable ones to turn on.',
        '',
        'For the genuinely sparse case — known keys, but not all present — combine the two:',
        '',
        '```ts',
        'type Feature = \'darkMode\' | \'betaSearch\';',
        '',
        'const overrides: Partial<Record<Feature, boolean>> = {',
        '  darkMode: true,',
        '};',
        '```',
        '',
        'Now the keys are still checked for typos, but you are not obliged to list them all. That combination comes up constantly for config overrides and caches.',
      ].join('\n'),
      starterCode: [
        "export type HttpMethod = 'GET' | 'POST' | 'DELETE';",
        '',
        'export type Handler = (body: string) => string;',
        '',
        'export type HandlerMap = object;',
      ].join('\n'),
      hiddenChecks: [
        "import type { HandlerMap, Handler } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<HandlerMap, { GET: Handler; POST: Handler; DELETE: Handler }>>,',
        '];',
      ].join('\n'),
      solution: [
        "export type HttpMethod = 'GET' | 'POST' | 'DELETE';",
        '',
        'export type Handler = (body: string) => string;',
        '',
        'export type HandlerMap = Record<HttpMethod, Handler>;',
      ].join('\n'),
      hints: [
        'Both type arguments are types you already have in this file.',
        'Keys first, then the value type.',
        'Write `Record<HttpMethod, Handler>`.',
      ],
    },
    {
      id: 'extract-from-functions',
      title: 'Read types back off a function',
      concept: [
        'Sometimes the type you want already exists inside a function signature you did not write.',
        '',
        '`ReturnType<F>` and `Parameters<F>` read them back out, and `Awaited<T>` unwraps a promise however deep it is nested:',
        '',
        '```ts',
        'async function fetchUser(id: string, includeDeleted: boolean) {',
        '  return { id, name: String(includeDeleted) };',
        '}',
        '',
        'type Args = Parameters<typeof fetchUser>;',
        'type Pending = ReturnType<typeof fetchUser>;',
        'type User = Awaited<Pending>;',
        '',
        'const args: Args = [\'u1\', false];',
        'const user: User = { id: \'u1\', name: \'false\' };',
        '```',
        '',
        'Note the `typeof`. These utilities take a *type*, and `fetchUser` is a *value*, so `typeof` is what bridges the two worlds — the same bridge as `typeof HTTP_METHODS` back in module 1.',
        '',
        '`Parameters` gives you a tuple, which is why `Args` above is `[string, boolean]` and can be spread straight back into a call.',
      ].join('\n'),
      brief: [
        'Pull the argument tuple and the resolved result type out of `fetchUser`.',
        '',
        'Remember it is `async`.',
      ].join('\n'),
      debrief: [
        'These are not built into the compiler. Every one is a few lines of conditional type in TypeScript\'s own `lib.es5.d.ts`, and `ReturnType` is the whole idea in one line:',
        '',
        '```ts',
        'type MyReturnType<F extends (...args: never[]) => unknown> =',
        '  F extends (...args: never[]) => infer R ? R : never;',
        '',
        'declare function load(): string;',
        'type R = MyReturnType<typeof load>;',
        '',
        'const value: R = \'ok\';',
        '```',
        '',
        '`infer R` is pattern matching: match the shape of a function type, and name whatever is in the return position. That is module 5, and after it you will be able to read the standard library instead of memorising it.',
        '',
        'One caution about deriving types from implementations. It cuts both ways: the type follows the code, which is exactly what you want for internal plumbing, and exactly what you do not want at a public boundary. If `fetchUser` is exported from a package, `ReturnType<typeof fetchUser>` means any change to its body is a change to your published API, with nothing in between to stop it.',
        '',
        'For internal glue, derive freely. At a boundary, declare the type explicitly and let the compiler check the implementation against it.',
      ].join('\n'),
      starterCode: [
        'export async function fetchUser(id: string, includeDeleted: boolean) {',
        '  return { id, name: String(includeDeleted) };',
        '}',
        '',
        'export type FetchArgs = unknown;',
        'export type FetchedUser = unknown;',
      ].join('\n'),
      hiddenChecks: [
        "import type { FetchArgs, FetchedUser } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<FetchArgs, [id: string, includeDeleted: boolean]>>,',
        '  Expect<Equal<FetchedUser, { id: string; name: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export async function fetchUser(id: string, includeDeleted: boolean) {',
        '  return { id, name: String(includeDeleted) };',
        '}',
        '',
        'export type FetchArgs = Parameters<typeof fetchUser>;',
        'export type FetchedUser = Awaited<ReturnType<typeof fetchUser>>;',
      ].join('\n'),
      hints: [
        '`Parameters<F>` gives a tuple of the argument types.',
        '`fetchUser` is async, so its return type is a `Promise` — you need to unwrap it.',
        'Write `Parameters<typeof fetchUser>` and `Awaited<ReturnType<typeof fetchUser>>`.',
      ],
    },
    {
      id: 'first-mapped-type',
      title: 'Write your own mapped type',
      concept: [
        'The built-ins are not special. They are *mapped types*, and you can write your own.',
        '',
        'The syntax looks like an index signature with `in` instead of a colon:',
        '',
        '```ts',
        'type Nullable<T> = {',
        '  [K in keyof T]: T[K] | null;',
        '};',
        '',
        'type Row = Nullable<{ id: string; age: number }>;',
        '',
        'const row: Row = { id: null, age: 42 };',
        '```',
        '',
        'Read it as a loop. `keyof T` produces the union of property names; `K` is bound to each one in turn; `T[K]` is that property\'s original type — the indexed access from module 3. Whatever you write on the right becomes the new property type.',
        '',
        'This particular one is the shape a database row takes after a `LEFT JOIN`, which is where you will actually reach for it.',
        '',
        'A mapped type written directly over `keyof T` like this is called *homomorphic*, which sounds worse than it is: it means the mapping preserves the original\'s structure, so `readonly` and `?` on the source properties survive into the result unless you deliberately change them. That is why `Partial<T>` does not accidentally strip your `readonly` markers.',
      ].join('\n'),
      brief: ['Write a mapped type that makes every property nullable.'].join('\n'),
      debrief: [
        'A mapped type can rewrite the *keys* as well as the values, using `as` in the key position:',
        '',
        '```ts',
        'type Prefixed<T> = {',
        '  [K in keyof T as `data-${string & K}`]: T[K];',
        '};',
        '',
        'type Attrs = Prefixed<{ id: string }>;',
        '',
        'const a: Attrs = { \'data-id\': \'x\' };',
        '```',
        '',
        'That is a preview of module 5, where template literal types make it genuinely powerful — generating getter names, event handler names, or whole derived APIs from one source type.',
        '',
        'The `string & K` is a detail you will hit the first time you try it yourself. `keyof T` can include `symbol` and `number`, not just `string`, and a template literal type needs something string-shaped. Intersecting with `string` filters the union down to the keys that qualify.',
        '',
        'One more thing worth knowing now: key remapping to `never` *removes* a property. That is how `Omit` is implemented, and it means you can write filters like "every property whose type is a function" with nothing but a mapped type and a conditional.',
      ].join('\n'),
      starterCode: [
        'export type Nullable<T> = T;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Nullable } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Nullable<{ id: string; age: number }>,',
        '      { id: string | null; age: number | null }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Nullable<T> = {',
        '  [K in keyof T]: T[K] | null;',
        '};',
      ].join('\n'),
      hints: [
        'The syntax looks like an index signature, but with `in` instead of `:`.',
        '`keyof T` is the union of property names; `K` takes each one in turn.',
        'Write `{ [K in keyof T]: T[K] | null }`.',
      ],
    },
    {
      id: 'mapped-modifiers',
      title: 'Add and remove modifiers',
      concept: [
        'A mapped type can change more than the property types — it can add or remove the `readonly` and `?` modifiers themselves.',
        '',
        'Writing them adds; prefixing with `-` removes:',
        '',
        '```ts',
        'type Mutable<T> = {',
        '  -readonly [K in keyof T]: T[K];',
        '};',
        '',
        'type Concrete<T> = {',
        '  [K in keyof T]-?: T[K];',
        '};',
        '',
        'type A = Mutable<{ readonly id: string }>;',
        'type B = Concrete<{ name?: string }>;',
        '',
        'const a: A = { id: \'u1\' };',
        'a.id = \'u2\';',
        '',
        'const b: B = { name: \'ada\' };',
        '```',
        '',
        'Position matters and mirrors where the modifiers normally live: `readonly` goes before the key, `?` after it. The minus sign attaches to each in place — `-readonly [K in keyof T]` and `[K in keyof T]-?`.',
        '',
        'Removing `?` does two things, which is easy to miss: the key becomes required *and* `undefined` is removed from its type. That is what makes `Required<T>` genuinely useful rather than cosmetic.',
      ].join('\n'),
      brief: ['Write both directions: one that strips `readonly`, one that strips `?`.'].join('\n'),
      debrief: [
        '`Concrete` is `Required<T>`, which ships with TypeScript. `Mutable` does not, and the omission is deliberate rather than an oversight.',
        '',
        '`readonly` is shallow and compile-time only — you met that in module 1 — so a built-in `Mutable` would be an official-looking tool whose entire job is to discard a safety marker. The language leaves you to write the four lines yourself, which is a small speed bump in front of exactly the operation that deserves one.',
        '',
        'Both of these are shallow, like everything else in this module:',
        '',
        '```ts',
        'type Mutable<T> = {',
        '  -readonly [K in keyof T]: T[K];',
        '};',
        '',
        'type Nested = Mutable<{ readonly inner: { readonly id: string } }>;',
        '',
        'const n: Nested = { inner: { id: \'a\' } };',
        'n.inner = { id: \'b\' };',
        '```',
        '',
        'The outer `inner` became writable; the `id` inside it did not. Going all the way down means recursing, which needs a conditional type — and that is the next module.',
        '',
        'There is a `+` prefix too, for symmetry: `+readonly` and `+?` explicitly add. You will almost never see it, since writing the bare modifier does the same thing, but it exists and it is not a typo when you meet it.',
      ].join('\n'),
      starterCode: [
        'export type Mutable<T> = T;',
        '',
        'export type Concrete<T> = T;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Mutable, Concrete } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Mutable<{ readonly id: string }>, { id: string }>>,',
        '  Expect<Equal<Concrete<{ name?: string }>, { name: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Mutable<T> = {',
        '  -readonly [K in keyof T]: T[K];',
        '};',
        '',
        'export type Concrete<T> = {',
        '  [K in keyof T]-?: T[K];',
        '};',
      ].join('\n'),
      hints: [
        'The `readonly` modifier goes before the key, and `?` goes after it — the minus sign attaches to each in place.',
        'So one reads `-readonly [K in keyof T]` and the other reads `[K in keyof T]-?`.',
        'Write `{ -readonly [K in keyof T]: T[K] }` and `{ [K in keyof T]-?: T[K] }`.',
      ],
    },
    {
      id: 'rebuild-partial',
      title: 'Rebuild Partial from scratch',
      concept: [
        'You have all the pieces now. `Partial<T>` is one mapped type with one modifier:',
        '',
        '```ts',
        'type MyPartial<T> = {',
        '  [K in keyof T]?: T[K];',
        '};',
        '',
        'type Patch = MyPartial<{ a: string; b: number }>;',
        '',
        'const p: Patch = { b: 1 };',
        '```',
        '',
        'That is the real implementation, near enough verbatim from TypeScript\'s own `lib.es5.d.ts`. So are its neighbours:',
        '',
        '```ts',
        'type MyRequired<T> = { [K in keyof T]-?: T[K] };',
        'type MyReadonly<T> = { readonly [K in keyof T]: T[K] };',
        'type MyRecord<K extends keyof never, V> = { [P in K]: V };',
        '',
        'const r: MyRecord<\'a\' | \'b\', number> = { a: 1, b: 2 };',
        '```',
        '',
        'Writing them out is the fastest way to stop seeing the built-ins as magic and start seeing them as a small vocabulary you can extend.',
      ].join('\n'),
      brief: ['Rebuild `Partial` from scratch. Using the real one would rather defeat the point.'].join('\n'),
      debrief: [
        'It is genuinely worth opening `lib.es5.d.ts` once — your editor will jump there if you go to the definition of `Partial`. Almost every utility type is between one and five lines, and seeing that removes a lot of the mystique.',
        '',
        'The ones you have now effectively written yourself: `Partial`, `Required`, `Readonly`, `Record`, and with a little more work `Pick`. The rest of the standard set — `Omit`, `Exclude`, `Extract`, `NonNullable`, `ReturnType`, `Parameters`, `Awaited` — all need conditional types, which is the next module. `Omit` is the interesting one, since it is built *from* `Pick` and `Exclude` rather than from scratch.',
        '',
        'The practical payoff is not that you will reimplement them. It is that when you need something the standard library does not have — and you will, constantly, because every codebase has its own shapes — you will write it in four lines instead of duplicating a type by hand and letting the copies drift.',
        '',
        'That is the whole argument of this module in one sentence: **when two types are related by a rule, write the rule.**',
      ].join('\n'),
      starterCode: ['export type MyPartial<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { MyPartial } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<MyPartial<{ a: string; b: number }>, { a?: string; b?: number }>>,',
        '];',
      ].join('\n'),
      solution: ['export type MyPartial<T> = {', '  [K in keyof T]?: T[K];', '};'].join('\n'),
      hints: [
        'Same mapped-type skeleton as `Nullable`, but you are changing a modifier rather than the value type.',
        'The `?` goes immediately after the closing bracket of the key.',
        'Write `{ [K in keyof T]?: T[K] }`.',
      ],
    },
  ],
};
