import type { Module } from '../types';

export const utilityTypes: Module = {
  id: 'utility-types',
  title: 'Utility & Mapped Types',
  blurb:
    'Stop hand-writing variations of the same type. Derive them — first with the built-ins, then by writing the mapped types those built-ins are made of.',
  status: 'ready',
  exercises: [
    {
      id: 'partial',
      title: 'Partial, for the update case',
      brief: [
        'An update endpoint takes *some* of a config, not all of it. Duplicating the type with',
        'every field made optional gives you two things to keep in sync.',
        '',
        '`Partial<T>` does it for you.',
      ].join('\n'),
      starterCode: [
        'export interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'export type ConfigPatch = ServerConfig;',
      ].join('\n'),
      hiddenChecks: [
        "import type { ConfigPatch } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ConfigPatch, { host?: string; port?: number; tls?: boolean }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export interface ServerConfig {',
        '  host: string;',
        '  port: number;',
        '  tls: boolean;',
        '}',
        '',
        'export type ConfigPatch = Partial<ServerConfig>;',
      ].join('\n'),
      hints: [
        'There is a built-in utility type for exactly this.',
        'It takes the type as a type argument, like a function call with angle brackets.',
        'Write `export type ConfigPatch = Partial<ServerConfig>;`',
      ],
    },
    {
      id: 'pick-and-omit',
      title: 'Pick and Omit',
      brief: [
        'The user record has a `passwordHash` on it, and it must never reach an API response.',
        'Writing a second interface by hand means the day someone adds a `mfaSecret`, the',
        'public type silently keeps working and leaks it.',
        '',
        '`Omit<T, K>` derives the safe shape from the real one, so new secret fields have to be',
        'excluded deliberately. Its counterpart `Pick<T, K>` goes the other way, listing what',
        'to keep.',
      ].join('\n'),
      starterCode: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '}',
        '',
        'export type PublicUser = User;',
      ].join('\n'),
      hiddenChecks: [
        "import type { PublicUser } from './exercise';",
        'type _cases = [Expect<Equal<PublicUser, { id: string; email: string }>>];',
      ].join('\n'),
      solution: [
        'export interface User {',
        '  id: string;',
        '  email: string;',
        '  passwordHash: string;',
        '}',
        '',
        "export type PublicUser = Omit<User, 'passwordHash'>;",
      ].join('\n'),
      hints: [
        'The second type argument is the key to remove, written as a string literal type.',
        "`Pick<User, 'id' | 'email'>` would also satisfy the check — but think about which one stays correct when a field is added.",
        "Write `Omit<User, 'passwordHash'>`.",
      ],
    },
    {
      id: 'record',
      title: 'Record for lookup tables',
      brief: [
        '`Record<Keys, Value>` builds an object type from a union of keys and one value type.',
        '',
        'Because the keys come from a union, the compiler knows the table is *complete* — miss',
        'a method and it says so. That is the entire value of typing a dispatch table this way.',
      ].join('\n'),
      starterCode: [
        "export type HttpMethod = 'GET' | 'POST' | 'DELETE';",
        '',
        'export type Handler = (body: string) => string;',
        '',
        'export type HandlerMap = object;',
      ].join('\n'),
      hiddenChecks: [
        "import type { HandlerMap, Handler } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<HandlerMap, { GET: Handler; POST: Handler; DELETE: Handler }>>,',
        '];',
      ].join('\n'),
      solution: [
        "export type HttpMethod = 'GET' | 'POST' | 'DELETE';",
        '',
        'export type Handler = (body: string) => string;',
        '',
        'export type HandlerMap = Record<HttpMethod, Handler>;',
      ].join('\n'),
      hints: [
        'Both type arguments are types you already have in this file.',
        'Keys first, then the value type.',
        'Write `Record<HttpMethod, Handler>`.',
      ],
    },
    {
      id: 'extract-from-functions',
      title: 'Read types back off a function',
      brief: [
        'Sometimes the type you want already exists — inside a function signature you did not',
        'write.',
        '',
        '`ReturnType<F>` and `Parameters<F>` pull them out, and `Awaited<T>` unwraps a promise.',
        'Note the `typeof` in `ReturnType<typeof fn>`: these take a *type*, and `fetchUser` is a',
        'value, so you need `typeof` to cross over.',
      ].join('\n'),
      starterCode: [
        'export async function fetchUser(id: string, includeDeleted: boolean) {',
        '  return { id, name: String(includeDeleted) };',
        '}',
        '',
        'export type FetchArgs = unknown;',
        'export type FetchedUser = unknown;',
      ].join('\n'),
      hiddenChecks: [
        "import type { FetchArgs, FetchedUser } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<FetchArgs, [id: string, includeDeleted: boolean]>>,',
        '  Expect<Equal<FetchedUser, { id: string; name: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export async function fetchUser(id: string, includeDeleted: boolean) {',
        '  return { id, name: String(includeDeleted) };',
        '}',
        '',
        'export type FetchArgs = Parameters<typeof fetchUser>;',
        'export type FetchedUser = Awaited<ReturnType<typeof fetchUser>>;',
      ].join('\n'),
      hints: [
        '`Parameters<F>` gives a tuple of the argument types.',
        '`fetchUser` is async, so its return type is a `Promise` — you need to unwrap it.',
        'Write `Parameters<typeof fetchUser>` and `Awaited<ReturnType<typeof fetchUser>>`.',
      ],
    },
    {
      id: 'first-mapped-type',
      title: 'Write your own mapped type',
      brief: [
        'The built-ins are not magic — they are mapped types, and you can write your own.',
        '',
        '`{ [K in keyof T]: ... }` walks every key of `T` and decides what its value type',
        'becomes. `K` is bound to each key in turn, so `T[K]` is that property’s original type.',
        '',
        'Build one that makes every property nullable. This is the shape a database row takes',
        'after a `LEFT JOIN`, which is where you will actually reach for it.',
      ].join('\n'),
      starterCode: [
        'export type Nullable<T> = T;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Nullable } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Nullable<{ id: string; age: number }>,',
        '      { id: string | null; age: number | null }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Nullable<T> = {',
        '  [K in keyof T]: T[K] | null;',
        '};',
      ].join('\n'),
      hints: [
        'The syntax looks like an index signature, but with `in` instead of `:`.',
        '`keyof T` is the union of property names; `K` takes each one in turn.',
        'Write `{ [K in keyof T]: T[K] | null }`.',
      ],
    },
    {
      id: 'mapped-modifiers',
      title: 'Add and remove modifiers',
      brief: [
        'A mapped type can change more than the value type — it can add or strip the `readonly`',
        'and `?` modifiers themselves.',
        '',
        'Prefixing with `-` removes one. `-readonly` makes properties writable; `-?` makes',
        'optional properties required (and drops `undefined` from their type).',
        '',
        'Write both directions.',
      ].join('\n'),
      starterCode: [
        'export type Mutable<T> = T;',
        '',
        'export type Concrete<T> = T;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Mutable, Concrete } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Mutable<{ readonly id: string }>, { id: string }>>,',
        '  Expect<Equal<Concrete<{ name?: string }>, { name: string }>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Mutable<T> = {',
        '  -readonly [K in keyof T]: T[K];',
        '};',
        '',
        'export type Concrete<T> = {',
        '  [K in keyof T]-?: T[K];',
        '};',
      ].join('\n'),
      hints: [
        'The `readonly` modifier goes before the key, and `?` goes after it — the minus sign attaches to each in place.',
        'So one reads `-readonly [K in keyof T]` and the other reads `[K in keyof T]-?`.',
        'Write `{ -readonly [K in keyof T]: T[K] }` and `{ [K in keyof T]-?: T[K] }`.',
      ],
    },
    {
      id: 'rebuild-partial',
      title: 'Rebuild Partial from scratch',
      brief: [
        'You have all the pieces now. `Partial<T>` is four tokens of mapped type, and writing',
        'it yourself is the fastest way to stop seeing the built-ins as magic.',
        '',
        'No `Partial` allowed — that would be cheating, and the check will catch it anyway if',
        'you get the modifier wrong.',
      ].join('\n'),
      starterCode: ['export type MyPartial<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { MyPartial } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<MyPartial<{ a: string; b: number }>, { a?: string; b?: number }>>,',
        '];',
      ].join('\n'),
      solution: ['export type MyPartial<T> = {', '  [K in keyof T]?: T[K];', '};'].join('\n'),
      hints: [
        'Same mapped-type skeleton as `Nullable`, but you are changing a modifier rather than the value type.',
        'The `?` goes immediately after the closing bracket of the key.',
        'Write `{ [K in keyof T]?: T[K] }`.',
      ],
    },
  ],
};
