import type { Module } from '../types';

export const conditionalTypes: Module = {
  id: 'conditional-types',
  title: 'Conditional & Template Literal Types',
  blurb:
    'Types that branch, types that pattern-match with `infer`, and types built out of strings. This is where TypeScript stops looking like annotations and starts looking like a language.',
  status: 'ready',
  exercises: [
    {
      id: 'conditional-basics',
      title: 'A type that branches',
      brief: [
        '`A extends B ? X : Y` is an if-statement for types. It asks "is `A` assignable to',
        '`B`?" and evaluates to one side or the other.',
        '',
        'Note that `extends` here means assignability, not class inheritance — the same meaning',
        'it had in generic constraints.',
      ].join('\n'),
      starterCode: ['export type IsArray<T> = false;'].join('\n'),
      hiddenChecks: [
        "import type { IsArray } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<IsArray<string[]>, true>>,',
        '  Expect<Equal<IsArray<number[]>, true>>,',
        '  Expect<Equal<IsArray<string>, false>>,',
        '];',
      ].join('\n'),
      solution: ['export type IsArray<T> = T extends unknown[] ? true : false;'].join('\n'),
      hints: [
        'You need a condition that is satisfied by every array and by nothing else.',
        '`unknown[]` is the array of anything; `readonly unknown[]` would also admit readonly arrays.',
        'Write `T extends unknown[] ? true : false`.',
      ],
    },
    {
      id: 'infer',
      title: 'infer pulls a type out of a pattern',
      brief: [
        '`infer` is pattern matching. Inside the condition of a conditional type, `infer U`',
        'says: "match anything here, and call it `U`, so I can use it in the true branch."',
        '',
        'Unwrapping a promise is the canonical use, and the thing `Awaited` does for you.',
      ].join('\n'),
      starterCode: ['export type UnwrapPromise<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { UnwrapPromise } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<UnwrapPromise<Promise<string>>, string>>,',
        '  Expect<Equal<UnwrapPromise<Promise<{ id: number }>>, { id: number }>>,',
        '  Expect<Equal<UnwrapPromise<number>, number>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type UnwrapPromise<T> = T extends Promise<infer U> ? U : T;',
      ].join('\n'),
      hints: [
        'The shape you are matching is `Promise<something>`, and you want to name that something.',
        'Look at the third case: a non-promise must come back untouched, so the false branch is `T`, not `never`.',
        'Write `T extends Promise<infer U> ? U : T`.',
      ],
    },
    {
      id: 'infer-element',
      title: 'infer, on an array',
      brief: [
        'Same tool, different pattern. Match an array and name its element type.',
        '',
        'The `readonly` in the pattern matters more than it looks: a `readonly string[]` is not',
        'assignable to `string[]`, so matching against the mutable form alone would fail for',
        'anything produced by `as const`.',
      ].join('\n'),
      starterCode: ['export type ElementOf<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { ElementOf } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ElementOf<string[]>, string>>,',
        "  Expect<Equal<ElementOf<readonly ['a', 'b']>, 'a' | 'b'>>,",
        '  Expect<Equal<ElementOf<number>, never>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type ElementOf<T> = T extends readonly (infer U)[] ? U : never;',
      ].join('\n'),
      hints: [
        'Start from `T extends (infer U)[] ? U : never` and check which case fails.',
        'A `readonly` tuple is not assignable to a mutable array type, so the pattern has to allow readonly.',
        'Write `T extends readonly (infer U)[] ? U : never`.',
      ],
    },
    {
      id: 'distributive',
      title: 'Conditionals distribute over unions',
      brief: [
        'Here is the behaviour that surprises everyone once and then becomes indispensable.',
        '',
        'When the checked type is a bare type parameter and you hand it a union, the conditional',
        'runs *once per member* and the results are unioned back together. So',
        '`Filter<string | number>` is `Filter<string> | Filter<number>`, not one check against',
        'the whole union.',
        '',
        'That is what makes a one-line `Exclude` possible: members that match become `never`,',
        'and `never` vanishes from a union.',
      ].join('\n'),
      starterCode: ['export type MyExclude<T, U> = T;'].join('\n'),
      hiddenChecks: [
        "import type { MyExclude } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<MyExclude<'a' | 'b' | 'c', 'a'>, 'b' | 'c'>>,",
        '  Expect<Equal<MyExclude<string | number | boolean, boolean>, string | number>>,',
        '];',
      ].join('\n'),
      solution: ['export type MyExclude<T, U> = T extends U ? never : T;'].join('\n'),
      hints: [
        'Each member of `T` is tested separately. You want to drop the ones that match `U`.',
        'Dropping a member means evaluating to `never` for it.',
        'Write `T extends U ? never : T`.',
      ],
    },
    {
      id: 'template-literals',
      title: 'Types built out of strings',
      brief: [
        'A template literal type interpolates other types into a string type, using the same',
        'backtick syntax as a runtime template literal.',
        '',
        'Combined with the built-in `Capitalize`, you can express naming conventions in the type',
        'system — and get autocomplete for names that do not exist anywhere yet.',
      ].join('\n'),
      starterCode: ['export type EventName<T extends string> = string;'].join('\n'),
      hiddenChecks: [
        "import type { EventName } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<EventName<'click'>, 'onClick'>>,",
        "  Expect<Equal<EventName<'focus'>, 'onFocus'>>,",
        '];',
      ].join('\n'),
      solution: [
        'export type EventName<T extends string> = `on${Capitalize<T>}`;',
      ].join('\n'),
      hints: [
        'Use backticks, and `${...}` to interpolate the type parameter.',
        "`'onclick'` is not `'onClick'` — there is a built-in utility that fixes the case.",
        'Write ``on${Capitalize<T>}`` between backticks.',
      ],
    },
    {
      id: 'key-remapping',
      title: 'Rename keys while you map them',
      brief: [
        'A mapped type can rewrite the *keys* too, using `as` in the key position. Combine that',
        'with a template literal and you can generate an entire derived API shape.',
        '',
        'Build the getter interface for a type: every property becomes a `getX()` method',
        'returning that property’s type.',
      ].join('\n'),
      starterCode: ['export type Getters<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { Getters } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Getters<{ name: string; age: number }>,',
        '      { getName: () => string; getAge: () => number }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Getters<T> = {',
        '  [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K];',
        '};',
      ].join('\n'),
      hints: [
        'The key clause becomes `[K in keyof T as NewKey]`.',
        '`keyof T` can include symbols, so `Capitalize<K>` alone will not type-check — intersect with `string` first.',
        'Write ``[K in keyof T as `get${Capitalize<string & K>}`]: () => T[K]``.',
      ],
    },
    {
      id: 'recursive-types',
      title: 'A type that calls itself',
      brief: [
        'Conditional types can recurse. `DeepReadonly` applies `readonly` all the way down',
        'instead of only at the top level, which is what `Readonly<T>` actually does.',
        '',
        'The base case matters: recurse only into object types, or you will try to map over',
        '`string` and get something strange.',
      ].join('\n'),
      starterCode: ['export type DeepReadonly<T> = Readonly<T>;'].join('\n'),
      hiddenChecks: [
        "import type { DeepReadonly } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      DeepReadonly<{ a: string; nested: { b: number } }>,',
        '      { readonly a: string; readonly nested: { readonly b: number } }',
        '    >',
        '  >,',
        '  Expect<Equal<DeepReadonly<string>, string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type DeepReadonly<T> = T extends object',
        '  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }',
        '  : T;',
      ].join('\n'),
      hints: [
        'Guard with a conditional first: only objects get mapped, everything else passes through.',
        'Inside the mapped type, apply `DeepReadonly` to the property type as well as adding `readonly`.',
        'Write `T extends object ? { readonly [K in keyof T]: DeepReadonly<T[K]> } : T`.',
      ],
    },
  ],
};
