import type { Module } from '../types';

export const conditionalTypes: Module = {
  id: 'conditional-types',
  title: 'Conditional & Template Literal Types',
  blurb:
    'Types that branch, types that pattern-match with `infer`, and types built out of strings. This is where TypeScript stops looking like annotations and starts looking like a language.',
  status: 'ready',
  exercises: [
    {
      id: 'conditional-basics',
      title: 'A type that branches',
      concept: [
        'A conditional type is an if-statement that runs on types at compile time:',
        '',
        '```ts',
        'type IsArray<T> = T extends unknown[] ? true : false;',
        '',
        'type A = IsArray<string[]>;',
        'type B = IsArray<string>;',
        '',
        'const a: A = true;',
        'const b: B = false;',
        '```',
        '',
        '`T extends U ? X : Y` asks "is `T` assignable to `U`?" and evaluates to one branch or the other. As in a generic constraint, `extends` means *assignable to*, not class inheritance — `\'GET\' extends string` is true, and so is `{ a: 1; b: 2 } extends { a: number }`.',
        '',
        'The result is an ordinary type, so it composes with everything else:',
        '',
        '```ts',
        'type Unwrap<T> = T extends { value: infer V } ? V : T;',
        '',
        'type C = Unwrap<{ value: number }>;',
        'type D = Unwrap<string>;',
        '',
        'const c: C = 42;',
        'const d: D = \'plain\';',
        '```',
        '',
        'This is where TypeScript\'s type system stops being a labelling scheme and becomes a small functional language: it has parameters, branching, and — as you will see at the end of this module — recursion.',
      ].join('\n'),
      brief: ['Write a conditional type that is `true` for every array and `false` otherwise.'].join('\n'),
      debrief: [
        'There is a limitation here that will bite you in real code, so it is worth meeting deliberately.',
        '',
        'A conditional type cannot be evaluated while `T` is still unknown. Inside a generic function body, `T` is exactly that — unresolved — so the compiler cannot check a return value against a conditional return type:',
        '',
        '```ts',
        'type Result<T> = T extends true ? string : number;',
        '',
        'function pick<T extends boolean>(flag: T): Result<T> {',
        '  return (flag ? \'yes\' : 0) as Result<T>;',
        '}',
        '',
        'const s: string = pick(true);',
        'const n: number = pick(false);',
        '```',
        '',
        'Note the cast. It is not laziness — without it the function does not compile, because the compiler has no way to know which branch applies until a caller supplies `T`. The *call sites* type-check beautifully; the body cannot.',
        '',
        'That is a real trade, and it is why overloads still exist:',
        '',
        '```ts',
        'function pick(flag: true): string;',
        'function pick(flag: false): number;',
        'function pick(flag: boolean): string | number {',
        '  return flag ? \'yes\' : 0;',
        '}',
        '',
        'const s: string = pick(true);',
        '```',
        '',
        'Same experience for callers, no cast, and the implementation is checked against a signature that actually describes it. Reach for conditional return types when the relationship is genuinely open-ended; reach for overloads when there are two or three concrete cases.',
      ].join('\n'),
      starterCode: ['export type IsArray<T> = false;'].join('\n'),
      hiddenChecks: [
        "import type { IsArray } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<IsArray<string[]>, true>>,',
        '  Expect<Equal<IsArray<number[]>, true>>,',
        '  Expect<Equal<IsArray<string>, false>>,',
        '];',
      ].join('\n'),
      solution: ['export type IsArray<T> = T extends unknown[] ? true : false;'].join('\n'),
      hints: [
        'You need a condition that is satisfied by every array and by nothing else.',
        '`unknown[]` is the array of anything; `readonly unknown[]` would also admit readonly arrays.',
        'Write `T extends unknown[] ? true : false`.',
      ],
    },
    {
      id: 'infer',
      title: 'infer pulls a type out of a pattern',
      concept: [
        '`infer` is pattern matching for types.',
        '',
        'Inside the condition of a conditional type, `infer U` means "match anything in this position, call it `U`, and let me use it in the true branch":',
        '',
        '```ts',
        'type UnwrapPromise<T> = T extends Promise<infer U> ? U : T;',
        '',
        'type A = UnwrapPromise<Promise<string>>;',
        'type B = UnwrapPromise<Promise<{ id: number }>>;',
        'type C = UnwrapPromise<number>;',
        '',
        'const a: A = \'ok\';',
        'const b: B = { id: 1 };',
        'const c: C = 42;',
        '```',
        '',
        'Look at that third case. A non-promise comes back untouched because the false branch is `T`, not `never` — a small decision that makes the difference between a type you can apply to anything and one that only works on promises.',
        '',
        '`infer` can appear almost anywhere a type can, and each position gives you a different tool:',
        '',
        '```ts',
        'type ReturnOf<F> = F extends (...args: never[]) => infer R ? R : never;',
        'type FirstArg<F> = F extends (first: infer A, ...rest: never[]) => unknown ? A : never;',
        'type Awaited1<T> = T extends Promise<infer U> ? U : T;',
        '',
        'declare function save(id: string, force: boolean): number;',
        '',
        'const r: ReturnOf<typeof save> = 1;',
        'const a2: FirstArg<typeof save> = \'u1\';',
        '```',
        '',
        'That is how `ReturnType` and `Parameters` from module 4 are built. There is no compiler magic in them at all.',
      ].join('\n'),
      brief: ['Unwrap a promise, leaving anything that is not a promise alone.'].join('\n'),
      debrief: [
        'Two refinements worth knowing about.',
        '',
        'You can constrain an `infer`, which lets you both match *and* filter in one step:',
        '',
        '```ts',
        'type NumericId<T> = T extends { id: infer U extends string } ? U : never;',
        '',
        'type A = NumericId<{ id: \'u1\' }>;',
        'type B = NumericId<{ id: number }>;',
        '',
        'const a: A = \'u1\';',
        'const b: B = undefined as never;',
        '```',
        '',
        '`B` falls to the false branch because `number` does not satisfy the constraint. Before this existed you had to nest a second conditional to achieve the same thing.',
        '',
        'The other is that multiple `infer`s in the same position are *unioned*, and in different positions are independent:',
        '',
        '```ts',
        'type Both<T> = T extends [infer A, infer B] ? { first: A; second: B } : never;',
        '',
        'type Pair = Both<[string, number]>;',
        '',
        'const p: Pair = { first: \'a\', second: 1 };',
        '```',
        '',
        'That tuple form is the gateway to the recursive type manipulation at the end of this module — matching `[infer First, ...infer Rest]` lets you walk a tuple one element at a time, which is how types like `Join` and `Path` are built.',
      ].join('\n'),
      starterCode: ['export type UnwrapPromise<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { UnwrapPromise } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<UnwrapPromise<Promise<string>>, string>>,',
        '  Expect<Equal<UnwrapPromise<Promise<{ id: number }>>, { id: number }>>,',
        '  Expect<Equal<UnwrapPromise<number>, number>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type UnwrapPromise<T> = T extends Promise<infer U> ? U : T;',
      ].join('\n'),
      hints: [
        'The shape you are matching is `Promise<something>`, and you want to name that something.',
        'Look at the third case: a non-promise must come back untouched, so the false branch is `T`, not `never`.',
        'Write `T extends Promise<infer U> ? U : T`.',
      ],
    },
    {
      id: 'infer-element',
      title: 'infer, on an array',
      concept: [
        'Same tool, different pattern: match an array and name its element type.',
        '',
        '```ts',
        'type ElementOf<T> = T extends readonly (infer U)[] ? U : never;',
        '',
        'type A = ElementOf<string[]>;',
        'type B = ElementOf<readonly [\'a\', \'b\']>;',
        'type C = ElementOf<number>;',
        '',
        'const a: A = \'x\';',
        'const b: B = \'a\';',
        'const c: C = undefined as never;',
        '```',
        '',
        'The `readonly` in the pattern matters more than it looks. A `readonly string[]` is *not* assignable to `string[]` — the mutable type promises methods the readonly one does not have — so a pattern written without it silently fails for anything produced by `as const`:',
        '',
        '```ts-bad',
        'type Strict<T> = T extends (infer U)[] ? U : never;',
        '',
        'const methods = [\'GET\', \'POST\'] as const;',
        'type Method = Strict<typeof methods>;',
        '',
        'const m: Method = \'GET\';',
        '```',
        '',
        '`Method` came out as `never`, so the assignment fails. The pattern matched nothing, and `never` is what a conditional gives you when the false branch says so — no error at the definition, just a type that quietly means "impossible" from then on.',
        '',
        'Matching `readonly` accepts both, since a mutable array satisfies a readonly pattern. When you write a pattern, prefer the more permissive form.',
      ].join('\n'),
      brief: ['Extract the element type, including from readonly tuples.'].join('\n'),
      debrief: [
        '`never` showing up where you expected a real type is the characteristic failure mode of conditional types, and it is quiet. Nothing errors at the definition — you only find out when something downstream refuses an assignment, often several types away from the cause.',
        '',
        'The habit that saves time: when a derived type comes out as `never`, check the *pattern* before you check anything else. Usually it matched nothing, and usually the reason is a modifier like `readonly`, an optional property, or a union member you forgot about.',
        '',
        'Since you now have both, it is worth noting there are two different ways to get an element type out of an array, and they are not interchangeable:',
        '',
        '```ts',
        'const methods = [\'GET\', \'POST\'] as const;',
        '',
        'type ViaIndex = (typeof methods)[number];',
        'type ViaInfer<T> = T extends readonly (infer U)[] ? U : never;',
        '',
        'const a: ViaIndex = \'GET\';',
        'const b: ViaInfer<typeof methods> = \'POST\';',
        '```',
        '',
        'Indexed access is simpler and is what you should reach for on a concrete array — it is the module 1 pattern. `infer` is what you need when you are writing a *generic* that has to work for any array it is handed, because you cannot index into a type parameter that has not been constrained to an array yet.',
      ].join('\n'),
      starterCode: ['export type ElementOf<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { ElementOf } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ElementOf<string[]>, string>>,',
        "  Expect<Equal<ElementOf<readonly ['a', 'b']>, 'a' | 'b'>>,",
        '  Expect<Equal<ElementOf<number>, never>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type ElementOf<T> = T extends readonly (infer U)[] ? U : never;',
      ].join('\n'),
      hints: [
        'Start from `T extends (infer U)[] ? U : never` and check which case fails.',
        'A `readonly` tuple is not assignable to a mutable array type, so the pattern has to allow readonly.',
        'Write `T extends readonly (infer U)[] ? U : never`.',
      ],
    },
    {
      id: 'distributive',
      title: 'Conditionals distribute over unions',
      concept: [
        'Here is the behaviour that surprises everyone exactly once and then becomes indispensable.',
        '',
        'When the checked type is a bare type parameter and you hand it a union, the conditional runs **once per member**, and the results are unioned back together:',
        '',
        '```ts',
        'type ToArray<T> = T extends unknown ? T[] : never;',
        '',
        'type A = ToArray<string | number>;',
        '',
        'const a: A = [\'x\'];',
        'const b: A = [1];',
        '```',
        '',
        '`A` is `string[] | number[]`, not `(string | number)[]`. The conditional distributed.',
        '',
        'That is what makes a one-line `Exclude` possible. Members that match become `never`, and `never` vanishes from a union:',
        '',
        '```ts',
        'type MyExclude<T, U> = T extends U ? never : T;',
        '',
        'type Letters = MyExclude<\'a\' | \'b\' | \'c\', \'a\'>;',
        '',
        'const l: Letters = \'b\';',
        '```',
        '',
        'Step through it: `\'a\'` matches and becomes `never`; `\'b\'` and `\'c\'` do not and stay themselves; the result is `never | \'b\' | \'c\'`, which collapses to `\'b\' | \'c\'`.',
        '',
        'The word *naked* is the technical condition — distribution happens only when the checked type is an unadorned type parameter, `T extends ...`, not `T[] extends ...` or `{ v: T } extends ...`.',
      ].join('\n'),
      brief: ['Write `Exclude` yourself: remove from `T` every member assignable to `U`.'].join('\n'),
      debrief: [
        'The essential companion knowledge is how to switch distribution **off**, because sometimes you want to ask about the union as a whole.',
        '',
        'Wrapping both sides in a one-element tuple does it — the checked type is no longer naked:',
        '',
        '```ts',
        'type Distributive<T> = T extends string ? \'yes\' : \'no\';',
        'type Whole<T> = [T] extends [string] ? \'yes\' : \'no\';',
        '',
        'type A = Distributive<string | number>;',
        'type B = Whole<string | number>;',
        '',
        'const a: A = \'yes\';',
        'const a2: A = \'no\';',
        'const b: B = \'no\';',
        '```',
        '',
        '`A` is `\'yes\' | \'no\'` — each member was tested separately, and the answer is both. `B` is just `\'no\'`, because `string | number` as a whole is not assignable to `string`. That is usually what you meant when you wrote the type.',
        '',
        'The same trick is how `IsNever` is written, since a naked conditional over `never` distributes over zero members and returns `never` rather than a boolean:',
        '',
        '```ts',
        'type IsNever<T> = [T] extends [never] ? true : false;',
        '',
        'const a: IsNever<never> = true;',
        'const b: IsNever<string> = false;',
        '```',
        '',
        '`never` being the empty union is consistent, and it means an unwrapped conditional over `never` never runs at all. That one catches everybody.',
      ].join('\n'),
      starterCode: ['export type MyExclude<T, U> = T;'].join('\n'),
      hiddenChecks: [
        "import type { MyExclude } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<MyExclude<'a' | 'b' | 'c', 'a'>, 'b' | 'c'>>,",
        '  Expect<Equal<MyExclude<string | number | boolean, boolean>, string | number>>,',
        '];',
      ].join('\n'),
      solution: ['export type MyExclude<T, U> = T extends U ? never : T;'].join('\n'),
      hints: [
        'Each member of `T` is tested separately. You want to drop the ones that match `U`.',
        'Dropping a member means evaluating to `never` for it.',
        'Write `T extends U ? never : T`.',
      ],
    },
    {
      id: 'template-literals',
      title: 'Types built out of strings',
      concept: [
        'A template literal type interpolates other types into a string type, using the same backtick syntax as a runtime template literal:',
        '',
        '```ts',
        'type EventName<T extends string> = `on${Capitalize<T>}`;',
        '',
        'type A = EventName<\'click\'>;',
        'type B = EventName<\'focus\'>;',
        '',
        'const a: A = \'onClick\';',
        'const b: B = \'onFocus\';',
        '```',
        '',
        'Four intrinsic helpers come with it: `Capitalize`, `Uncapitalize`, `Uppercase` and `Lowercase`. These are implemented in the compiler rather than in TypeScript, since string manipulation is not otherwise expressible.',
        '',
        'What makes this more than a party trick is that it lets you express a *naming convention* in the type system, and then get autocomplete for names that do not exist anywhere yet:',
        '',
        '```ts',
        'type Endpoint = `/api/${\'users\' | \'orders\'}/${string}`;',
        '',
        'const ok: Endpoint = \'/api/users/u1\';',
        '```',
        '',
        '```ts-bad',
        'type Endpoint = `/api/${\'users\' | \'orders\'}/${string}`;',
        '',
        'const bad: Endpoint = \'/api/invoices/i1\';',
        '```',
        '',
        'A typo in a route, an event name or a CSS custom property becomes a compile error instead of a silent no-op.',
      ].join('\n'),
      brief: ['Turn an event name into its handler name.'].join('\n'),
      debrief: [
        'Interpolating a union produces the **cross product**, and it grows faster than people expect:',
        '',
        '```ts',
        'type Size = \'sm\' | \'md\' | \'lg\';',
        'type Colour = \'red\' | \'blue\';',
        'type Class = `${Size}-${Colour}`;',
        '',
        'const c: Class = \'md-blue\';',
        '```',
        '',
        'Six members there — fine. But two unions of twenty each is four hundred, three is eight thousand, and the compiler materialises every one. TypeScript enforces a hard cap of 100,000 members on a union produced this way, and you can make an editor unusable well before reaching it. If you find yourself generating combinations from several unions, that is the moment to stop and use a plain `string` with a runtime check.',
        '',
        'The other half of template literal types is that `infer` can *parse* them:',
        '',
        '```ts',
        'type Split<S extends string> =',
        '  S extends `${infer Head}.${infer Tail}` ? [Head, ...Split<Tail>] : [S];',
        '',
        'type Parts = Split<\'user.address.city\'>;',
        '',
        'const p: Parts = [\'user\', \'address\', \'city\'];',
        '```',
        '',
        'That is a recursive descent parser written in the type system, and it is roughly how libraries type things like `t(\'user.address.city\')` or an ORM\'s `select(\'user.name\')` — string keys that are checked against a schema at compile time. It is also, as the last exercise in this module discusses, a good way to bring your editor to its knees if you are careless.',
      ].join('\n'),
      starterCode: ['export type EventName<T extends string> = string;'].join('\n'),
      hiddenChecks: [
        "import type { EventName } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<EventName<'click'>, 'onClick'>>,",
        "  Expect<Equal<EventName<'focus'>, 'onFocus'>>,",
        '];',
      ].join('\n'),
      solution: [
        'export type EventName<T extends string> = `on${Capitalize<T>}`;',
      ].join('\n'),
      hints: [
        'Use backticks, and `${...}` to interpolate the type parameter.',
        "`'onclick'` is not `'onClick'` — there is a built-in utility that fixes the case.",
        'Write ``on${Capitalize<T>}`` between backticks.',
      ],
    },
    {
      id: 'key-remapping',
      title: 'Rename keys while you map them',
      concept: [
        'A mapped type can rewrite the keys as it goes, using `as` in the key position. Combine that with a template literal and you can generate a whole derived API from one type:',
        '',
        '```ts',
        'type Getters<T> = {',
        '  [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K];',
        '};',
        '',
        'type UserGetters = Getters<{ name: string; age: number }>;',
        '',
        'const g: UserGetters = {',
        '  getName: () => \'ada\',',
        '  getAge: () => 36,',
        '};',
        '```',
        '',
        'The `string & K` is the detail everyone hits first. `keyof T` can include `symbol` and `number`, and `Capitalize` only accepts strings — intersecting with `string` filters the union down to the keys that qualify:',
        '',
        '```ts-bad',
        'type Broken<T> = {',
        '  [K in keyof T as `get${Capitalize<K>}`]: () => T[K];',
        '};',
        '```',
        '',
        'The other half of key remapping is that mapping a key to `never` **removes** it. That is not a special case; `never` disappearing from a union is the same rule you met in the distribution exercise, applied to keys.',
      ].join('\n'),
      brief: ['Generate the getter interface for a type: every property becomes a `getX()` method.'].join('\n'),
      debrief: [
        'Remapping to `never` is how `Omit` is actually implemented, and it lets you filter properties by anything you can express as a conditional — including their *type*, which nothing else in the language can do:',
        '',
        '```ts',
        'type MethodsOf<T> = {',
        '  [K in keyof T as T[K] extends (...args: never[]) => unknown ? K : never]: T[K];',
        '};',
        '',
        'type Api = MethodsOf<{',
        '  id: string;',
        '  save: () => void;',
        '  load: (id: string) => string;',
        '}>;',
        '',
        'const api: Api = {',
        '  save: () => {},',
        '  load: (id) => id,',
        '};',
        '```',
        '',
        '`id` was dropped because its key mapped to `never`. You now have "every method of this type, and nothing else", derived automatically — the shape of type you would write to build a proxy, a mock, or an RPC client.',
        '',
        'Worth pausing on how much of the language that one type used: a mapped type, `keyof`, indexed access, key remapping, a conditional type, and `never` as a filter. Five modules of material in four lines.',
        '',
        'That is genuinely how the useful types in real codebases are written. Not one clever feature, but a handful of small ones that compose.',
      ].join('\n'),
      starterCode: ['export type Getters<T> = T;'].join('\n'),
      hiddenChecks: [
        "import type { Getters } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Getters<{ name: string; age: number }>,',
        '      { getName: () => string; getAge: () => number }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type Getters<T> = {',
        '  [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K];',
        '};',
      ].join('\n'),
      hints: [
        'The key clause becomes `[K in keyof T as NewKey]`.',
        '`keyof T` can include symbols, so `Capitalize<K>` alone will not type-check — intersect with `string` first.',
        'Write ``[K in keyof T as `get${Capitalize<string & K>}`]: () => T[K]``.',
      ],
    },
    {
      id: 'recursive-types',
      title: 'A type that calls itself',
      concept: [
        'Type aliases can refer to themselves, which is what turns the shallow utilities of module 4 into deep ones.',
        '',
        '`Readonly<T>` only marks the top level. Applying the type recursively goes all the way down:',
        '',
        '```ts',
        'type DeepReadonly<T> = T extends object',
        '  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }',
        '  : T;',
        '',
        'type Config = DeepReadonly<{ a: string; nested: { b: number } }>;',
        '',
        'const c: Config = { a: \'x\', nested: { b: 1 } };',
        '```',
        '',
        '```ts-bad',
        'type DeepReadonly<T> = T extends object',
        '  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }',
        '  : T;',
        '',
        'const c: DeepReadonly<{ nested: { b: number } }> = { nested: { b: 1 } };',
        'c.nested.b = 2;',
        '```',
        '',
        'The base case is what makes it terminate. Without the `T extends object` guard you would try to map over `string`, and the recursion would have nothing to stop it.',
        '',
        'That guard is also less precise than it looks — functions and arrays are objects too, so a thorough `DeepReadonly` usually handles them separately. It is worth knowing that the four-line version you just wrote is the *teaching* version, not the library-grade one.',
      ].join('\n'),
      brief: ['Make `readonly` apply all the way down, leaving non-objects alone.'].join('\n'),
      debrief: [
        'Recursion in the type system has a budget, and you can exhaust it. TypeScript stops at roughly 50 levels of instantiation depth and reports "Type instantiation is excessively deep and possibly infinite" — usually the first time you write a recursive type over a long tuple.',
        '',
        'Since TypeScript 4.5 there is *tail recursion elimination* for conditional types: if the recursive call is the entire result of a branch, the compiler unrolls it iteratively and the limit rises to around 1000. Which means this form is cheap:',
        '',
        '```ts',
        'type Join<T extends readonly string[], Acc extends string = \'\'> =',
        '  T extends readonly [infer H extends string, ...infer R extends readonly string[]]',
        '    ? Join<R, `${Acc}${Acc extends \'\' ? \'\' : \',\'}${H}`>',
        '    : Acc;',
        '',
        'type S = Join<[\'a\', \'b\', \'c\']>;',
        '',
        'const s: S = \'a,b,c\';',
        '```',
        '',
        'The accumulator parameter is the giveaway. That is the same trick you would use to make a recursive function tail-call optimised in a language that supports it, and it is deliberate — the compiler team added the optimisation precisely so this style would work.',
        '',
        'The practical warning: type-level recursion is not free, and unlike slow runtime code, slow types make *your editor* slow. If autocomplete starts lagging in a file, a recursive type applied to something large is a prime suspect. `tsc --generateTrace` will tell you which one.',
        '',
        'That is the end of module 5, and the end of the type-level programming. From here it is applying all of it: declaration files, backend patterns, and React.',
      ].join('\n'),
      starterCode: ['export type DeepReadonly<T> = Readonly<T>;'].join('\n'),
      hiddenChecks: [
        "import type { DeepReadonly } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      DeepReadonly<{ a: string; nested: { b: number } }>,',
        '      { readonly a: string; readonly nested: { readonly b: number } }',
        '    >',
        '  >,',
        '  Expect<Equal<DeepReadonly<string>, string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type DeepReadonly<T> = T extends object',
        '  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }',
        '  : T;',
      ].join('\n'),
      hints: [
        'Guard with a conditional first: only objects get mapped, everything else passes through.',
        'Inside the mapped type, apply `DeepReadonly` to the property type as well as adding `readonly`.',
        'Write `T extends object ? { readonly [K in keyof T]: DeepReadonly<T[K]> } : T`.',
      ],
    },
  ],
};
