import type { Module } from '../types';

export const declarationFiles: Module = {
  id: 'declaration-files',
  title: 'Declaration Files & Ambient Types',
  blurb:
    'What to do when the types do not exist: describing an untyped package, augmenting one that already has types, and adding to the global scope.',
  status: 'ready',
  exercises: [
    {
      id: 'declare-a-module',
      title: 'Type an untyped package',
      concept: [
        'Sooner or later you install something with no types and no `@types/` package, and every import from it is `any`.',
        '',
        'An *ambient module declaration* fixes it without touching the package. You describe its shape in a `.d.ts` file and the compiler believes you:',
        '',
        '```ts',
        'declare module \'legacy-logger\' {',
        '  export type LogLevel = \'info\' | \'error\';',
        '  export function createLogger(name: string): {',
        '    log: (level: LogLevel, message: string) => void;',
        '  };',
        '}',
        '```',
        '',
        'There is one rule that decides whether this works, and it catches everyone.',
        '',
        'A file with no top-level `import` or `export` is a **script**, and its declarations are global. A file with either is a **module**, and its declarations are scoped to itself. `declare module \'x\'` only *declares a new module* inside a script. Inside a module it means something different — augmenting one that already exists — so it fails on a package the compiler has never heard of:',
        '',
        '```ts-bad',
        'export {};',
        '',
        'declare module \'legacy-logger\' {',
        '  export function createLogger(name: string): void;',
        '}',
        '```',
        '',
        'That is why this exercise is a `.d.ts` with nothing exported at the top level. Add an `export` anywhere outside the braces and it stops working.',
      ].join('\n'),
      brief: ['Declare `legacy-logger` so its two exports have real types.'].join('\n'),
      debrief: [
        'In a real project these live in a file the compiler is told to include — typically `types/*.d.ts` covered by the `include` array in `tsconfig.json`, or a `typeRoots` entry. They do not need to be imported; being in the program is enough.',
        '',
        'There is a shorthand worth recognising and mostly avoiding:',
        '',
        '```ts',
        'declare module \'legacy-logger\';',
        '```',
        '',
        'No body. That silences the error and types every export as `any` — the whole module becomes an opaque hole. It is a reasonable five-second unblock and a bad thing to leave in a repository, because it looks like the problem was solved.',
        '',
        'Two things worth doing instead when you hit this for real. Check whether types already exist — a great many packages ship them now, and `npm i -D @types/whatever` covers most of the rest. And if you do end up writing declarations for a popular package, consider contributing them to DefinitelyTyped; you have already done the work.',
        '',
        'One related flag: `skipLibCheck`, which is on in this project and in most templates. It stops the compiler type-checking inside `.d.ts` files, which makes builds substantially faster and papers over conflicts between dependencies\' type definitions. The trade is that errors *in your own* declaration files go unreported, so a mistake here is quieter than you would like.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ["declare module 'legacy-logger' {}"].join('\n'),
      hiddenChecks: [
        "import type { createLogger, LogLevel } from 'legacy-logger';",
        'type _cases = [',
        "  Expect<Equal<LogLevel, 'info' | 'error'>>,",
        '  Expect<',
        '    Equal<',
        '      typeof createLogger,',
        '      (name: string) => { log: (level: LogLevel, message: string) => void }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'legacy-logger' {",
        "  export type LogLevel = 'info' | 'error';",
        '  export function createLogger(name: string): {',
        '    log: (level: LogLevel, message: string) => void;',
        '  };',
        '}',
      ].join('\n'),
      hints: [
        'Everything goes inside the braces, and each thing the package provides needs `export`.',
        'You need one type and one function: `LogLevel` and `createLogger`.',
        "Declare `export type LogLevel = 'info' | 'error';` and `export function createLogger(name: string): { log: (level: LogLevel, message: string) => void };`",
      ],
    },
    {
      id: 'wildcard-modules',
      title: 'Declare a whole class of imports',
      concept: [
        'Bundlers let you import things that are not JavaScript — an image, a stylesheet, an SVG — and TypeScript has no idea what those are.',
        '',
        'A module name in a declaration can contain a `*`, which matches any path ending that way. One declaration then covers every such import in the entire project:',
        '',
        '```ts',
        'declare module \'*.svg\' {',
        '  const url: string;',
        '  export default url;',
        '}',
        '```',
        '',
        'The body describes what the bundler actually gives you at runtime. For an asset under Vite that is a URL string as the default export; for a CSS module it would be an object of class names:',
        '',
        '```ts',
        'declare module \'*.module.css\' {',
        '  const classes: Record<string, string>;',
        '  export default classes;',
        '}',
        '```',
        '',
        'Getting the body right matters more than getting it to compile. The declaration is a promise about runtime behaviour that nothing verifies — if your bundler is configured to inline SVGs as React components rather than URLs, the declaration above is a lie that will typecheck perfectly.',
      ].join('\n'),
      brief: ['Declare the pattern so any `.svg` import is a URL string.'].join('\n'),
      debrief: [
        'When several wildcard patterns could match, TypeScript picks the **most specific** one — the one with the longest matching prefix before the `*`. So these coexist correctly:',
        '',
        '```ts',
        'declare module \'*.css\' {',
        '  const url: string;',
        '  export default url;',
        '}',
        '',
        'declare module \'*.module.css\' {',
        '  const classes: Record<string, string>;',
        '  export default classes;',
        '}',
        '```',
        '',
        'An import of `styles.module.css` gets the object; `reset.css` gets the string.',
        '',
        'In practice you often do not need to write these at all. Vite ships them: adding `"types": ["vite/client"]` to your `tsconfig.json` brings in declarations for every asset type it handles, and this project relies on exactly that for the raw text imports the grading engine uses. Next.js, Parcel and the rest do the same.',
        '',
        'So the useful skill is recognising the error — "Cannot find module \'./logo.svg\' or its corresponding type declarations" — and knowing there are two fixes: reach for your bundler\'s client types first, and write the wildcard yourself only for something genuinely custom.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ['// Declare the module pattern here.'].join('\n'),
      hiddenChecks: [
        "import iconUrl from './icons/warning.svg';",
        "import otherUrl from './logo.svg';",
        'type _cases = [',
        '  Expect<Equal<typeof iconUrl, string>>,',
        '  Expect<Equal<typeof otherUrl, string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module '*.svg' {",
        '  const url: string;',
        '  export default url;',
        '}',
      ].join('\n'),
      hints: [
        'The module name can contain a `*`, which matches any path ending that way.',
        'The imports use a default import, so the declaration needs a default export.',
        "Write `declare module '*.svg' { const url: string; export default url; }`",
      ],
    },
    {
      id: 'declare-global',
      title: 'Type your environment variables',
      concept: [
        '`process.env.ANYTHING` is `string | undefined`, because the index signature says any key might be missing. That is honest, and it is tedious when the app refuses to boot without `DATABASE_URL`.',
        '',
        '`declare global` reaches out of the current module and adds to the global scope. Because interfaces *merge*, naming one that already exists adds to it rather than replacing it:',
        '',
        '```ts',
        'declare global {',
        '  interface ProcessEnv {',
        '    DATABASE_URL: string;',
        '  }',
        '}',
        '',
        'export {};',
        '```',
        '',
        'Note the `export {}` at the bottom. `declare global` is only legal inside a module — a file that is already global has no "out" to reach into — and that empty export is what makes the file one. It is the mirror image of the rule from the first exercise in this module, and the two catch people in opposite directions.',
        '',
        'Merging is why you only list the new property. You are contributing to `ProcessEnv`, not redefining it, so everything already there stays.',
      ].join('\n'),
      brief: ['Make `DATABASE_URL` a guaranteed string, leaving unknown keys as they are.'].join('\n'),
      debrief: [
        'This works, and it is worth being uneasy about it.',
        '',
        'You have not made the variable exist. You have told the compiler to stop asking. If `DATABASE_URL` is missing at runtime, the value is `undefined` and its type says `string` — precisely the situation `strictNullChecks` exists to prevent, now written into the type system on purpose.',
        '',
        'It is also *global*. Every file in the project now believes it, including the ones running in tests where the variable genuinely is not set.',
        '',
        'The alternative is to validate once at startup and pass a typed object around:',
        '',
        '```ts',
        'interface Config {',
        '  databaseUrl: string;',
        '}',
        '',
        'function loadConfig(): Config {',
        '  const databaseUrl = process.env.DATABASE_URL;',
        '  if (databaseUrl === undefined) {',
        '    throw new Error(\'DATABASE_URL is required\');',
        '  }',
        '  return { databaseUrl };',
        '}',
        '```',
        '',
        'Now the type is `string` because it was *checked*, the failure is one clear error at boot rather than a mystery `undefined` an hour in, and nothing global was touched. Module 7 does this with a schema so the type is derived rather than hand-written.',
        '',
        'Global augmentation earns its place for things that genuinely are global and genuinely do exist — a value your bundler injects at build time, a polyfill you install at startup. For configuration, prefer parsing.',
      ].join('\n'),
      starterCode: [
        '// Augment the global ProcessEnv here.',
        '',
        'export {};',
      ].join('\n'),
      hiddenChecks: [
        'type _cases = [',
        '  Expect<Equal<typeof process.env.DATABASE_URL, string>>,',
        '  Expect<Equal<typeof process.env.SOMETHING_ELSE, string | undefined>>,',
        '];',
      ].join('\n'),
      solution: [
        'declare global {',
        '  interface ProcessEnv {',
        '    DATABASE_URL: string;',
        '  }',
        '}',
        '',
        'export {};',
      ].join('\n'),
      hints: [
        'The interface you are merging into is called `ProcessEnv`.',
        'Redeclaring an interface that already exists merges into it rather than replacing it — you only list the new property.',
        'Write `declare global { interface ProcessEnv { DATABASE_URL: string } }`.',
      ],
    },
    {
      id: 'module-augmentation',
      title: 'Add to a module that already has types',
      concept: [
        'The mirror image of declaring a module: adding to one that already has types.',
        '',
        'In a file that *is* a module, `declare module \'x\'` merges into the existing declaration rather than replacing it:',
        '',
        '```ts',
        'declare module \'node:path\' {',
        '  export function isAbsolutePath(p: string): boolean;',
        '}',
        '',
        'export {};',
        '```',
        '',
        'Everything the module already exported still works; yours is added alongside. This is how plugin ecosystems type themselves — the library ships a base type, and each plugin augments it with whatever it attaches at runtime.',
        '',
        'The canonical example is an Express request:',
        '',
        '```ts',
        'declare module \'node:path\' {',
        '  interface PathExtras {',
        '    projectRoot: string;',
        '  }',
        '}',
        '',
        'export {};',
        '```',
        '',
        'Same mechanism, and the same caveat as `declare global`: you are describing something a piece of middleware does at runtime. If the middleware is not installed, the type is still there and still confident.',
        '',
        'Augmentation can only **add**. You cannot change the type of an existing export, and you cannot augment a module\'s default export — both produce errors rather than silently winning.',
      ].join('\n'),
      brief: [
        'Add a function to `node:path` without disturbing what it already exports.',
        '',
        'The check on `join` will tell you if you replaced it instead of augmenting it.',
      ].join('\n'),
      debrief: [
        'The `export {}` in this exercise and its absence in the first one are the whole lesson of this module, so it is worth stating the rule once, plainly:',
        '',
        '- **Script** (no top-level import/export): `declare module \'x\'` *creates* module `x`.',
        '- **Module** (has an import or export): `declare module \'x\'` *augments* the existing module `x`, and errors if there is none.',
        '',
        'Same syntax, opposite meanings, decided by something that is not on the line you are looking at. When an augmentation mysteriously reports "Cannot find module", check whether the file is a module — and when a declaration mysteriously has no effect, check whether it is a script.',
        '',
        'One practical limit: augmenting a module that has no types at all does not work, because there is nothing to merge into. You need the full ambient declaration from exercise 1 instead. And a module can only be augmented from a file that is itself part of the program, which is why these declarations usually sit in a `types/` folder covered by `include` rather than somewhere they are imported from.',
        '',
        'For a real-world Express setup, the augmentation for `req.user` is roughly four lines and is one of the most-copied snippets in TypeScript. You now know exactly why each line is there.',
      ].join('\n'),
      starterCode: [
        '// Augment node:path here.',
        '',
        'export {};',
      ].join('\n'),
      hiddenChecks: [
        "import type { isAbsolutePath, join } from 'node:path';",
        'type _cases = [',
        '  Expect<Equal<typeof isAbsolutePath, (p: string) => boolean>>,',
        '  Expect<Equal<typeof join, (...paths: string[]) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'node:path' {",
        '  export function isAbsolutePath(p: string): boolean;',
        '}',
        '',
        'export {};',
      ].join('\n'),
      hints: [
        'The syntax is identical to declaring a module — the difference is that this file is a module, so it merges.',
        'You only declare the new function; the existing exports come along automatically.',
        "Write `declare module 'node:path' { export function isAbsolutePath(p: string): boolean; }`",
      ],
    },
    {
      id: 'overloads',
      title: 'Overloads, for when one signature will not do',
      concept: [
        'A single signature taking `string | number` and returning `string | number` throws away the connection between them. Pass a string and the compiler still thinks you might get a number back:',
        '',
        '```ts-bad',
        'function double(value: string | number): string | number {',
        '  return typeof value === \'string\' ? value + value : value * 2;',
        '}',
        '',
        'const doubled: string = double(\'x\');',
        '```',
        '',
        'Overload signatures state each valid combination separately. They sit above the implementation and have no body:',
        '',
        '```ts',
        'function double(value: number): number;',
        'function double(value: string): string;',
        'function double(value: string | number): string | number {',
        '  return typeof value === \'string\' ? value + value : value * 2;',
        '}',
        '',
        'const a: number = double(2);',
        'const b: string = double(\'x\');',
        '```',
        '',
        'The last signature — the one with the body — is the *implementation signature*. It is not callable from outside; it exists only to be wide enough for the body to type-check against. That is why `double(true)` is an error even though `boolean` would satisfy nothing in particular.',
        '',
        'A generic would also work for some of these. Overloads earn their keep when the argument *shapes* differ, not merely their types: different arities, or a callback in one form and a promise in the other.',
      ].join('\n'),
      brief: ['Give `double` two callable signatures without changing the implementation.'].join('\n'),
      debrief: [
        'Two things about overloads that are genuinely surprising.',
        '',
        '**Resolution picks the first match, not the best one.** Order is significant, and a broad signature placed first will shadow everything after it:',
        '',
        '```ts',
        'function get(id: string | number): string | number;',
        'function get(id: string): string;',
        'function get(id: string | number): string | number {',
        '  return id;',
        '}',
        '',
        'const value = get(\'u1\');',
        '```',
        '',
        '`value` is `string | number`, because the first signature matched and the search stopped. Swap the two and it is `string`. Always order overloads from most specific to least.',
        '',
        '**The implementation signature is checked loosely.** TypeScript verifies that each overload is broadly compatible with it, and the check is deliberately permissive — this is one of the acknowledged unsound corners of the language. You can write overloads the implementation does not actually honour and the compiler will accept them, so the guarantee here rests on you rather than on the checker.',
        '',
        'Which suggests the practical rule: reach for a generic or a discriminated union first, since both are checked properly. Use overloads when neither can express the shape — and keep the implementation obviously correct, because nothing else is going to.',
      ].join('\n'),
      starterCode: [
        'export function double(value: string | number): string | number {',
        "  return typeof value === 'string' ? value + value : value * 2;",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import { double } from './exercise';",
        'const a = double(2);',
        "const b = double('x');",
        'type _cases = [Expect<Equal<typeof a, number>>, Expect<Equal<typeof b, string>>];',
      ].join('\n'),
      solution: [
        'export function double(value: number): number;',
        'export function double(value: string): string;',
        'export function double(value: string | number): string | number {',
        "  return typeof value === 'string' ? value + value : value * 2;",
        '}',
      ].join('\n'),
      hints: [
        'Overload signatures go above the implementation and have no body — just a semicolon.',
        'Write one for the number case and one for the string case; keep the existing wide signature as the implementation.',
        'Add `export function double(value: number): number;` and `export function double(value: string): string;` above the current declaration.',
      ],
    },
    {
      id: 'default-export-module',
      title: 'A package that exports one function',
      concept: [
        'Plenty of older packages do `module.exports = fn`. The entire module *is* a function, with no named exports at all.',
        '',
        'In a declaration you express that as a default export, which is what a bundler\'s interop gives you at the call site:',
        '',
        '```ts',
        'declare module \'slugify\' {',
        '  export default function slugify(input: string, separator?: string): string;',
        '}',
        '```',
        '',
        'The optional `separator` gets a `?`, exactly as it would in any other signature — a declaration file is ordinary TypeScript with the bodies removed.',
        '',
        'There is an older syntax you will meet in existing `.d.ts` files for the same situation:',
        '',
        '```ts',
        'declare module \'slugify\' {',
        '  function slugify(input: string, separator?: string): string;',
        '  export = slugify;',
        '}',
        '```',
        '',
        '`export =` is TypeScript\'s own way of modelling `module.exports =` precisely, from before ES modules settled. It is stricter: importing it needs either `esModuleInterop` enabled — which it is here, and in essentially every modern setup — or the old `import slugify = require(\'slugify\')` form.',
        '',
        'For new declarations, prefer `export default`. Recognise `export =` when you read it.',
      ].join('\n'),
      brief: ['Type a package whose entire export is one function.'].join('\n'),
      debrief: [
        '`esModuleInterop` is the flag that makes `import slugify from \'slugify\'` work against a CommonJS module that never had a `default` in the first place. It emits a small helper that checks for `__esModule` and wraps the value if it is absent.',
        '',
        'It is on by default in every modern template, and turning it off in an existing project is a large and unrewarding day. Worth knowing it exists, mostly so the error message means something when you meet a project without it.',
        '',
        'That closes out the module, and the through-line is worth naming. Everything here has been about the boundary between typed and untyped code — packages without types, files your bundler invents, globals injected at build time, functions whose real signature the type system cannot see.',
        '',
        'Every technique in it shares one property: **the compiler stops checking and starts believing you.** An ambient declaration, a global augmentation, an overload set — none of them are verified against anything. They are assertions.',
        '',
        'That makes them the highest-leverage and highest-risk types in a codebase. Write them narrowly, keep them close to the thing they describe, and treat a wrong one as seriously as you would a wrong cast — because that is exactly what it is.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ["declare module 'slugify' {}"].join('\n'),
      hiddenChecks: [
        "import slugify from 'slugify';",
        'type _cases = [',
        '  Expect<Equal<typeof slugify, (input: string, separator?: string) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'slugify' {",
        '  export default function slugify(input: string, separator?: string): string;',
        '}',
      ].join('\n'),
      hints: [
        'The check uses a default import, so the module needs a default export.',
        'The separator is optional — mark it with `?`.',
        "Write `export default function slugify(input: string, separator?: string): string;` inside the module block.",
      ],
    },
  ],
};
