import type { Module } from '../types';

export const declarationFiles: Module = {
  id: 'declaration-files',
  title: 'Declaration Files & Ambient Types',
  blurb:
    'What to do when the types do not exist: describing an untyped package, augmenting one that already has types, and adding to the global scope.',
  status: 'ready',
  exercises: [
    {
      id: 'declare-a-module',
      title: 'Type an untyped package',
      brief: [
        'Sooner or later you `npm install` something with no types and no `@types/` package,',
        'and every import is `any`.',
        '',
        'The fix is an ambient module declaration: a `.d.ts` file that tells TypeScript what',
        'the package exports, without touching the package itself.',
        '',
        'This exercise is a `.d.ts` *script* — no imports, no exports at the top level. That',
        'distinction matters: in a file that is already a module, `declare module \'x\'` means',
        '"augment the existing module x". Only in a script does it declare a new one.',
        '',
        'Declare `legacy-logger` so its two exports have real types.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ["declare module 'legacy-logger' {}"].join('\n'),
      hiddenChecks: [
        "import type { createLogger, LogLevel } from 'legacy-logger';",
        'type _cases = [',
        "  Expect<Equal<LogLevel, 'info' | 'error'>>,",
        '  Expect<',
        '    Equal<',
        '      typeof createLogger,',
        '      (name: string) => { log: (level: LogLevel, message: string) => void }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'legacy-logger' {",
        "  export type LogLevel = 'info' | 'error';",
        '  export function createLogger(name: string): {',
        '    log: (level: LogLevel, message: string) => void;',
        '  };',
        '}',
      ].join('\n'),
      hints: [
        'Everything goes inside the braces, and each thing the package provides needs `export`.',
        'You need one type and one function: `LogLevel` and `createLogger`.',
        "Declare `export type LogLevel = 'info' | 'error';` and `export function createLogger(name: string): { log: (level: LogLevel, message: string) => void };`",
      ],
    },
    {
      id: 'wildcard-modules',
      title: 'Declare a whole class of imports',
      brief: [
        'Bundlers let you import assets — `import icon from \'./icon.svg\'` — and TypeScript has',
        'no idea what those are.',
        '',
        'A wildcard module declaration covers every path matching a pattern at once, which is',
        'why one line in a `.d.ts` fixes every asset import in a project.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ['// Declare the module pattern here.'].join('\n'),
      hiddenChecks: [
        "import iconUrl from './icons/warning.svg';",
        "import otherUrl from './logo.svg';",
        'type _cases = [',
        '  Expect<Equal<typeof iconUrl, string>>,',
        '  Expect<Equal<typeof otherUrl, string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module '*.svg' {",
        '  const url: string;',
        '  export default url;',
        '}',
      ].join('\n'),
      hints: [
        'The module name can contain a `*`, which matches any path ending that way.',
        'The imports use a default import, so the declaration needs a default export.',
        "Write `declare module '*.svg' { const url: string; export default url; }`",
      ],
    },
    {
      id: 'declare-global',
      title: 'Type your environment variables',
      brief: [
        '`process.env.ANYTHING` is `string | undefined`, because the index signature says every',
        'key might be missing. That is honest, and it is also tedious when you know the app',
        'refuses to boot without `DATABASE_URL`.',
        '',
        '`declare global` reaches out of the current module and augments the global scope.',
        'Interfaces merge, so adding a property to `ProcessEnv` refines it everywhere.',
        '',
        'Note the `export {}` at the bottom of the starter: `declare global` is only legal',
        'inside a module, and that empty export is what makes this file one.',
      ].join('\n'),
      starterCode: [
        '// Augment the global ProcessEnv here.',
        '',
        'export {};',
      ].join('\n'),
      hiddenChecks: [
        'type _cases = [',
        '  Expect<Equal<typeof process.env.DATABASE_URL, string>>,',
        '  Expect<Equal<typeof process.env.SOMETHING_ELSE, string | undefined>>,',
        '];',
      ].join('\n'),
      solution: [
        'declare global {',
        '  interface ProcessEnv {',
        '    DATABASE_URL: string;',
        '  }',
        '}',
        '',
        'export {};',
      ].join('\n'),
      hints: [
        'The interface you are merging into is called `ProcessEnv`.',
        'Redeclaring an interface that already exists merges into it rather than replacing it — you only list the new property.',
        'Write `declare global { interface ProcessEnv { DATABASE_URL: string } }`.',
      ],
    },
    {
      id: 'module-augmentation',
      title: 'Add to a module that already has types',
      brief: [
        'Plugins do this constantly: a library ships types, and something else bolts a property',
        'onto them at runtime.',
        '',
        'In a file that *is* a module, `declare module \'node:path\'` augments the existing',
        'declaration rather than replacing it — so the original exports keep working and yours',
        'is added alongside.',
        '',
        'Check the `join` assertion below: if you accidentally replace the module instead of',
        'augmenting it, that one fails and tells you.',
      ].join('\n'),
      starterCode: [
        '// Augment node:path here.',
        '',
        'export {};',
      ].join('\n'),
      hiddenChecks: [
        "import type { isAbsolutePath, join } from 'node:path';",
        'type _cases = [',
        '  Expect<Equal<typeof isAbsolutePath, (p: string) => boolean>>,',
        '  Expect<Equal<typeof join, (...paths: string[]) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'node:path' {",
        '  export function isAbsolutePath(p: string): boolean;',
        '}',
        '',
        'export {};',
      ].join('\n'),
      hints: [
        'The syntax is identical to declaring a module — the difference is that this file is a module, so it merges.',
        'You only declare the new function; the existing exports come along automatically.',
        "Write `declare module 'node:path' { export function isAbsolutePath(p: string): boolean; }`",
      ],
    },
    {
      id: 'overloads',
      title: 'Overloads, for when one signature will not do',
      brief: [
        'A single signature taking `string | number` and returning `string | number` loses the',
        'connection between them: pass a string, and the compiler still thinks you might get a',
        'number back.',
        '',
        'Overloads state each valid combination separately. The implementation signature below',
        'them is not callable from outside — it exists only to satisfy the body.',
        '',
        'A generic would also work here; overloads earn their keep when the argument *shapes*',
        'differ, not just their types.',
      ].join('\n'),
      starterCode: [
        'export function double(value: string | number): string | number {',
        "  return typeof value === 'string' ? value + value : value * 2;",
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import { double } from './exercise';",
        'const a = double(2);',
        "const b = double('x');",
        'type _cases = [Expect<Equal<typeof a, number>>, Expect<Equal<typeof b, string>>];',
      ].join('\n'),
      solution: [
        'export function double(value: number): number;',
        'export function double(value: string): string;',
        'export function double(value: string | number): string | number {',
        "  return typeof value === 'string' ? value + value : value * 2;",
        '}',
      ].join('\n'),
      hints: [
        'Overload signatures go above the implementation and have no body — just a semicolon.',
        'Write one for the number case and one for the string case; keep the existing wide signature as the implementation.',
        'Add `export function double(value: number): number;` and `export function double(value: string): string;` above the current declaration.',
      ],
    },
    {
      id: 'default-export-module',
      title: 'A package that exports one function',
      brief: [
        'Plenty of older packages do `module.exports = fn` — the entire module *is* a function.',
        '',
        'In a declaration you express that with a default export, which is what a bundler’s',
        'interop will give you at the call site.',
      ].join('\n'),
      fileName: 'exercise.d.ts',
      starterCode: ["declare module 'slugify' {}"].join('\n'),
      hiddenChecks: [
        "import slugify from 'slugify';",
        'type _cases = [',
        '  Expect<Equal<typeof slugify, (input: string, separator?: string) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        "declare module 'slugify' {",
        '  export default function slugify(input: string, separator?: string): string;',
        '}',
      ].join('\n'),
      hints: [
        'The check uses a default import, so the module needs a default export.',
        'The separator is optional — mark it with `?`.',
        "Write `export default function slugify(input: string, separator?: string): string;` inside the module block.",
      ],
    },
  ],
};
