import type { Module } from '../types';

export const backendPatterns: Module = {
  id: 'backend-patterns',
  title: 'Backend Patterns',
  blurb:
    'The handful of patterns that carry most of the weight in real Node services: schemas as the source of truth, results instead of exceptions, and identifiers that cannot be mixed up.',
  status: 'ready',
  exercises: [
    {
      id: 'schema-inference',
      title: 'One schema, one type',
      brief: [
        'The oldest bug in a typed backend: an `interface User` and a runtime validator that',
        'have drifted apart, so the compiler is confidently describing a shape the server never',
        'actually produces.',
        '',
        'The fix is to stop writing both. Define the validator, and derive the type from it with',
        '`z.infer<typeof schema>` — now they cannot disagree, because there is only one of them.',
        '',
        '(This exercise runs against a small stub of zod covering `string`, `number`, `boolean`,',
        '`object`, `array` and `optional`. The API matches the real thing.)',
      ].join('\n'),
      starterCode: [
        "import { z } from 'zod';",
        '',
        'export const userSchema = z.object({',
        '  id: z.string(),',
        '  email: z.string().email(),',
        '  loginCount: z.number(),',
        '});',
        '',
        'export interface User {',
        '  id: string;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<User, { id: string; email: string; loginCount: number }>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { z } from 'zod';",
        '',
        'export const userSchema = z.object({',
        '  id: z.string(),',
        '  email: z.string().email(),',
        '  loginCount: z.number(),',
        '});',
        '',
        'export type User = z.infer<typeof userSchema>;',
      ].join('\n'),
      hints: [
        'Replace the interface entirely — it should be a type alias derived from the schema.',
        '`userSchema` is a value, so you need `typeof` to use it in a type position.',
        'Write `export type User = z.infer<typeof userSchema>;`',
      ],
    },
    {
      id: 'result-in-practice',
      title: 'Return failures instead of throwing them',
      brief: [
        'A thrown error is invisible to the type system: nothing in a function’s signature says',
        'it can fail, and nothing forces the caller to care.',
        '',
        'Returning a `Result` makes failure part of the type. The caller cannot reach `.value`',
        'without first checking `ok`, because the discriminated union will not let them.',
        '',
        'Implement the parse so that both branches type-check.',
      ].join('\n'),
      starterCode: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'export function parsePort(raw: string): Result<number, string> {',
        '  const parsed = Number(raw);',
        '  return { ok: true, value: parsed };',
        '}',
        '',
        'export function describe(result: Result<number, string>): string {',
        '  return result.value.toFixed(0);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { describe, parsePort, Result } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof parsePort, (raw: string) => Result<number, string>>>,',
        '  Expect<Equal<typeof describe, (result: Result<number, string>) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'export function parsePort(raw: string): Result<number, string> {',
        '  const parsed = Number(raw);',
        '  if (Number.isNaN(parsed)) {',
        "    return { ok: false, error: 'not a number' };",
        '  }',
        '  return { ok: true, value: parsed };',
        '}',
        '',
        'export function describe(result: Result<number, string>): string {',
        '  if (result.ok) {',
        '    return result.value.toFixed(0);',
        '  }',
        '  return result.error;',
        '}',
      ].join('\n'),
      hints: [
        '`describe` is the one failing: `result.value` does not exist on the error branch.',
        'Narrow on `result.ok` first — it is the discriminant.',
        'Guard with `if (result.ok) { return result.value.toFixed(0); }` then return `result.error`.',
      ],
    },
    {
      id: 'branded-types',
      title: 'Identifiers that cannot be swapped',
      brief: [
        '`getUser(orderId)` compiles perfectly when both ids are `string`, and the bug shows up',
        'in production.',
        '',
        'A *branded* type intersects a primitive with a phantom property that exists only in',
        'the type system. The runtime value is still a plain string; the compiler now refuses',
        'to let one kind stand in for another.',
        '',
        'Give both ids distinct brands. The last assertion checks a `UserId` is still usable as',
        'a string, which is the point — you are adding a constraint, not a wrapper.',
      ].join('\n'),
      starterCode: [
        'export type UserId = string;',
        '',
        'export type OrderId = string;',
      ].join('\n'),
      hiddenChecks: [
        "import type { UserId, OrderId } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Extends<UserId, OrderId>, false>>,',
        '  Expect<Equal<Extends<OrderId, UserId>, false>>,',
        '  Expect<Equal<Extends<UserId, string>, true>>,',
        '];',
      ].join('\n'),
      solution: [
        "export type UserId = string & { readonly __brand: 'UserId' };",
        '',
        "export type OrderId = string & { readonly __brand: 'OrderId' };",
      ].join('\n'),
      hints: [
        'Intersect the primitive with an object type carrying a marker property.',
        'The marker has to differ between the two, or they will still be interchangeable.',
        "Write `string & { readonly __brand: 'UserId' }` and the same with `'OrderId'`.",
      ],
    },
    {
      id: 'satisfies',
      title: 'satisfies checks without widening',
      brief: [
        'An annotation is a two-way street: `const palette: Palette` checks your object *and*',
        'replaces its type with `Palette`. So `palette.red` becomes the whole union, and you',
        'have to narrow it again at every use.',
        '',
        '`satisfies` checks without replacing. The object keeps the specific type it was',
        'inferred with, and you still get an error if it violates the constraint.',
        '',
        'Keep the constraint, lose the widening.',
      ].join('\n'),
      starterCode: [
        'export type Palette = Record<string, string | [number, number, number]>;',
        '',
        'export const palette: Palette = {',
        "  red: [255, 0, 0],",
        "  green: '#00ff00',",
        '};',
      ].join('\n'),
      hiddenChecks: [
        "import { palette } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof palette.red, [number, number, number]>>,',
        '  Expect<Equal<typeof palette.green, string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Palette = Record<string, string | [number, number, number]>;',
        '',
        'export const palette = {',
        '  red: [255, 0, 0],',
        "  green: '#00ff00',",
        '} satisfies Palette;',
      ].join('\n'),
      hints: [
        'Remove the annotation from the declaration and constrain the value instead.',
        'The `satisfies` keyword goes after the object literal, before the semicolon.',
        'Write `export const palette = { ... } satisfies Palette;`',
      ],
    },
    {
      id: 'unknown-in-catch',
      title: 'A caught error is unknown',
      brief: [
        'Under `strict`, the variable in a `catch` is `unknown`, not `Error` — and that is',
        'correct, because JavaScript lets you throw anything at all. A string, `undefined`, a',
        'number. Libraries do.',
        '',
        'So a helper that turns *whatever was thrown* into a message has to check before it',
        'reaches for `.message`.',
      ].join('\n'),
      starterCode: [
        'export function errorMessage(error: unknown): string {',
        '  return error.message;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { errorMessage } from './exercise';",
        'type _cases = [Expect<Equal<typeof errorMessage, (error: unknown) => string>>];',
      ].join('\n'),
      solution: [
        'export function errorMessage(error: unknown): string {',
        '  if (error instanceof Error) {',
        '    return error.message;',
        '  }',
        '  return String(error);',
        '}',
      ].join('\n'),
      hints: [
        '`instanceof` narrows, the same way `typeof` does for primitives.',
        'You still need a fallback for things that are not Errors.',
        'Guard with `if (error instanceof Error) return error.message;` then `return String(error);`',
      ],
    },
    {
      id: 'typed-handler',
      title: 'A handler that keeps its body type',
      brief: [
        'Route handlers are where types get abandoned: `body: any` in, `unknown` out, and every',
        'route re-validates by hand.',
        '',
        'Make the handler type generic over both its request body and its response, so a route',
        'declares its contract once and the compiler holds it to it.',
      ].join('\n'),
      starterCode: [
        'export interface Request<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'export type Handler = (req: Request<unknown>) => Promise<unknown>;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Handler, Request } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Handler<{ name: string }, { id: number }>,',
        '      (req: Request<{ name: string }>) => Promise<{ id: number }>',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export interface Request<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'export type Handler<Body, Response> = (req: Request<Body>) => Promise<Response>;',
      ].join('\n'),
      hints: [
        'The check calls `Handler` with two type arguments, so it needs two type parameters.',
        'The first flows into `Request`, the second into the `Promise`.',
        'Write `export type Handler<Body, Response> = (req: Request<Body>) => Promise<Response>;`',
      ],
    },
    {
      id: 'exhaustive-config',
      title: 'Make the compiler enforce completeness',
      brief: [
        'A feature-flag map that is missing a flag should not compile. `Record<Flag, boolean>`',
        'over a literal union gives you exactly that — add a flag to the union and every',
        'incomplete map lights up.',
        '',
        'Derive the union from the flag list rather than writing it twice, so there is still',
        'only one source of truth.',
      ].join('\n'),
      starterCode: [
        "export const FLAGS = ['newCheckout', 'darkMode', 'betaSearch'];",
        '',
        'export type Flag = string;',
        '',
        'export type FlagState = Record<string, boolean>;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Flag, FlagState } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<Flag, 'newCheckout' | 'darkMode' | 'betaSearch'>>,",
        '  Expect<',
        '    Equal<',
        '      FlagState,',
        '      { newCheckout: boolean; darkMode: boolean; betaSearch: boolean }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      hints: [
        'This combines two things you have already done: `as const` with indexed access, then `Record`.',
        'Without `as const` the array is `string[]` and the literals are gone before you can read them.',
        'Write `as const` on the array, `type Flag = (typeof FLAGS)[number]`, and `Record<Flag, boolean>`.',
      ],
      solution: [
        "export const FLAGS = ['newCheckout', 'darkMode', 'betaSearch'] as const;",
        '',
        'export type Flag = (typeof FLAGS)[number];',
        '',
        'export type FlagState = Record<Flag, boolean>;',
      ].join('\n'),
    },
  ],
};
