import type { Module } from '../types';

export const backendPatterns: Module = {
  id: 'backend-patterns',
  title: 'Backend Patterns',
  blurb:
    'The handful of patterns that carry most of the weight in real Node services: schemas as the source of truth, results instead of exceptions, and identifiers that cannot be mixed up.',
  status: 'ready',
  exercises: [
    {
      id: 'schema-inference',
      title: 'One schema, one type',
      concept: [
        'Here is the oldest bug in a typed backend. You have an `interface User`, and a validator that checks incoming JSON, and over eighteen months they drift apart. The compiler is now confidently describing a shape your server never actually produces.',
        '',
        'The fix is to stop writing both. Define the validator, and *derive* the type from it:',
        '',
        '```ts',
        'import { z } from \'zod\';',
        '',
        'const userSchema = z.object({',
        '  id: z.string(),',
        '  email: z.string().email(),',
        '  loginCount: z.number(),',
        '});',
        '',
        'type User = z.infer<typeof userSchema>;',
        '',
        'const user: User = { id: \'u1\', email: \'ada@example.com\', loginCount: 3 };',
        '```',
        '',
        '`z.infer<typeof schema>` reads the static type back out of the runtime object. There is now exactly one definition, so the two cannot disagree.',
        '',
        'Note the `typeof` again — `userSchema` is a value, and `z.infer` takes a type. The same bridge as `typeof HTTP_METHODS` in module 1.',
        '',
        'Under the hood this is nothing you have not seen. The schema object carries its output type as a phantom property, and `z.infer` is an indexed access that reads it. Mapped types assemble the object shape from the field schemas. It is module 4 and 5, applied.',
        '',
        '*(These exercises run against a small stub of zod covering the core. The API matches the real library.)*',
      ].join('\n'),
      brief: ['Derive `User` from the schema instead of declaring it separately.'].join('\n'),
      debrief: [
        'The principle has a name worth knowing: **parse, don\'t validate.**',
        '',
        'A validator that returns `boolean` leaves you holding the same `unknown` you started with, and every function downstream has to trust that somebody checked. A *parser* returns a new, differently-typed value — so having the value is itself the proof:',
        '',
        '```ts',
        'import { z } from \'zod\';',
        '',
        'const userSchema = z.object({ id: z.string() });',
        'type User = z.infer<typeof userSchema>;',
        '',
        'function handle(raw: unknown): string {',
        '  const result = userSchema.safeParse(raw);',
        '  if (!result.success) {',
        '    return \'invalid\';',
        '  }',
        '  return result.data.id;',
        '}',
        '```',
        '',
        '`safeParse` returns a discriminated union — module 2, exactly — so you cannot reach `.data` without handling failure first.',
        '',
        'The practical guidance is about *where* this goes. Parse once, at the edge: the request body, the config file, the queue message, the third-party API response. Everything inside the boundary then works with real types and never re-checks.',
        '',
        'What you should not do is scatter `safeParse` through the middle of your application. If an internal function is unsure what it was handed, the problem is that something upstream failed to parse, and adding a second check there just hides it.',
      ].join('\n'),
      starterCode: [
        "import { z } from 'zod';",
        '',
        'export const userSchema = z.object({',
        '  id: z.string(),',
        '  email: z.string().email(),',
        '  loginCount: z.number(),',
        '});',
        '',
        'export interface User {',
        '  id: string;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<User, { id: string; email: string; loginCount: number }>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { z } from 'zod';",
        '',
        'export const userSchema = z.object({',
        '  id: z.string(),',
        '  email: z.string().email(),',
        '  loginCount: z.number(),',
        '});',
        '',
        'export type User = z.infer<typeof userSchema>;',
      ].join('\n'),
      hints: [
        'Replace the interface entirely — it should be a type alias derived from the schema.',
        '`userSchema` is a value, so you need `typeof` to use it in a type position.',
        'Write `export type User = z.infer<typeof userSchema>;`',
      ],
    },
    {
      id: 'result-in-practice',
      title: 'Return failures instead of throwing them',
      concept: [
        'A thrown error is invisible to the type system. Nothing in a function\'s signature says it can fail, nothing forces the caller to care, and `try`/`catch` gives you an `unknown`.',
        '',
        'Returning a `Result` makes failure part of the type:',
        '',
        '```ts',
        'type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'function parsePort(raw: string): Result<number, string> {',
        '  const parsed = Number(raw);',
        '  if (Number.isNaN(parsed)) {',
        '    return { ok: false, error: \'not a number\' };',
        '  }',
        '  return { ok: true, value: parsed };',
        '}',
        '',
        'const result = parsePort(\'8080\');',
        'if (result.ok) {',
        '  const port: number = result.value;',
        '}',
        '```',
        '',
        'The caller cannot reach `.value` without checking `ok` first, because the discriminated union will not let them:',
        '',
        '```ts-bad',
        'type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'declare const result: Result<number, string>;',
        'const port: number = result.value;',
        '```',
        '',
        'Two things this buys you. The signature now documents that the operation can fail, so a reviewer sees it. And the compiler enforces handling, so "we forgot to catch that" stops being possible in the class of failures you model this way.',
      ].join('\n'),
      brief: ['Return the failure instead of ignoring it, and make the caller handle both branches.'].join('\n'),
      debrief: [
        'Being even-handed about this: `Result` is not free, and TypeScript is not Rust.',
        '',
        'Rust has `?`, which propagates a failure up one call in one character. TypeScript has nothing of the kind, so every layer that merely passes a failure along has to unwrap and rewrap it by hand. Ten layers deep, that is a lot of ceremony to say "and if it failed, it failed".',
        '',
        'So the useful line is roughly this. Use `Result` for **expected** failures — a parse that might not parse, a lookup that might miss, a validation that might reject. These are ordinary outcomes, and the caller genuinely has a decision to make.',
        '',
        'Keep exceptions for the **unexpected** — the database is gone, an invariant broke, the disk is full. Nobody up the stack has a sensible local response to those, and forcing every intermediate function to thread them through adds noise without adding safety. Let them hit a top-level handler.',
        '',
        'The library worth knowing if you decide you want this properly is `neverthrow`, which adds `map`, `andThen` and async variants so chains of fallible operations compose without a pyramid of `if (result.ok)`.',
        '',
        'One thing to avoid: mixing both for the same failure. A function that returns a `Result` *and* throws for some cases is worse than either, because now the caller has to do both and the signature only mentions one.',
      ].join('\n'),
      starterCode: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'export function parsePort(raw: string): Result<number, string> {',
        '  const parsed = Number(raw);',
        '  return { ok: true, value: parsed };',
        '}',
        '',
        'export function describe(result: Result<number, string>): string {',
        '  return result.value.toFixed(0);',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { describe, parsePort, Result } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof parsePort, (raw: string) => Result<number, string>>>,',
        '  Expect<Equal<typeof describe, (result: Result<number, string>) => string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Result<T, E = Error> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: E };',
        '',
        'export function parsePort(raw: string): Result<number, string> {',
        '  const parsed = Number(raw);',
        '  if (Number.isNaN(parsed)) {',
        "    return { ok: false, error: 'not a number' };",
        '  }',
        '  return { ok: true, value: parsed };',
        '}',
        '',
        'export function describe(result: Result<number, string>): string {',
        '  if (result.ok) {',
        '    return result.value.toFixed(0);',
        '  }',
        '  return result.error;',
        '}',
      ].join('\n'),
      hints: [
        '`describe` is the one failing: `result.value` does not exist on the error branch.',
        'Narrow on `result.ok` first — it is the discriminant.',
        'Guard with `if (result.ok) { return result.value.toFixed(0); }` then return `result.error`.',
      ],
    },
    {
      id: 'branded-types',
      title: 'Identifiers that cannot be swapped',
      concept: [
        '`getUser(orderId)` compiles perfectly when both ids are `string`, and the bug surfaces in production.',
        '',
        'TypeScript is *structurally* typed: two types are compatible if their shapes match, and every `string` has the same shape. Most of the time that is exactly what you want. For identifiers it is a hole.',
        '',
        'A *branded* type closes it by intersecting the primitive with a marker that exists only at compile time:',
        '',
        '```ts',
        'type UserId = string & { readonly __brand: \'UserId\' };',
        'type OrderId = string & { readonly __brand: \'OrderId\' };',
        '',
        'declare function getUser(id: UserId): string;',
        'declare const orderId: OrderId;',
        '```',
        '',
        '```ts-bad',
        'type UserId = string & { readonly __brand: \'UserId\' };',
        'type OrderId = string & { readonly __brand: \'OrderId\' };',
        '',
        'declare function getUser(id: UserId): string;',
        'declare const orderId: OrderId;',
        '',
        'getUser(orderId);',
        '```',
        '',
        'Nothing exists at runtime — the value is still a plain string, with no wrapper and no cost. `__brand` is never assigned; it is there purely so the two types stop being interchangeable.',
        '',
        'And a `UserId` is still usable everywhere a `string` is, because an intersection is assignable to both its parts. You have added a constraint, not a box.',
      ].join('\n'),
      brief: ['Give the two id types distinct brands, keeping both usable as strings.'].join('\n'),
      debrief: [
        'The obvious question: how do you ever *make* one? Nothing produces a `UserId` naturally, and that is the point — so it takes a cast, and the discipline is to have exactly one place that does it:',
        '',
        '```ts',
        'type UserId = string & { readonly __brand: \'UserId\' };',
        '',
        'function toUserId(raw: string): UserId {',
        '  if (raw.length === 0) {',
        '    throw new Error(\'empty id\');',
        '  }',
        '  return raw as UserId;',
        '}',
        '',
        'declare function getUser(id: UserId): string;',
        'getUser(toUserId(\'u1\'));',
        '```',
        '',
        'That function is a *smart constructor*. The cast is unavoidable, and confining it to one place turns it from a hole into a checkpoint — every `UserId` in the system provably came through a validation you can read in one file.',
        '',
        'This composes with the previous exercises. A branded type plus a schema means "this string has been validated" is something the type system tracks, and the brand is the receipt.',
        '',
        'A slightly stronger variant uses a `unique symbol` so the brand cannot be forged by writing the same object type by hand:',
        '',
        '```ts',
        'declare const brand: unique symbol;',
        'type Email = string & { readonly [brand]: \'Email\' };',
        '',
        'declare function send(to: Email): void;',
        '```',
        '',
        'Since the symbol is not exported, nothing outside that module can construct the marker at all. Worth reaching for on the types where being wrong actually matters.',
      ].join('\n'),
      starterCode: [
        'export type UserId = string;',
        '',
        'export type OrderId = string;',
      ].join('\n'),
      hiddenChecks: [
        "import type { UserId, OrderId } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<Extends<UserId, OrderId>, false>>,',
        '  Expect<Equal<Extends<OrderId, UserId>, false>>,',
        '  Expect<Equal<Extends<UserId, string>, true>>,',
        '];',
      ].join('\n'),
      solution: [
        "export type UserId = string & { readonly __brand: 'UserId' };",
        '',
        "export type OrderId = string & { readonly __brand: 'OrderId' };",
      ].join('\n'),
      hints: [
        'Intersect the primitive with an object type carrying a marker property.',
        'The marker has to differ between the two, or they will still be interchangeable.',
        "Write `string & { readonly __brand: 'UserId' }` and the same with `'OrderId'`.",
      ],
    },
    {
      id: 'satisfies',
      title: 'satisfies checks without widening',
      concept: [
        'An annotation is a two-way street. `const palette: Palette` checks your object **and** replaces its type with `Palette` — so the specific thing you wrote is gone, and every use has to narrow it back:',
        '',
        '```ts-bad',
        'type Palette = Record<string, string | [number, number, number]>;',
        '',
        'const palette: Palette = {',
        '  red: [255, 0, 0],',
        '  green: \'#00ff00\',',
        '};',
        '',
        'const [r] = palette.red;',
        '```',
        '',
        '`satisfies` checks without replacing. The object keeps the type it was inferred with, and you still get an error if it violates the constraint:',
        '',
        '```ts',
        'type Palette = Record<string, string | [number, number, number]>;',
        '',
        'const palette = {',
        '  red: [255, 0, 0],',
        '  green: \'#00ff00\',',
        '} satisfies Palette;',
        '',
        'const [r] = palette.red;',
        'const g: string = palette.green;',
        '```',
        '',
        '`palette.red` is `[number, number, number]` and `palette.green` is `string` — each key kept what it actually holds, while the whole object was still checked against `Palette`.',
        '',
        'The tuple inference is worth noticing too. `[255, 0, 0]` would normally widen to `number[]`; the contextual type from `satisfies` is what makes it a tuple.',
      ].join('\n'),
      brief: ['Keep the constraint, lose the widening.'].join('\n'),
      debrief: [
        'Three tools that look similar and do different things. Worth getting straight, because choosing wrong is a common source of "why is this type so vague".',
        '',
        '```ts',
        'const a = { port: 3000 };',
        'const b = { port: 3000 } as const;',
        'const c = { port: 3000 } satisfies { port: number };',
        '',
        'const wide: number = a.port;',
        'const exact: 3000 = b.port;',
        'const checked: number = c.port;',
        '```',
        '',
        '- **Annotation** (`const x: T = ...`) — checks, and replaces the type with `T`. Use when you want the wider type, which is often: a variable you will reassign, a function parameter.',
        '- **`as const`** — no checking, preserves everything as literally as possible and marks it `readonly`. Use for lookup tables and constant lists you derive types from, as in module 1.',
        '- **`satisfies`** — checks against `T`, keeps the inferred type. Use when both matter: you want to catch a missing key *and* keep the specific types.',
        '',
        'The two combine, and the combination is the one you want for a route table or config object:',
        '',
        '```ts',
        'type Routes = Record<string, { method: \'GET\' | \'POST\' }>;',
        '',
        'const routes = {',
        '  home: { method: \'GET\' },',
        '  submit: { method: \'POST\' },',
        '} as const satisfies Routes;',
        '',
        'type RouteName = keyof typeof routes;',
        '',
        'const r: RouteName = \'home\';',
        '```',
        '',
        'Checked for correctness, literal types preserved, and `keyof typeof` gives you the union of route names for free. `satisfies` arrived in TypeScript 4.9 and this pattern is most of why.',
      ].join('\n'),
      starterCode: [
        'export type Palette = Record<string, string | [number, number, number]>;',
        '',
        'export const palette: Palette = {',
        "  red: [255, 0, 0],",
        "  green: '#00ff00',",
        '};',
      ].join('\n'),
      hiddenChecks: [
        "import { palette } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<typeof palette.red, [number, number, number]>>,',
        '  Expect<Equal<typeof palette.green, string>>,',
        '];',
      ].join('\n'),
      solution: [
        'export type Palette = Record<string, string | [number, number, number]>;',
        '',
        'export const palette = {',
        '  red: [255, 0, 0],',
        "  green: '#00ff00',",
        '} satisfies Palette;',
      ].join('\n'),
      hints: [
        'Remove the annotation from the declaration and constrain the value instead.',
        'The `satisfies` keyword goes after the object literal, before the semicolon.',
        'Write `export const palette = { ... } satisfies Palette;`',
      ],
    },
    {
      id: 'unknown-in-catch',
      title: 'A caught error is unknown',
      concept: [
        'Under `strict`, the variable in a `catch` is `unknown`. That is not pedantry — JavaScript lets you throw anything at all, and libraries do:',
        '',
        '```ts',
        'throw \'a string\';',
        '```',
        '',
        'So a helper that turns *whatever was thrown* into a message has to check before reaching for `.message`:',
        '',
        '```ts-bad',
        'function errorMessage(error: unknown): string {',
        '  return error.message;',
        '}',
        '```',
        '',
        '```ts',
        'function errorMessage(error: unknown): string {',
        '  if (error instanceof Error) {',
        '    return error.message;',
        '  }',
        '  return String(error);',
        '}',
        '```',
        '',
        '`instanceof` narrows the same way `typeof` does for primitives — module 2, applied to classes.',
        '',
        'The flag responsible is `useUnknownInCatchVariables`, part of `strict` since TypeScript 4.4. Before it, `catch (e)` gave you `any`, and the overwhelmingly common `e.message` compiled fine and crashed whenever something threw a non-Error.',
      ].join('\n'),
      brief: ['Handle whatever was actually thrown.'].join('\n'),
      debrief: [
        'One trap that costs people real debugging time: `instanceof Error` can return `false` for something that genuinely is an Error.',
        '',
        'It compares against a specific constructor\'s prototype, so it fails across *realms* — a Node `vm` context, an iframe, a worker — and it can fail when two copies of a library end up in the bundle, each with its own `Error` subclass. The object is an error, has a `message`, and fails the check.',
        '',
        'The robust version is duck typing:',
        '',
        '```ts',
        'function isErrorLike(value: unknown): value is { message: string } {',
        '  return (',
        '    typeof value === \'object\' &&',
        '    value !== null &&',
        '    \'message\' in value &&',
        '    typeof (value as { message: unknown }).message === \'string\'',
        '  );',
        '}',
        '',
        'function errorMessage(error: unknown): string {',
        '  return isErrorLike(error) ? error.message : String(error);',
        '}',
        '```',
        '',
        'A type predicate from module 2, doing exactly the job it was designed for.',
        '',
        'Also worth knowing: `Error` takes a `cause` since ES2022, which is how you wrap without losing the original.',
        '',
        'And if you subclass `Error`, be aware that `class extends Error` has a long-standing quirk when compiled down to ES5 — `instanceof YourError` returns `false` unless you call `Object.setPrototypeOf(this, new.target.prototype)` in the constructor. Targeting ES2015 or later, which this project does, avoids it entirely.',
      ].join('\n'),
      starterCode: [
        'export function errorMessage(error: unknown): string {',
        '  return error.message;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { errorMessage } from './exercise';",
        'type _cases = [Expect<Equal<typeof errorMessage, (error: unknown) => string>>];',
      ].join('\n'),
      solution: [
        'export function errorMessage(error: unknown): string {',
        '  if (error instanceof Error) {',
        '    return error.message;',
        '  }',
        '  return String(error);',
        '}',
      ].join('\n'),
      hints: [
        '`instanceof` narrows, the same way `typeof` does for primitives.',
        'You still need a fallback for things that are not Errors.',
        'Guard with `if (error instanceof Error) return error.message;` then `return String(error);`',
      ],
    },
    {
      id: 'typed-handler',
      title: 'A handler that keeps its body type',
      concept: [
        'Route handlers are where types tend to get abandoned: `body: any` going in, `unknown` coming out, and every route re-checking by hand.',
        '',
        'Making the handler generic over both halves lets a route declare its contract once:',
        '',
        '```ts',
        'interface ApiRequest<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'type Handler<Body, Response> = (req: ApiRequest<Body>) => Promise<Response>;',
        '',
        'const createUser: Handler<{ name: string }, { id: number }> = async (req) => {',
        '  return { id: req.body.name.length };',
        '};',
        '```',
        '',
        'Look at what the annotation on `createUser` bought. Inside the body, `req.body.name` is a `string` with no annotation anywhere in the function — the types flowed in from `Handler` by contextual typing. And the return value is checked against `{ id: number }`, so a typo in the response shape is an error here rather than a surprise for whoever consumes the endpoint.',
        '',
        'This is the shape every typed web framework converges on. Fastify\'s type providers, tRPC\'s procedures and Hono\'s handlers are all elaborations of these two type parameters.',
      ].join('\n'),
      brief: ['Make the handler carry its request body and response types.'].join('\n'),
      debrief: [
        'The essential caveat, and it is the reason module 7 opened with schemas: **this proves nothing at runtime.**',
        '',
        '`Handler<{ name: string }, ...>` is a claim about what will arrive. The actual request body is whatever was posted — an empty object, a string, `null`. Types are erased; nothing checks it:',
        '',
        '```ts',
        'interface ApiRequest<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'type Handler<Body, Response> = (req: ApiRequest<Body>) => Promise<Response>;',
        '',
        'const handler: Handler<{ name: string }, number> = async (req) => {',
        '  return req.body.name.length;',
        '};',
        '```',
        '',
        'That compiles, and it throws on the first request with no `name`. The type parameter described an intention, and intentions are not validation.',
        '',
        'The fix is to make the schema the source of both, so the runtime check and the static type cannot come apart:',
        '',
        '```ts',
        'import { z } from \'zod\';',
        '',
        'const bodySchema = z.object({ name: z.string() });',
        'type Body = z.infer<typeof bodySchema>;',
        '',
        'function handle(raw: unknown): number {',
        '  const parsed = bodySchema.safeParse(raw);',
        '  if (!parsed.success) {',
        '    return 0;',
        '  }',
        '  return parsed.data.name.length;',
        '}',
        '```',
        '',
        'That is what the frameworks actually do: you hand them a schema, they validate the request *and* infer the handler\'s types from the same object. Both halves, one definition — which is exercise 1 of this module, arriving where it was always going.',
      ].join('\n'),
      starterCode: [
        'export interface ApiRequest<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'export type Handler = (req: ApiRequest<unknown>) => Promise<unknown>;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Handler, ApiRequest } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      Handler<{ name: string }, { id: number }>,',
        '      (req: ApiRequest<{ name: string }>) => Promise<{ id: number }>',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export interface ApiRequest<Body> {',
        '  body: Body;',
        '  headers: Record<string, string>;',
        '}',
        '',
        'export type Handler<Body, Response> = (req: ApiRequest<Body>) => Promise<Response>;',
      ].join('\n'),
      hints: [
        'The check calls `Handler` with two type arguments, so it needs two type parameters.',
        'The first flows into `ApiRequest`, the second into the `Promise`.',
        'Write `export type Handler<Body, Response> = (req: ApiRequest<Body>) => Promise<Response>;`',
      ],
    },
    {
      id: 'exhaustive-config',
      title: 'Make the compiler enforce completeness',
      concept: [
        'A feature-flag map that is missing a flag should not compile. Two things you already have combine to guarantee it.',
        '',
        '`as const` with an indexed access derives the union from the list, so there is one source of truth. `Record` over that union then demands every member:',
        '',
        '```ts',
        'const FLAGS = [\'newCheckout\', \'darkMode\', \'betaSearch\'] as const;',
        '',
        'type Flag = (typeof FLAGS)[number];',
        'type FlagState = Record<Flag, boolean>;',
        '',
        'const state: FlagState = {',
        '  newCheckout: true,',
        '  darkMode: false,',
        '  betaSearch: true,',
        '};',
        '```',
        '',
        'Add a fourth flag to the array and every incomplete map in the codebase becomes an error, naming the property it lacks:',
        '',
        '```ts-bad',
        'const FLAGS = [\'newCheckout\', \'darkMode\', \'betaSearch\', \'newNav\'] as const;',
        '',
        'type FlagState = Record<(typeof FLAGS)[number], boolean>;',
        '',
        'const state: FlagState = {',
        '  newCheckout: true,',
        '  darkMode: false,',
        '  betaSearch: true,',
        '};',
        '```',
        '',
        'The list stays iterable at runtime, which you need for rendering an admin page or seeding defaults, and the type is derived from it rather than maintained alongside it.',
      ].join('\n'),
      brief: ['Derive the flag union from the list, then demand a complete map.'].join('\n'),
      debrief: [
        'That is module 7. Every exercise in it was one idea seen from a different angle: **make the illegal state unrepresentable, then let the compiler do the enforcing.**',
        '',
        '- A schema, so the type and the runtime check cannot disagree.',
        '- A `Result`, so an unhandled failure is a compile error.',
        '- A brand, so a `UserId` cannot be an `OrderId`.',
        '- `satisfies`, so a config is checked without being flattened.',
        '- `unknown` in `catch`, so the thing you caught gets examined before it gets used.',
        '- A generic handler, so a route\'s contract is written once.',
        '- `Record` over a derived union, so an incomplete table does not build.',
        '',
        'None of these are advanced features. They are the basics from modules 1 through 5 pointed at problems that actually occur in a service.',
        '',
        'The thread worth carrying out of here is the last one, because it generalises: when you find yourself writing a comment that says "remember to update X when you change Y", there is usually a type that can say it instead. `as const` plus a derived union is the cheapest version of that idea, and it applies far beyond feature flags — route tables, permission sets, event names, migration lists, environment names.',
        '',
        'Module 8 is the same material aimed at React, where "illegal state unrepresentable" turns into props that cannot be combined wrongly.',
      ].join('\n'),
      starterCode: [
        "export const FLAGS = ['newCheckout', 'darkMode', 'betaSearch'];",
        '',
        'export type Flag = string;',
        '',
        'export type FlagState = Record<string, boolean>;',
      ].join('\n'),
      hiddenChecks: [
        "import type { Flag, FlagState } from './exercise';",
        'type _cases = [',
        "  Expect<Equal<Flag, 'newCheckout' | 'darkMode' | 'betaSearch'>>,",
        '  Expect<',
        '    Equal<',
        '      FlagState,',
        '      { newCheckout: boolean; darkMode: boolean; betaSearch: boolean }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      hints: [
        'This combines two things you have already done: `as const` with indexed access, then `Record`.',
        'Without `as const` the array is `string[]` and the literals are gone before you can read them.',
        'Write `as const` on the array, `type Flag = (typeof FLAGS)[number]`, and `Record<Flag, boolean>`.',
      ],
      solution: [
        "export const FLAGS = ['newCheckout', 'darkMode', 'betaSearch'] as const;",
        '',
        'export type Flag = (typeof FLAGS)[number];',
        '',
        'export type FlagState = Record<Flag, boolean>;',
      ].join('\n'),
    },
  ],
};
