import type { Module } from '../types';

export const react: Module = {
  id: 'react',
  title: 'Typing React',
  blurb:
    'Everything so far, pointed at components: props, state, events, and the two patterns — union props and generic components — that make a component impossible to misuse.',
  status: 'ready',
  exercises: [
    {
      id: 'props-interface',
      title: 'Props are just a parameter',
      brief: [
        'A component is a function, and its props are its one argument. There is nothing',
        'React-specific about typing it — you are annotating a destructured object parameter.',
        '',
        '`variant` should only accept the two values the styles actually handle, and `onClick`',
        'is optional.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        'export interface ButtonProps {',
        '  label: string;',
        '  variant: string;',
        '  onClick: () => void;',
        '}',
        '',
        'export function Button({ label }: ButtonProps) {',
        '  return <button>{label}</button>;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ButtonProps } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ButtonProps,',
        "      { label: string; variant: 'primary' | 'ghost'; onClick?: () => void }",
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export interface ButtonProps {',
        '  label: string;',
        "  variant: 'primary' | 'ghost';",
        '  onClick?: () => void;',
        '}',
        '',
        'export function Button({ label }: ButtonProps) {',
        '  return <button>{label}</button>;',
        '}',
      ].join('\n'),
      hints: [
        'Two changes, both things you did back in module 1 and 2.',
        '`variant` becomes a union of string literals; `onClick` gets a `?`.',
        "Write `variant: 'primary' | 'ghost';` and `onClick?: () => void;`",
      ],
    },
    {
      id: 'children',
      title: 'children is not automatic',
      brief: [
        'React 18 removed the implicit `children` from function components, which surprised a',
        'lot of people. If a component takes children, its props type has to say so.',
        '',
        '`ReactNode` is the right type: it covers elements, strings, numbers, arrays, null and',
        'undefined — everything React knows how to render.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface CardProps {',
        '  title: string;',
        '}',
        '',
        'export function Card({ title, children }: CardProps) {',
        '  return (',
        '    <section>',
        '      <h2>{title}</h2>',
        '      {children}',
        '    </section>',
        '  );',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { CardProps } from './exercise';",
        "import type { ReactNode } from 'react';",
        'type _cases = [',
        '  Expect<Equal<CardProps, { title: string; children?: ReactNode }>>,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface CardProps {',
        '  title: string;',
        '  children?: ReactNode;',
        '}',
        '',
        'export function Card({ title, children }: CardProps) {',
        '  return (',
        '    <section>',
        '      <h2>{title}</h2>',
        '      {children}',
        '    </section>',
        '  );',
        '}',
      ].join('\n'),
      hints: [
        'The import is already there — you just need to use it.',
        'The check expects children to be optional.',
        'Add `children?: ReactNode;` to `CardProps`.',
      ],
    },
    {
      id: 'usestate',
      title: 'When useState needs help',
      brief: [
        '`useState` infers from its initial value, and most of the time that is exactly right —',
        '`useState(0)` is a `number` and needs no annotation.',
        '',
        'It goes wrong when the initial value is narrower than the state will ever be.',
        '`useState(null)` infers `null`, and now you can never set anything else.',
        '',
        'Give it the type argument it cannot work out on its own.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import { useState } from 'react';",
        '',
        'export interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState(null);',
        "  const load = () => setUser({ id: 'u1' });",
        '  return { user, load };',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { useCurrentUser, User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ReturnType<typeof useCurrentUser>[\'user\'], User | null>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { useState } from 'react';",
        '',
        'export interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState<User | null>(null);',
        "  const load = () => setUser({ id: 'u1' });",
        '  return { user, load };',
        '}',
      ].join('\n'),
      hints: [
        'The type argument goes in angle brackets, between `useState` and its parentheses.',
        'The state is either a user or nothing.',
        'Write `useState<User | null>(null)`.',
      ],
    },
    {
      id: 'event-handlers',
      title: 'Typing an event handler',
      brief: [
        'React events are not DOM events — they are React’s synthetic wrappers, and they are',
        'generic over the element they fired on. That type parameter is what makes',
        '`event.target.value` a `string` rather than a guess.',
        '',
        'Type the handler so the body compiles without a cast.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ChangeEvent } from 'react';",
        '',
        'export type SearchHandler = (event: unknown) => void;',
        '',
        'export const onSearch: SearchHandler = (event) => {',
        '  console.log(event.target.value);',
        '};',
      ].join('\n'),
      hiddenChecks: [
        "import type { SearchHandler } from './exercise';",
        "import type { ChangeEvent } from 'react';",
        'type _cases = [',
        '  Expect<Equal<SearchHandler, (event: ChangeEvent<HTMLInputElement>) => void>>,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ChangeEvent } from 'react';",
        '',
        'export type SearchHandler = (event: ChangeEvent<HTMLInputElement>) => void;',
        '',
        'export const onSearch: SearchHandler = (event) => {',
        '  console.log(event.target.value);',
        '};',
      ].join('\n'),
      hints: [
        'The import you need is already at the top of the file.',
        '`ChangeEvent` takes the element type as a type argument — this one is an input.',
        'Write `(event: ChangeEvent<HTMLInputElement>) => void`.',
      ],
    },
    {
      id: 'union-props',
      title: 'Props that make bad combinations impossible',
      brief: [
        'This is the most valuable React typing pattern, and it is just a discriminated union',
        'again.',
        '',
        'An alert is either a link (with an `href`) or a button (with an `onDismiss`) — never',
        'both, never neither. Two optional props cannot express that; a union of two prop',
        'shapes can, and the compiler rejects the nonsense combinations at the call site.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        'export interface AlertProps {',
        '  message: string;',
        "  kind: 'link' | 'button';",
        '  href?: string;',
        '  onDismiss?: () => void;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { AlertProps } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      AlertProps,',
        "      | { message: string; kind: 'link'; href: string }",
        "      | { message: string; kind: 'button'; onDismiss: () => void }",
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type AlertProps =',
        "  | { message: string; kind: 'link'; href: string }",
        "  | { message: string; kind: 'button'; onDismiss: () => void };",
      ].join('\n'),
      hints: [
        'This stops being an `interface` and becomes a union type.',
        'Each member carries its own literal `kind` plus the prop that goes with it — and both props are required within their branch.',
        "Write `export type AlertProps = { message: string; kind: 'link'; href: string } | { message: string; kind: 'button'; onDismiss: () => void };`",
      ],
    },
    {
      id: 'generic-component',
      title: 'A component with a type parameter',
      brief: [
        'A list component should not flatten its items to `unknown` — the `renderItem` callback',
        'ought to receive whatever you actually passed in.',
        '',
        'Components take type parameters exactly like functions do, because that is all they',
        'are. Pass `User[]`, and `renderItem` gets a `User`.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface ListProps {',
        '  items: unknown[];',
        '  renderItem: (item: unknown) => ReactNode;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ListProps } from './exercise';",
        "import type { ReactNode } from 'react';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ListProps<{ id: string }>,',
        '      { items: { id: string }[]; renderItem: (item: { id: string }) => ReactNode }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface ListProps<T> {',
        '  items: T[];',
        '  renderItem: (item: T) => ReactNode;',
        '}',
      ].join('\n'),
      hints: [
        'The check uses `ListProps<{ id: string }>`, so the interface needs a type parameter.',
        'That same parameter is the element type of `items` and the argument of `renderItem` — which is what ties them together.',
        'Write `export interface ListProps<T> { items: T[]; renderItem: (item: T) => ReactNode }`.',
      ],
    },
    {
      id: 'custom-hook-tuple',
      title: 'Make a hook return a tuple, not an array',
      brief: [
        'A hook that returns `[value, toggle]` looks like `useState` — until you destructure it',
        'and find both elements typed as `boolean | (() => void)`.',
        '',
        'Array literals infer as arrays, so positions are lost. `as const` freezes the return',
        'into a tuple, and each position keeps its own type.',
        '',
        'That readonly tuple is exactly what `useState` returns, and why destructuring it works.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import { useState } from 'react';",
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { useToggle } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ReturnType<typeof useToggle>, readonly [boolean, () => void]>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { useState } from 'react';",
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle] as const;',
        '}',
      ].join('\n'),
      hints: [
        'The check expects a `readonly` tuple, which is a strong hint about which tool to reach for.',
        'You met it in module 1, applied to an array of strings.',
        'Append `as const` to the returned array literal.',
      ],
    },
  ],
};
