import type { Module } from '../types';

export const react: Module = {
  id: 'react',
  title: 'Typing React',
  blurb:
    'Everything so far, pointed at components: props, state, events, and the two patterns — union props and generic components — that make a component impossible to misuse.',
  status: 'ready',
  exercises: [
    {
      id: 'props-interface',
      title: 'Props are just a parameter',
      concept: [
        'A component is a function, and its props are its single argument. There is nothing React-specific about typing it — you are annotating a destructured object parameter, which you have been doing since module 1.',
        '',
        '```tsx',
        'interface ButtonProps {',
        '  label: string;',
        '  variant: \'primary\' | \'ghost\';',
        '  onClick?: () => void;',
        '}',
        '',
        'export function Button({ label, onClick }: ButtonProps) {',
        '  return <button onClick={onClick}>{label}</button>;',
        '}',
        '```',
        '',
        'Everything in there is material you already have. `variant` is a union of string literals from module 1, so a typo is a compile error and the two values autocomplete. `onClick` is optional with `?` from module 2. The handler is a function type from module 1.',
        '',
        'That is most of what typing React amounts to. The genuinely React-specific parts — `ReactNode`, the synthetic event types, the generic component syntax — are a handful of names layered on top of what the rest of this curriculum has already covered.',
      ].join('\n'),
      brief: ['Constrain `variant` to the two variants the styles handle, and make `onClick` optional.'].join('\n'),
      debrief: [
        'You may have seen components written with `React.FC` instead:',
        '',
        '```tsx',
        'import type { FC } from \'react\';',
        '',
        'interface ButtonProps {',
        '  label: string;',
        '}',
        '',
        'const Button: FC<ButtonProps> = ({ label }) => <button>{label}</button>;',
        '```',
        '',
        'That works, and the ecosystem has largely moved away from it. Three reasons, in ascending order of how much they matter.',
        '',
        'Before React 18\'s types, `FC` silently added `children` to every component, so components that did not accept children accepted them anyway and dropped them on the floor. That is fixed now, but a lot of the advice you will find predates the fix and is confusing as a result.',
        '',
        '`FC` cannot express a generic component. There is no way to write `FC<ListProps<T>>` with `T` bound per call site, so the moment you need exercise 6 you have to drop it.',
        '',
        'And it adds nothing. `function Button(props: ButtonProps)` is shorter, infers the return type correctly, and works with every pattern including generics and overloads.',
        '',
        'The current default is a plain function declaration with a typed parameter, and to let the return type be inferred. `JSX.Element` is not worth writing out — inference has it, and it is one more thing to keep in step.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        'export interface ButtonProps {',
        '  label: string;',
        '  variant: string;',
        '  onClick: () => void;',
        '}',
        '',
        'export function Button({ label }: ButtonProps) {',
        '  return <button>{label}</button>;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ButtonProps } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ButtonProps,',
        "      { label: string; variant: 'primary' | 'ghost'; onClick?: () => void }",
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export interface ButtonProps {',
        '  label: string;',
        "  variant: 'primary' | 'ghost';",
        '  onClick?: () => void;',
        '}',
        '',
        'export function Button({ label }: ButtonProps) {',
        '  return <button>{label}</button>;',
        '}',
      ].join('\n'),
      hints: [
        'Two changes, both things you did back in module 1 and 2.',
        '`variant` becomes a union of string literals; `onClick` gets a `?`.',
        "Write `variant: 'primary' | 'ghost';` and `onClick?: () => void;`",
      ],
    },
    {
      id: 'children',
      title: 'children is not automatic',
      concept: [
        'React 18\'s types removed the implicit `children` prop, which surprised a lot of people mid-upgrade. If a component takes children now, its props type has to say so.',
        '',
        '`ReactNode` is the type you want. It covers everything React knows how to render — elements, strings, numbers, arrays, `null`, `undefined`, booleans:',
        '',
        '```tsx',
        'import type { ReactNode } from \'react\';',
        '',
        'interface CardProps {',
        '  title: string;',
        '  children?: ReactNode;',
        '}',
        '',
        'export function Card({ title, children }: CardProps) {',
        '  return (',
        '    <section>',
        '      <h2>{title}</h2>',
        '      {children}',
        '    </section>',
        '  );',
        '}',
        '```',
        '',
        'Whether to mark it optional is a real decision rather than a formality. `children?: ReactNode` means the component works with or without them. `children: ReactNode` makes them required, so `<Card title="x" />` becomes a compile error — appropriate for something like a modal body or a layout wrapper that is meaningless when empty.',
        '',
        'There is a helper for the common case:',
        '',
        '```tsx',
        'import type { PropsWithChildren } from \'react\';',
        '',
        'type CardProps = PropsWithChildren<{ title: string }>;',
        '```',
        '',
        'It expands to exactly the same thing. Use it if you like it; writing `children` out is equally idiomatic and rather more obvious.',
      ].join('\n'),
      brief: ['Let `Card` accept children.'].join('\n'),
      debrief: [
        'Three similar names, worth separating once:',
        '',
        '- **`ReactNode`** — anything renderable. The right type for `children` in almost every case.',
        '- **`ReactElement`** — specifically a JSX element. Narrower: no strings, no numbers, no arrays.',
        '- **`JSX.Element`** — very nearly `ReactElement`, and a historical artefact. Prefer `ReactElement` in new code.',
        '',
        'Being narrower is occasionally what you want. A component that will clone its children and inject a prop genuinely cannot accept a plain string, and `ReactElement` says so.',
        '',
        'Mostly, though, reaching for `ReactElement` on `children` is a mistake that shows up the first time someone writes `<Card title="x">hello</Card>` and gets a type error for a completely reasonable thing to do.',
        '',
        'When children need real structure — not "anything renderable" but "one row per item, and I control the layout" — the answer is usually a function prop rather than a narrower node type:',
        '',
        '```tsx',
        'import type { ReactNode } from \'react\';',
        '',
        'interface TableProps<T> {',
        '  rows: T[];',
        '  renderRow: (row: T) => ReactNode;',
        '}',
        '```',
        '',
        'That is a render prop, it types cleanly, and it is exercise 6 arriving early.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface CardProps {',
        '  title: string;',
        '}',
        '',
        'export function Card({ title, children }: CardProps) {',
        '  return (',
        '    <section>',
        '      <h2>{title}</h2>',
        '      {children}',
        '    </section>',
        '  );',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { CardProps } from './exercise';",
        "import type { ReactNode } from 'react';",
        'type _cases = [',
        '  Expect<Equal<CardProps, { title: string; children?: ReactNode }>>,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface CardProps {',
        '  title: string;',
        '  children?: ReactNode;',
        '}',
        '',
        'export function Card({ title, children }: CardProps) {',
        '  return (',
        '    <section>',
        '      <h2>{title}</h2>',
        '      {children}',
        '    </section>',
        '  );',
        '}',
      ].join('\n'),
      hints: [
        'The import is already there — you just need to use it.',
        'The check expects children to be optional.',
        'Add `children?: ReactNode;` to `CardProps`.',
      ],
    },
    {
      id: 'usestate',
      title: 'When useState needs help',
      concept: [
        '`useState` infers from its initial value, and most of the time that is exactly right:',
        '',
        '```tsx',
        'import { useState } from \'react\';',
        '',
        'export function Counter() {',
        '  const [count, setCount] = useState(0);',
        '  return <button onClick={() => setCount(count + 1)}>{count}</button>;',
        '}',
        '```',
        '',
        '`count` is `number` and `setCount` takes a `number`, with nothing annotated.',
        '',
        'It goes wrong when the initial value is *narrower* than the state will ever be. `useState(null)` infers `null`, and now nothing else can ever be stored:',
        '',
        '```tsx-bad',
        'import { useState } from \'react\';',
        '',
        'interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState(null);',
        '  const load = () => setUser({ id: \'u1\' });',
        '  return { user, load };',
        '}',
        '```',
        '',
        'The type argument says what the state can hold across its whole life, not just at the start:',
        '',
        '```tsx',
        'import { useState } from \'react\';',
        '',
        'interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState<User | null>(null);',
        '  const load = () => setUser({ id: \'u1\' });',
        '  return { user, load };',
        '}',
        '```',
        '',
        'The rule of thumb: annotate `useState` when the initial value is `null`, `undefined`, or an empty array — those are the three that infer too narrowly. Otherwise let it infer.',
      ].join('\n'),
      brief: ['Give the state a type wide enough for what it will actually hold.'].join('\n'),
      debrief: [
        'The more valuable habit is one level up: what you choose to *store* matters more than how you type it.',
        '',
        'The common shape is three independent pieces of state:',
        '',
        '```tsx',
        'import { useState } from \'react\';',
        '',
        'export function useUser() {',
        '  const [loading, setLoading] = useState(false);',
        '  const [error, setError] = useState<Error | null>(null);',
        '  const [data, setData] = useState<{ id: string } | null>(null);',
        '  return { loading, error, data, setLoading, setError, setData };',
        '}',
        '```',
        '',
        'Three booleans-and-nullables give eight combinations, and only three of them mean anything. Loading *and* error? Data *and* loading? Nothing stops them, and every component reading this has to defend against states that should be impossible.',
        '',
        'One discriminated union — module 2, in a hook — makes them unrepresentable:',
        '',
        '```tsx',
        'import { useState } from \'react\';',
        '',
        'type State =',
        '  | { phase: \'idle\' }',
        '  | { phase: \'loading\' }',
        '  | { phase: \'done\'; data: { id: string } }',
        '  | { phase: \'failed\'; error: Error };',
        '',
        'export function useUser() {',
        '  const [state, setState] = useState<State>({ phase: \'idle\' });',
        '  return state;',
        '}',
        '```',
        '',
        'Four states, all legal, and `data` is unreachable without proving the request finished. The component that renders this ends up as a `switch` with an exhaustiveness check, so adding a fifth phase makes every consumer light up.',
        '',
        'This is the single highest-leverage TypeScript habit in a React codebase, and it is not a React feature at all — it is the module 2 pattern, applied to state.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import { useState } from 'react';",
        '',
        'export interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState(null);',
        "  const load = () => setUser({ id: 'u1' });",
        '  return { user, load };',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { useCurrentUser, User } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ReturnType<typeof useCurrentUser>[\'user\'], User | null>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { useState } from 'react';",
        '',
        'export interface User {',
        '  id: string;',
        '}',
        '',
        'export function useCurrentUser() {',
        '  const [user, setUser] = useState<User | null>(null);',
        "  const load = () => setUser({ id: 'u1' });",
        '  return { user, load };',
        '}',
      ].join('\n'),
      hints: [
        'The type argument goes in angle brackets, between `useState` and its parentheses.',
        'The state is either a user or nothing.',
        'Write `useState<User | null>(null)`.',
      ],
    },
    {
      id: 'event-handlers',
      title: 'Typing an event handler',
      concept: [
        'React events are not DOM events. They are React\'s synthetic wrappers, and they are generic over the element that fired them — which is what makes `event.target.value` a `string` rather than a guess.',
        '',
        '```tsx',
        'import type { ChangeEvent } from \'react\';',
        '',
        'export type SearchHandler = (event: ChangeEvent<HTMLInputElement>) => void;',
        '',
        'export const onSearch: SearchHandler = (event) => {',
        '  console.log(event.target.value);',
        '};',
        '```',
        '',
        'The type argument matters. `ChangeEvent<HTMLInputElement>` knows the target has a `value`; a bare `ChangeEvent` does not.',
        '',
        'The names follow the event: `ChangeEvent`, `MouseEvent`, `KeyboardEvent`, `FocusEvent`, `FormEvent`, each generic over the element. There is also a handler-shaped alias for each, so these two are the same thing:',
        '',
        '```tsx',
        'import type { ChangeEvent, ChangeEventHandler } from \'react\';',
        '',
        'type A = (event: ChangeEvent<HTMLInputElement>) => void;',
        'type B = ChangeEventHandler<HTMLInputElement>;',
        '',
        'declare const a: A;',
        'const b: B = a;',
        '```',
      ].join('\n'),
      brief: ['Type the handler so the body compiles without a cast.'].join('\n'),
      debrief: [
        'Now the part that saves you the most typing: **inline handlers need no annotation at all.**',
        '',
        '```tsx',
        'export function Search() {',
        '  return <input onChange={(event) => console.log(event)} />;',
        '}',
        '```',
        '',
        'The `onChange` prop already has a type, so the callback\'s parameter is *contextually typed* from it — the same mechanism that let the `Formatter` callback in module 1 go unannotated. Writing `(event: ChangeEvent<HTMLInputElement>)` inline is pure noise, and it is one of the most common pieces of unnecessary ceremony in React codebases.',
        '',
        'You only need the explicit type when the handler is defined *away* from the JSX, because then there is no context to flow from:',
        '',
        '```tsx',
        'import type { ChangeEvent } from \'react\';',
        '',
        'export function Search() {',
        '  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {',
        '    console.log(event.target.value);',
        '  };',
        '',
        '  return <input onChange={handleChange} />;',
        '}',
        '```',
        '',
        'That is the whole rule. Inline, let it infer; extracted, annotate.',
        '',
        'One trap worth knowing: `event.target` and `event.currentTarget` are different. `currentTarget` is the element the handler is attached to and is typed precisely; `target` is whatever was actually clicked, which in a nested structure may be a child. For form inputs they coincide, which is why `event.target.value` works and why the distinction stays invisible until the day it bites.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ChangeEvent } from 'react';",
        '',
        'export type SearchHandler = (event: unknown) => void;',
        '',
        'export const onSearch: SearchHandler = (event) => {',
        '  console.log(event.target.value);',
        '};',
      ].join('\n'),
      hiddenChecks: [
        "import type { SearchHandler } from './exercise';",
        "import type { ChangeEvent } from 'react';",
        'type _cases = [',
        '  Expect<Equal<SearchHandler, (event: ChangeEvent<HTMLInputElement>) => void>>,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ChangeEvent } from 'react';",
        '',
        'export type SearchHandler = (event: ChangeEvent<HTMLInputElement>) => void;',
        '',
        'export const onSearch: SearchHandler = (event) => {',
        '  console.log(event.target.value);',
        '};',
      ].join('\n'),
      hints: [
        'The import you need is already at the top of the file.',
        '`ChangeEvent` takes the element type as a type argument — this one is an input.',
        'Write `(event: ChangeEvent<HTMLInputElement>) => void`.',
      ],
    },
    {
      id: 'union-props',
      title: 'Props that make bad combinations impossible',
      concept: [
        'This is the most valuable React typing pattern, and it is the module 2 discriminated union in a new outfit.',
        '',
        'An alert is either a link, with an `href`, or a dismissible message, with an `onDismiss`. Never both, never neither. Two optional props cannot say that:',
        '',
        '```tsx',
        'interface Loose {',
        '  message: string;',
        '  href?: string;',
        '  onDismiss?: () => void;',
        '}',
        '',
        'const bad: Loose = { message: \'oops\' };',
        'const alsoBad: Loose = { message: \'oops\', href: \'/x\', onDismiss: () => {} };',
        '```',
        '',
        'Both of those are nonsense and both type-check. A union of prop shapes makes them impossible:',
        '',
        '```tsx',
        'type AlertProps =',
        '  | { message: string; kind: \'link\'; href: string }',
        '  | { message: string; kind: \'button\'; onDismiss: () => void };',
        '',
        'const ok: AlertProps = { message: \'oops\', kind: \'link\', href: \'/x\' };',
        '```',
        '',
        '```tsx-bad',
        'type AlertProps =',
        '  | { message: string; kind: \'link\'; href: string }',
        '  | { message: string; kind: \'button\'; onDismiss: () => void };',
        '',
        'const wrong: AlertProps = { message: \'oops\', kind: \'link\', onDismiss: () => {} };',
        '```',
        '',
        'The error now lands at the call site, in the component using it, which is exactly where the mistake was made.',
      ].join('\n'),
      brief: ['Make the two prop combinations the only two that exist.'].join('\n'),
      debrief: [
        'There is a wrinkle that catches everybody the first time, and it is about *destructuring*.',
        '',
        'You cannot pull a per-branch prop out of the parameter list, because at that point the compiler has not narrowed anything:',
        '',
        '```tsx-bad',
        'type AlertProps =',
        '  | { message: string; kind: \'link\'; href: string }',
        '  | { message: string; kind: \'button\'; onDismiss: () => void };',
        '',
        'export function Alert({ message, href }: AlertProps) {',
        '  return <div>{message}</div>;',
        '}',
        '```',
        '',
        'Take the whole props object and narrow it first:',
        '',
        '```tsx',
        'type AlertProps =',
        '  | { message: string; kind: \'link\'; href: string }',
        '  | { message: string; kind: \'button\'; onDismiss: () => void };',
        '',
        'export function Alert(props: AlertProps) {',
        '  if (props.kind === \'link\') {',
        '    return <a href={props.href}>{props.message}</a>;',
        '  }',
        '  return <button onClick={props.onDismiss}>{props.message}</button>;',
        '}',
        '```',
        '',
        'Narrowing works on a *value*, and destructuring throws the value away before you get a chance. You can destructure the shared props (`const { message } = props`) and keep the union for the rest, but reaching straight for `props.x` after a narrowing check is usually clearest.',
        '',
        'The payoff is that this component is now genuinely hard to misuse. The compiler rejects a link without an `href` and a button with one, and neither mistake needs a runtime guard, a comment, or a code review to catch.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        'export interface AlertProps {',
        '  message: string;',
        "  kind: 'link' | 'button';",
        '  href?: string;',
        '  onDismiss?: () => void;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { AlertProps } from './exercise';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      AlertProps,',
        "      | { message: string; kind: 'link'; href: string }",
        "      | { message: string; kind: 'button'; onDismiss: () => void }",
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        'export type AlertProps =',
        "  | { message: string; kind: 'link'; href: string }",
        "  | { message: string; kind: 'button'; onDismiss: () => void };",
      ].join('\n'),
      hints: [
        'This stops being an `interface` and becomes a union type.',
        'Each member carries its own literal `kind` plus the prop that goes with it — and both props are required within their branch.',
        "Write `export type AlertProps = { message: string; kind: 'link'; href: string } | { message: string; kind: 'button'; onDismiss: () => void };`",
      ],
    },
    {
      id: 'generic-component',
      title: 'A component with a type parameter',
      concept: [
        'A list component should not flatten its items to `unknown` — the `renderItem` callback ought to receive whatever you actually passed in.',
        '',
        'Components take type parameters exactly like functions do, because that is all they are:',
        '',
        '```tsx',
        'import type { ReactNode } from \'react\';',
        '',
        'interface ListProps<T> {',
        '  items: T[];',
        '  renderItem: (item: T) => ReactNode;',
        '}',
        '',
        'export function List<T>({ items, renderItem }: ListProps<T>) {',
        '  return <ul>{items.map(renderItem)}</ul>;',
        '}',
        '',
        'const rendered = (',
        '  <List items={[{ id: \'u1\' }]} renderItem={(user) => <li>{user.id}</li>} />',
        ');',
        '```',
        '',
        '`T` is inferred per use from `items`, so `user` inside `renderItem` is `{ id: string }` with no annotation. Pass strings instead and it is `string`. The single type parameter is what ties the two props together — module 3, in a component.',
        '',
        'The alternative is `items: unknown[]`, which forces every caller to cast inside their own render callback, in a codebase that then has casts scattered through its JSX.',
      ].join('\n'),
      brief: ['Tie `renderItem` to the element type of `items`.'].join('\n'),
      debrief: [
        'One syntax trap, and it is specific to `.tsx` files.',
        '',
        'In a `.ts` file this is a generic arrow function. In a `.tsx` file the parser sees the opening of a JSX element:',
        '',
        '```ts',
        'const identity = <T>(value: T): T => value;',
        '',
        'const a = identity(\'x\');',
        '```',
        '',
        'Inside `.tsx` that fails. The fix is a trailing comma, which is unambiguous:',
        '',
        '```tsx',
        'const identity = <T,>(value: T): T => value;',
        '',
        'const a = identity(\'x\');',
        '```',
        '',
        '`<T,>` is one of those things that looks like a typo forever until you know why it is there. Some codebases write `<T extends unknown>` instead, which is equally valid and equally odd-looking. A plain `function` declaration sidesteps the problem entirely, which is one more small reason to prefer it for components.',
        '',
        'Worth knowing where the ceiling is. A generic component whose type parameter must flow through `forwardRef` or `memo` gets genuinely awkward, because those helpers\' own signatures are not generic in the right way — the usual workaround is a cast on the wrapped component, and it is one of the few places in React typing where the honest answer is "assert and move on".',
        '',
        'For ordinary components, though, this is exactly as simple as it looks: a function with a type parameter.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface ListProps {',
        '  items: unknown[];',
        '  renderItem: (item: unknown) => ReactNode;',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { ListProps } from './exercise';",
        "import type { ReactNode } from 'react';",
        'type _cases = [',
        '  Expect<',
        '    Equal<',
        '      ListProps<{ id: string }>,',
        '      { items: { id: string }[]; renderItem: (item: { id: string }) => ReactNode }',
        '    >',
        '  >,',
        '];',
      ].join('\n'),
      solution: [
        "import type { ReactNode } from 'react';",
        '',
        'export interface ListProps<T> {',
        '  items: T[];',
        '  renderItem: (item: T) => ReactNode;',
        '}',
      ].join('\n'),
      hints: [
        'The check uses `ListProps<{ id: string }>`, so the interface needs a type parameter.',
        'That same parameter is the element type of `items` and the argument of `renderItem` — which is what ties them together.',
        'Write `export interface ListProps<T> { items: T[]; renderItem: (item: T) => ReactNode }`.',
      ],
    },
    {
      id: 'custom-hook-tuple',
      title: 'Make a hook return a tuple, not an array',
      concept: [
        'A hook that returns `[value, toggle]` looks like `useState` — until you destructure it and find both elements typed as `boolean | (() => void)`.',
        '',
        'Array literals infer as arrays, so the positions are lost:',
        '',
        '```tsx-bad',
        'import { useState } from \'react\';',
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle];',
        '}',
        '',
        'const [isOpen] = useToggle(false);',
        'const flag: boolean = isOpen;',
        '```',
        '',
        '`as const` freezes the return into a readonly tuple, and each position keeps its own type:',
        '',
        '```tsx',
        'import { useState } from \'react\';',
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle] as const;',
        '}',
        '',
        'const [isOpen, toggle] = useToggle(false);',
        'const flag: boolean = isOpen;',
        '```',
        '',
        'That readonly tuple is exactly what `useState` itself returns, and it is why destructuring it with your own names has always worked.',
      ].join('\n'),
      brief: ['Make the two positions keep their own types.'].join('\n'),
      debrief: [
        'Tuple or object is a design decision, and there is a reasonable rule.',
        '',
        '**Tuple** when there are two values and the caller will want to rename them. That is `useState`\'s whole reason for returning one — you call it five times in a component and need five different names, and positional destructuring gives you that for free.',
        '',
        '**Object** for three or more, or when names carry meaning:',
        '',
        '```tsx',
        'export function useUser() {',
        '  return { user: null, isLoading: false, refetch: () => {} };',
        '}',
        '',
        'const { user, isLoading } = useUser();',
        '```',
        '',
        'Order stops mattering, callers take only what they need, and you can add a field later without breaking anyone. A five-element tuple, by contrast, is a puzzle at every call site.',
        '',
        'And that is the end of the curriculum.',
        '',
        'Look back at what this module actually needed. Union props are module 2\'s discriminated union. The generic list is module 3. The `as const` you just wrote is module 1, exercise 5. `ReactNode` and the event types are ordinary function and object types with React\'s names on them.',
        '',
        'There was never a separate skill called "TypeScript for React". There is TypeScript, and React is one of the places you point it — which is why the seven modules before this one were the actual work.',
        '',
        'From here the way to get better is to stop treating a red squiggle as an obstacle and start reading it as a claim about your program. It is usually right. When it is not, you now know enough to say precisely why.',
      ].join('\n'),
      fileName: 'exercise.tsx',
      starterCode: [
        "import { useState } from 'react';",
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle];',
        '}',
      ].join('\n'),
      hiddenChecks: [
        "import type { useToggle } from './exercise';",
        'type _cases = [',
        '  Expect<Equal<ReturnType<typeof useToggle>, readonly [boolean, () => void]>>,',
        '];',
      ].join('\n'),
      solution: [
        "import { useState } from 'react';",
        '',
        'export function useToggle(initial: boolean) {',
        '  const [on, setOn] = useState(initial);',
        '  const toggle = () => setOn((prev) => !prev);',
        '  return [on, toggle] as const;',
        '}',
      ].join('\n'),
      hints: [
        'The check expects a `readonly` tuple, which is a strong hint about which tool to reach for.',
        'You met it in module 1, applied to an array of strings.',
        'Append `as const` to the returned array literal.',
      ],
    },
  ],
};
